src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Note this field is only used on the Investment Entity Page Layout</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled_Steps__c</fullName>
        <label>Cancelled Steps</label>
        <summaryFilterItems>
            <field>Process_Step__c.Status__c</field>
            <operation>contains</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Process_Step__c.Process__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Completed_Steps__c</fullName>
        <label>Completed Steps</label>
        <summaryFilterItems>
            <field>Process_Step__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Process_Step__c.Process__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NA_Steps__c</fullName>
        <description>Used for the formula field Process Status</description>
        <label>N/A Steps</label>
        <summaryFilterItems>
            <field>Process_Step__c.Status__c</field>
            <operation>equals</operation>
            <value>N/A</value>
        </summaryFilterItems>
        <summaryForeignKey>Process_Step__c.Process__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Steps__c</fullName>
        <label>Total Steps</label>
        <summaryForeignKey>Process_Step__c.Process__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Process_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Process Owner is the person who instantiates the process for a record.</inlineHelpText>
        <label>Assign to Process Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_to_Record_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Record Owner is the person who owns the record where the process is being instantiated.</inlineHelpText>
        <label>Assign to Record Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessManager_T.cls
@isTest
private class ProcessManager_T {

	static Account entity;
	static Process_Template__c template;
	static Process__c process1;
	static User user1;
	
	private static void setup() {
		entity = new Account(
			Name = 'testacc'
		);
		insert entity;
		
		template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Entity'
		);
		insert template;

		process1 = new Process__c(
			Name = 'testprocess',
			Auto_Create_Tasks__c = true,
			Process_Template__c = template.Id,
			Entity__c = entity.Id
		);
		insert process1;
		
		Profile profile = [Select Id from Profile where Name = 'System Administrator'];
		user1 = new User(Username= 'test9090@test.com', FirstName='Test User', LastName='9090', 
                             Email= 'test9090@test.com', Alias='t9090', CommunityNickname='test9090@test.com', 
                             IsActive=true, TimeZoneSidKey='America/Los_Angeles', 
                             LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', ProfileId = profile.Id); 
		insert user1;
	}

	@isTest 
	private static void test() {
		setup();
		Process__c process2 = new Process__c(
			Name = 'testprocess2',
			Process_Template__c = template.Id,
			Entity__c = entity.Id
		);
		insert process2;
		process2 = [SELECT Auto_Create_Tasks__c FROM Process__c WHERE Id = :process2.Id];
		System.assert(process2.Auto_Create_Tasks__c, 'Expected Auto_Create_Tasks__c to be true');
	}
	
	@isTest
	private static void stopProcess() {
		setup();
		
		Process_Step__c step1 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 1,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);

		insert step1;
		ProcessManager mgr = new ProcessManager();
		mgr.stopProcess(process1.Id);
		
		Process__c tmpProcess = [Select Id, Status__c from Process__c where Id =: process1.Id];
		system.assertEquals('Cancelled', tmpProcess.Status__c);
		
		step1 = [SELECT Status__c FROM Process_Step__c WHERE Id = :step1.Id];
		system.assertEquals(ProcessManager.PROCESS_STEP_STATUS_CANCELLED, step1.Status__c);
		
	}
	
	@isTest
	private static void stopProcessNoSteps() {
		setup();

		ProcessManager mgr = new ProcessManager();
		mgr.stopProcess(process1.Id);
		
		Process__c tmpProcess = [Select Id, Status__c from Process__c where Id =: process1.Id];
		system.assertEquals('Not Started', tmpProcess.Status__c);
		
		system.assertEquals([Select id from Process_Step__c where Process__c =: process1.Id].size(), 0);
		
	}
	
	@isTest
	private static void stopProcessWitMoreThan100Steps() {
		setup();
		
		List<Process_Step__c> steps = new List<Process_Step__c>();
		for (Integer i = 0; i < 150; i++){
			Process_Step__c step = new Process_Step__c(
				Process__c = process1.Id,
				Sequence__c = i,
				Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
			);
			steps.add(step);
		}
		
		insert steps;
		system.assertEquals([Select Id from Process_Step__c where Status__c =: ProcessManager.PROCESS_STEP_STATUS_OPEN ].size(), 150);
		
		// Cancell process1
		ProcessManager mgr = new ProcessManager();
		mgr.stopProcess(process1.Id);
		
		Process__c tmpProcess = [Select Id, Status__c from Process__c where Id =: process1.Id];
		system.assertEquals('Cancelled', tmpProcess.Status__c);
		
		steps = [SELECT Status__c FROM Process_Step__c WHERE Id IN : steps];
		system.assertEquals([Select Id from Process_Step__c where Status__c =: ProcessManager.PROCESS_STEP_STATUS_CANCELLED].size(), 150);
		
	}

	@isTest
	private static void insertProcessSteps() {
		setup();
		Process_Template_Step__c templateStep1 = new Process_Template_Step__c(
			Process_Template__c = template.Id,
			Assign_To_Role__c = 'Primary Advisor',
			Sequence__c = 1,
			Details__c = 'details'
		);
		insert templateStep1;
		
		Process_Template_Step__c templateStep2 = new Process_Template_Step__c(
			Process_Template__c = template.Id,
			Assign_To_Role__c = 'Primary Advisor',
			Sequence__c = 1,
			Details__c = 'details'
		);
		insert templateStep2;
		
		ProcessManager mgr = new ProcessManager();
		mgr.insertProcessSteps(template.Id, new List<Process__c> { process1 });
		
		List<Process_Step__c> steps = [SELECT Id FROM Process_Step__c 
			WHERE Process__c = :process1.Id];
		System.assertEquals(2, steps.size());
	}
	
	@isTest
	private static void insertProcessStepsAssigedToProcessOwner() {
		setup();
		Process_Template_Step__c templateStep1 = new Process_Template_Step__c(
			Process_Template__c = template.Id,
			Assign_To_Process_Owner__c = true,
			Sequence__c = 1,
			Details__c = 'details'
		);
		insert templateStep1;
		
		Process_Template_Step__c templateStep2 = new Process_Template_Step__c(
			Process_Template__c = template.Id,
			Assign_To_Process_Owner__c = true,
			Sequence__c = 1,
			Details__c = 'details'
		);
		insert templateStep2;
		
		ProcessManager mgr = new ProcessManager();
		mgr.insertProcessSteps(template.Id, new List<Process__c> { process1 });
		
		List<Process_Step__c> steps = [SELECT Id, Assigned_To__c FROM Process_Step__c 
			WHERE Process__c = :process1.Id];
		System.assertEquals(2, steps.size());
		system.assertEquals(steps.get(0).Assigned_To__c, UserInfo.getUserId());
		system.assertEquals(steps.get(1).Assigned_To__c, UserInfo.getUserId());
		
		// Verify that tasks were inserted and assigned to the process owner
		List<Task> tasks = [Select Id, OwnerId from Task where WhatId IN : steps];
		system.assertEquals(tasks.size(), 2);
		system.assertEquals(tasks.get(0).OwnerId, UserInfo.getUserId());
		system.assertEquals(tasks.get(1).OwnerId, UserInfo.getUserId());
	}
	
	@isTest
	private static void insertProcessStepsAssigedToRecordOwner() {
		setup();
		Process_Template_Step__c templateStep1 = new Process_Template_Step__c(
			Process_Template__c = template.Id,
			Assign_To_Process_Owner__c = true,
			Sequence__c = 1,
			Details__c = 'details'
		);
		insert templateStep1;
		
		Process_Template_Step__c templateStep2 = new Process_Template_Step__c(
			Process_Template__c = template.Id,
			Assign_To_Record_Owner__c = true,
			Sequence__c = 2,
			Details__c = 'details'
		);
		insert templateStep2;
		
		// Change the owner of the Entity
		entity.OwnerId = user1.Id;
		update entity;
		
		ProcessManager mgr = new ProcessManager();
		mgr.insertProcessSteps(template.Id, new List<Process__c> { process1 });
		
		List<Process_Step__c> steps = [SELECT Id, Assigned_To__c FROM Process_Step__c 
			WHERE Process__c = :process1.Id order by Sequence__c];
		System.assertEquals(2, steps.size());
		system.assertEquals(steps.get(0).Assigned_To__c, UserInfo.getUserId());
		system.assertEquals(steps.get(1).Assigned_To__c,user1.Id);
		
		// Verify that tasks were inserted and assigned to the process owner
		List<Task> tasks = [Select Id, OwnerId from Task where WhatId IN : steps];
		system.assertEquals(tasks.size(), 2);
		system.assertEquals(tasks.get(0).OwnerId, UserInfo.getUserId());
		system.assertEquals(tasks.get(1).OwnerId, user1.Id);
	}
	
	@isTest
	public static void setPredecessorsFromGenericSteps() {
		setup();
		Process_Step__c step1 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 1,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		insert step1;

		Process_Step__c step2 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 2,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		insert step2;
		
		Process_Step_Junction__c junction1 = new Process_Step_Junction__c(
			ParentStep__c = step1.Id,
			PredecessorStep__c = step2.Id
		); 
		insert junction1;
		
		GenericStep genericStep = new GenericStep();
		genericStep.Id = step1.Id;
		genericStep.PredecessorIds = step2.Id;

		ProcessManager mgr = new ProcessManager();
		mgr.setPredecessorsFromGenericSteps(new List<GenericStep>{ genericStep });

		List<Process_Step_Junction__c> junctions = [SELECT Id 
			FROM Process_Step_Junction__c];
		System.assertEquals(1, junctions.size());
	}
	
	@isTest
	public static void processStatusAndMasterTask(){
		setup();
		
		//Create for steps
		List<Process_Step__c> steps = new List<Process_Step__c>();
		Process_Step__c step1 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 1,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step1);

		Process_Step__c step2 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 2,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step2);
		
		Process_Step__c step3 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 3,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step3);
		
		Process_Step__c step4 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 4,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step4);
		
		insert steps;
		system.assertNotEquals(step1.Id, null);
		system.assertNotEquals(step2.Id, null);
		system.assertNotEquals(step3.Id, null);
		system.assertNotEquals(step4.Id, null);
		
		Test.startTest();
		// Query the process and ensure the status is Not started.
		
		process1 = [Select Id, Status__c, Total_Steps__c, Cancelled_Steps__c, NA_Steps__c, Completed_Steps__c from Process__c where id =: process1.Id];
		system.assertEquals(process1.Total_Steps__c, 4);
		system.assertEquals(process1.Cancelled_Steps__c, 0);
		system.assertEquals(process1.NA_Steps__c, 0);
		system.assertEquals(process1.Completed_Steps__c, 0);
		system.assertEquals(process1.Status__c, 'Not Started');
		
		// Query the master task, and ensure the stauts is Not Started.
		List<Task> masterTasks = [Select Id, status from Task where WhatId =: process1.Id];
		system.assertEquals(masterTasks.size(), 1);
		system.assertEquals(masterTasks.get(0).Status, 'Not Started');
		
		// Mark one step as N/a
		step1.Status__c = 'N/A';
		update step1;
		
		// Process status should be updated to In Progress
		process1 = [Select Id, Status__c, Total_Steps__c, Cancelled_Steps__c, NA_Steps__c, Completed_Steps__c from Process__c where id =: process1.Id];
		system.assertEquals(process1.Total_Steps__c, 4);
		system.assertEquals(process1.Cancelled_Steps__c, 0);
		system.assertEquals(process1.NA_Steps__c, 1);
		system.assertEquals(process1.Completed_Steps__c, 0);
		system.assertEquals(process1.Status__c, 'In Progress');
		
		// Master task status should be In Progress
		masterTasks = [Select Id, status from Task where WhatId =: process1.Id];
		system.assertEquals(masterTasks.size(), 1);
		system.assertEquals(masterTasks.get(0).Status, 'In Progress');
		
		
		// Mark one step as Completed
		step2.Status__c = 'Completed';
		update step2;
		
		// Process status should be updated to In Progress
		process1 = [Select Id, Status__c, Total_Steps__c, Cancelled_Steps__c, NA_Steps__c, Completed_Steps__c from Process__c where id =: process1.Id];
		system.assertEquals(process1.Total_Steps__c, 4);
		system.assertEquals(process1.Cancelled_Steps__c, 0);
		system.assertEquals(process1.NA_Steps__c, 1);
		system.assertEquals(process1.Completed_Steps__c, 1);
		system.assertEquals(process1.Status__c, 'In Progress');
		
		// Master task status should be In Progress
		masterTasks = [Select Id, status from Task where WhatId =: process1.Id];
		system.assertEquals(masterTasks.size(), 1);
		system.assertEquals(masterTasks.get(0).Status, 'In Progress');
		
		// Complete all the steps
		
		// Mark one step as N/a
		step3.Status__c = 'Completed';
		update step3;
		
		step4.Status__c = 'Completed';
		update step4;	
		
		// Process status should be updated to In Progress
		process1 = [Select Id, Status__c, Total_Steps__c, Cancelled_Steps__c, NA_Steps__c, Completed_Steps__c from Process__c where id =: process1.Id];
		system.assertEquals(process1.Total_Steps__c, 4);
		system.assertEquals(process1.Cancelled_Steps__c, 0);
		system.assertEquals(process1.NA_Steps__c, 1);
		system.assertEquals(process1.Completed_Steps__c, 3);
		system.assertEquals(process1.Status__c, 'Completed');
		
		// Master task status should be In Progress
		masterTasks = [Select Id, status from Task where WhatId =: process1.Id];
		system.assertEquals(masterTasks.size(), 1);
		system.assertEquals(masterTasks.get(0).Status, 'Completed');
		
		// Cancel one step
		step4.Status__c = 'Cancelled';
		update step4;	
		
		// Process status should be updated to In Progress
		process1 = [Select Id, Status__c, Total_Steps__c, Cancelled_Steps__c, NA_Steps__c, Completed_Steps__c from Process__c where id =: process1.Id];
		system.assertEquals(process1.Total_Steps__c, 4);
		system.assertEquals(process1.Cancelled_Steps__c, 1);
		system.assertEquals(process1.NA_Steps__c, 1);
		system.assertEquals(process1.Completed_Steps__c, 2);
		system.assertEquals(process1.Status__c, 'Cancelled');
		
		// Master task status should be In Progress
		masterTasks = [Select Id, status from Task where WhatId =: process1.Id];
		system.assertEquals(masterTasks.size(), 1);
		system.assertEquals(masterTasks.get(0).Status, 'Cancelled');
		Test.stopTest();
	}
	
	@isTest
	public static void editMasterTaskStatus(){
		setup();
		
		//Create for steps
		List<Process_Step__c> steps = new List<Process_Step__c>();
		Process_Step__c step1 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 1,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step1);

		Process_Step__c step2 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 2,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step2);
		
		Process_Step__c step3 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 3,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step3);
		
		Process_Step__c step4 = new Process_Step__c(
			Process__c = process1.Id,
			Sequence__c = 4,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step4);
		
		insert steps;
		system.assertNotEquals(step1.Id, null);
		system.assertNotEquals(step2.Id, null);
		system.assertNotEquals(step3.Id, null);
		system.assertNotEquals(step4.Id, null);
		
		Test.startTest();
		// Query the process and ensure the status is Not started.
		
		process1 = [Select Id, Status__c, Total_Steps__c, Cancelled_Steps__c, NA_Steps__c, Completed_Steps__c from Process__c where id =: process1.Id];
		system.assertEquals(process1.Total_Steps__c, 4);
		system.assertEquals(process1.Cancelled_Steps__c, 0);
		system.assertEquals(process1.NA_Steps__c, 0);
		system.assertEquals(process1.Completed_Steps__c, 0);
		system.assertEquals(process1.Status__c, 'Not Started');
		
		// Query the master task, and ensure the stauts is Not Started.
		List<Task> masterTasks = [Select Id, status from Task where WhatId =: process1.Id];
		system.assertEquals(masterTasks.size(), 1);
		system.assertEquals(masterTasks.get(0).Status, 'Not Started');
		
		// update the master task status, and ensure you cannot set a status that differs from the process status
		masterTasks.get(0).Status = 'Complete';
		Boolean exceptionThrown = false;
		String exceptionMessage = '';
		
		try{
			update masterTasks;
		}catch (Exception ex){
			exceptionThrown = true;
			exceptionMessage = ex.getMessage();
		}
		
		system.assert(exceptionThrown);
		system.assert(exceptionMessage.contains('This task is tied to a Process, and you cannot change the status because it is controlled by the Process.'));
		Test.stopTest();
	}
	
	
	
	@isTest
	public static void processStepAndTaskStatusSync(){
		setup();
		
		//Create for steps
		List<Process_Step__c> steps = new List<Process_Step__c>();
		Process_Step__c step1 = new Process_Step__c(
			Process__c = process1.Id,
			Assigned_To__c = Userinfo.getUserId(),
			Sequence__c = 1,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step1);

		Process_Step__c step2 = new Process_Step__c(
			Process__c = process1.Id,
			Assigned_To__c = Userinfo.getUserId(),
			Sequence__c = 2,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step2);
		
		Process_Step__c step3 = new Process_Step__c(
			Process__c = process1.Id,
			Assigned_To__c = Userinfo.getUserId(),
			Sequence__c = 3,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step3);
		
		Process_Step__c step4 = new Process_Step__c(
			Process__c = process1.Id,
			Assigned_To__c = Userinfo.getUserId(),
			Sequence__c = 4,
			Status__c = ProcessManager.PROCESS_STEP_STATUS_OPEN
		);
		steps.add(step4);
		
		insert steps;
		system.assertNotEquals(step1.Id, null);
		system.assertNotEquals(step2.Id, null);
		system.assertNotEquals(step3.Id, null);
		system.assertNotEquals(step4.Id, null);
		
		Test.startTest();
		// Query the process and ensure the status is Not started.
		
		List<Task> tasks = [Select Id, Status, WhatId from Task where WhatId IN : steps];
		system.assertEquals(tasks.size(), 4);
		
		Map<Id, Task> stepToTask = new Map<Id,Task>();
		for (Task task : tasks){
			stepToTask.put(task.WhatId, task);
		}
		
		system.assertEquals(stepToTask.get(step1.Id).Status, 'Not Started');
		system.assertEquals(stepToTask.get(step2.Id).Status, 'Not Started');
		system.assertEquals(stepToTask.get(step3.Id).Status, 'Not Started');
		system.assertEquals(stepToTask.get(step4.Id).Status, 'Not Started');
		
		// update tasks to ensure they update the ste status
		stepToTask.get(step1.Id).Status = 'Completed';
		stepToTask.get(step2.Id).Status = 'Not Started';
		stepToTask.get(step3.Id).Status = 'In Progress';
		stepToTask.get(step4.Id).Status = 'Cancelled';
		update tasks;
		
		Map<Id, Process_Step__c>stepsMap = new Map<Id,Process_Step__c>([Select Id, Status__c, Completed_By__c, Completed_Date__c from Process_Step__c]);
		system.assertEquals(steps.size(), 4);
		system.assertEquals(stepsMap.get(step1.Id).Status__c, 'Completed');
		system.assertEquals(stepsMap.get(step2.Id).Status__c, 'Open');
		system.assertEquals(stepsMap.get(step3.Id).Status__c, 'Open');
		system.assertEquals(stepsMap.get(step4.Id).Status__c, 'N/A');
		Test.stopTest();
	}
	
}