src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Designed for recording information about Client Households</description>
        <label>Client Household</label>
    </recordTypes>
    <recordTypes>
        <fullName>Client_Business</fullName>
        <active>true</active>
        <description>Designed for recording information about Client Businesses</description>
        <label>Client Business</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_Revenue__c.object
<CustomObject>
    <description>XLR8 custom object that tracks the management of new policies and the renewal of existing policies.</description>
    <label>Case Management</label>
    <nameField>
        <label>Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <recordTypes>
        <fullName>Commercial_Insurance</fullName>
        <active>true</active>
        <description>Commercial Auto, Liability, Property, Umbrella and Workers Comp</description>
        <label>Commercial Insurance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Executive_Benefits</fullName>
        <active>true</active>
        <description>Executive Bonus, Life, Compensation, and Retirement</description>
        <label>Executive Benefits</label>
    </recordTypes>
    <recordTypes>
        <fullName>Group_Benefits</fullName>
        <active>true</active>
        <description>Group Health, Disability, and Life</description>
        <label>Group Benefits</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual_Life_Insurance</fullName>
        <active>true</active>
        <description>Case Management for Individual Life Insurance</description>
        <label>Individual Life Insurance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual_Other_Insurance</fullName>
        <active>true</active>
        <description>Individual Insurance for Disability, Health, LTC, P&amp;C, Umbrella</description>
        <label>Individual Other Insurance</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retirement_Plans</fullName>
        <active>true</active>
        <description>Group Retirement Plans - 401(a), 401(k), 403(b), 457</description>
        <label>Retirement Plans</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Potential_Revenue_Fields_Ids__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Entity_c__c</fullName>
        <label>Entity__c</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Potential_Revenue_Fields_Ids</label>
</CustomObject>

src/classes/NFPUtils.cls
/*
 *Utils class for NFP
 *@author Ximena Lasserre
 *@since October 2015
 */
public with sharing class NFPUtils {
    
    public static final String CLIENT_HOUSEHOLD = 'Client Household'; 
    public static final String CLIENT_BUSINESS = 'Client Business'; 
    public static final String COMMERCIAL_INSURANCE = 'Commercial Insurance'; 
    public static final String GROUP_BENEFITS = 'Group Benefits'; 
    public static final String EXECUTIVE_BENEFITS = 'Executive Benefits'; 
    public static final String RETIREMENT_PLANS = 'Retirement Plans'; 
    public static final String INDIVIDUAL_LIFE_INSURANCE = 'Individual Life Insurance'; 
    public static final String INDIVIDUAL_OTHER_INSURANCE = 'Individual Other Insurance'; 
        
    /*
     * Gets the record type of the entity 
     * whose id is passed as a param 
     * @param Id entityId
     * @return String
     */
    public static String getEntityRecordTypeName(Id entityId){
        List<Account> relatedEntity = [SELECT RecordType.Name
                                         FROM Account
                                        WHERE Id = :entityId];
        if(relatedEntity.size() != 0){
            return relatedEntity[0].RecordType.Name;
        }                         
        return '';
    }
    
    
    /*
     * Gets the record type of the entity 
     * whose id is passed as a param 
     * @param Id entityId
     * @return String
     */
    public static Map<Id, String> getEntityRecordTypeNames(Set<Id> entityIds){
        Map<Id,String> result = new Map<Id,String>();
        
        for (Account account : [SELECT RecordType.Name
                                         FROM Account
                                        WHERE Id = :entityIds AND
                                              RecordTypeId != null]){
            result.put(account.Id, account.RecordType.Name);                                
        }     
                         
        return result;
    }
    
    
    public static Map<Id, String> getPotentialRevenueRecordTypes(Set<Id> recordTypeIds){
        Map<Id,String> result = new Map<Id,String>();
        List<RecordTypeInfo> recordTypes = Potential_Revenue__c.SObjectType.getDescribe().getRecordTypeInfos();
        
        if (recordTypes != null && recordTypes.size() > 0){
            for (RecordTypeInfo rt : recordTypes){
                if (rt.isAvailable() && !rt.isMaster()){
                    if (recordTypeIds == null || recordTypeIds.contains(rt.getRecordTypeId())){
                        result.put(rt.getRecordTypeId(), rt.getName());
                    }
                }            
            }
        }
                              
        return result;
    }
    
    
    
    /*
     *Checks if the potentialRevRecordType which is the potential revenue record type
     *is valid for the entity record type (entityRecordType)
     *@param String potentialRevRecordType
     *@param String entityRecordType
     *@return boolean
     */
    public static boolean checkIfPotentialRevenueRecordTypeValid(String potentialRevRecordType, String entityRecordType){
         
        if (potentialRevRecordType == null || potentialRevRecordType == '' || entityRecordType == null || entityRecordType == ''){
            return false;
        }
        
        if(entityRecordType.equalsIgnoreCase(CLIENT_HOUSEHOLD)){
            if(potentialRevRecordType.equalsIgnoreCase(COMMERCIAL_INSURANCE) || 
               potentialRevRecordType.equalsIgnoreCase(EXECUTIVE_BENEFITS) ||
               potentialRevRecordType.equalsIgnoreCase(GROUP_BENEFITS) || 
               potentialRevRecordType.equalsIgnoreCase(RETIREMENT_PLANS)){
                return false;
            }
        }else if(entityRecordType.equalsIgnoreCase(CLIENT_BUSINESS)){
            if(potentialRevRecordType.equalsIgnoreCase(INDIVIDUAL_LIFE_INSURANCE) ||
            potentialRevRecordType.equalsIgnoreCase(INDIVIDUAL_OTHER_INSURANCE)){
                return false;
            }
        }
        
        return true;
    }
    
    /*
     * Insert Potential_Revenue_Fields_Ids__c custom settings 
     * with the corresponding field ids
     */
    public static void insertPotentialRevenueFieldsId(){
        
        //create custom settings
        Potential_Revenue_Fields_Ids__c potentialRevenueCustomSetting = new Potential_Revenue_Fields_Ids__c();
        potentialRevenueCustomSetting.Name = 'Potential_Revenue__c';
        String entityFieldId = ToolingAPIUtils.getFieldId(true, 'Potential_Revenue', 'Entity');
		entityFieldId = entityFieldId != null && !entityFieldId.startsWithIgnoreCase('CF') ? 'CF' + entityFieldId.substring(0,15) : entityFieldId;
        
        potentialRevenueCustomSetting.Entity_c__c = entityFieldId;
                            
        //insert custom settings
        try{
            insert potentialRevenueCustomSetting;
        }catch(Exception ex){
            system.debug('EXCEPTION: Could not insert custom settings: ' + ex.getMessage());
        }   
    }
    
    public static List<RecordType> getRecordTypes(Set<Id> recordTypeIds){
        List<RecordType> result = new List<RecordType>();
        
        if (recordTypeIds != null && recordTypeIds.size() > 0){
            result = [Select Id, Name, Description from RecordType where ID IN : recordTypeIds ORDER BY Name ASC];
        }
        
        return result;
    }
    
    public static String getProfileName(){
        List<Profile> profiles = [Select Id, Name from Profile where Id =: UserInfo.getProfileId()];
        
        if (profiles.size() == 1){
            return profiles[0].Name;
        }
        
        return '';
    }
    
}