src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Note this field is only used on the Investment Entity Page Layout</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age_EOY__c</fullName>
        <formula>((DATE((YEAR(TODAY())),12,31))-(Birthdate))/365.25</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age EOY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Process_Template__r.Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration In Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Client Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Case_Role__c</fullName>
        <label>Assign to Case Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Case Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user will be assigned this step every time the template is instantiated on a record.</inlineHelpText>
        <label>Assign to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration in Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RMD_Factors__c.object
<CustomObject>
    <description>XLR8 custom object that contains the RMD Uniform, Single and Joint IRS Life Expectancy Values, which are used to calculate RMD.</description>
    <fields>
        <fullName>Age_EOY__c</fullName>
        <label>Age EOY</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RMD Factors</label>
    <nameField>
        <label>RMD Table ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XLR8_Assets_Liabilities__c.object
<CustomObject>
    <description>XLR8 custom object that holds Client Household Use Assets, Financial Assets, Retirement Assets and Liabilities data.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>401K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>529 Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aircraft Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airplane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automobiles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boat Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brokerage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection (Artwork, Stamps, Coins)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity Line of Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Tax Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inherited IRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inherited Roth IRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRA Rollover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irrevocable Living Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Margin Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Notes/Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Property &amp; Furniture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Residence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Describe this debt&apos;s interest rate or terms.  E.g. 5 year adjustable arm with initial rate of 6.7%</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets &amp; Liabilities</relationshipLabel>
        <relationshipName>R00N40000001YLFUEA4</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Opening</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Assets &amp; Liabilities</label>
    <nameField>
        <label>Asset/Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets &amp; Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestUtility.cls
public with sharing class TestUtility {
	
	public static Process_Template__c createProcessTemplate(String name, String templateType, String templateCategory, String description, Boolean autoCreateTasks){
		Process_Template__c result = new Process_Template__c();
		result.Name = name;
		result.Type__c = templateType;
		result.Category__c = templateCategory;
		result.Description__c = description;
		result.Auto_Create_Tasks_Default__c = autoCreateTasks;
		return result;
	}
	
	public static Process_Template__c createProcessTemplate(String name, String templateType){
		Process_Template__c result = new Process_Template__c();
		result.Name = name;
		result.Type__c = templateType;
		return result;
	}
	
	public static Process_Template_Step__c createProcessTemplateStep(String name, String details, Integer duration, Id templateId, Id userId, String caseRole){
		Process_Template_Step__c result = new Process_Template_Step__c();
		result.Name = name;
		result.Details__c = details;
		result.Duration_In_Days__c = duration;
		result.Process_Template__c = templateId;
		result.Assign_to_User__c = userId;
		result.Assign_To_Case_Role__c = caseRole;
		
		return result;
	}
	
	public static Process_Template_Step__c createProcessTemplateStep(String name, Id templateId, Integer sequence, String caseRole){
		Process_Template_Step__c result = new Process_Template_Step__c();
		result.Name = name;
		result.Process_Template__c = templateId;
		result.Sequence__c = sequence;
		result.Assign_To_Case_Role__c = caseRole;
		return result;
	}
	
	public static Process__c createProcess(String name, Id templateId, Id caseId){
		Process__c result = new Process__c();
		result.Name = name;
		result.Process_Template__c = templateId;
		result.Case__c = caseId;
		
		return result;	
	}
	
	public static Process__c createAccountProcess(String name, Id templateId, Id accountId){
		Process__c result = new Process__c();
		result.Name = name;
		result.Process_Template__c = templateId;
		result.Entity__c = accountId;
		
		return result;	
	}
	
	public static Process_Step__c createProcessStep(String name, Id processId, String status, Integer sequence){
		Process_Step__c result = new Process_Step__c();
		result.Name = name;
		result.Process__c = processId;
		result.Status__c = status;
		result.Sequence__c = sequence;
		return result;
	}
	
	public static Case createCase(String status, String origin){
		Case result = new Case();
		result.Status = status;
		result.Origin = origin;
		
		return result;
	}
	
	public static Account createAccount(String name){
		Account result = new Account();
		result.Name = name;
		return result;
	}
	
	public static Contact createContact(String firstName, String lastName){
		Contact result = new Contact();
		result.FirstName = firstName;
		result.LastName = lastName;
		return result;
	}
	
	public static Lead createLead(String firstName, String lastName, String company, String status){
		Lead result = new Lead();
		result.FirstName = firstName;
		result.LastName = lastName;
		result.Company = company;
		result.Status = status;
		return result;
	}
	
	public static Opportunity createOpportunity(String Name, Date closeDate, String stage){
		Opportunity result = new Opportunity();
		result.Name = name;
		result.CloseDate = closeDate;
		result.StageName = stage;
		return result;
	}
	
	public static User createUser (String userName,Id userProfile, String alias, String firstName, String lastName ){ 
        return new User(Username= userName+'@test.com', FirstName=firstName, LastName=lastName, 
                             Email= userName+'@test.com', Alias=alias, CommunityNickname=userName, 
                             IsActive=true, TimeZoneSidKey='America/Los_Angeles', 
                             LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', ProfileId = userProfile); 
    }
	
	public static XLR8_Assets_Liabilities__c createAsset(Id entityId){
        XLR8_Assets_Liabilities__c asset = new XLR8_Assets_Liabilities__c();
        
        asset.Entity__c = entityId;
        
        return asset;
    }
    
    public static RMD_Factors__c createFactor(Integer age, Integer age2, String calculationType, Decimal factor){
    	RMD_Factors__c factor1 = new RMD_Factors__c();
        factor1.Age_EOY__c = age; 
        factor1.Age_EOY_2__c = age2; 
        factor1.Calculation_Type__c = calculationType;
        factor1.RMD_Factor__c = factor;
        
        return factor1;
    }
	
}