src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Designed for recording information about Client Households</description>
        <label>Client Household</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_Revenue__c.object
<CustomObject>
    <description>XLR8 custom object that tracks the management of new policies and the renewal of existing policies.</description>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Management</relationshipLabel>
        <relationshipName>Potential_Revenue</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opened_Date__c</fullName>
        <inlineHelpText>Select or enter the start date for this Case.</inlineHelpText>
        <label>Opened Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referred_by_Other__c</fullName>
        <inlineHelpText>Referral source text up to 30 characters.</inlineHelpText>
        <label>Referred by Other</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Case Management</label>
    <nameField>
        <label>Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Management</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PotentialRevenueTriggerTest.cls
/*
 *Test class for PotentialRevenueTrigger
 *@author Ximena Lasserre
 *@since November 2015
 */
@isTest
public with sharing class PotentialRevenueTriggerTest {

	@testSetup static void setup(){
		Account acc1 = new Account();
		acc1.Name = 'Client Household Account';
		acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client Household').getRecordTypeId();
		insert acc1;
		
		Account acc2 = new Account();
		acc2.Name = 'Client Business Account';
		acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client Business').getRecordTypeId();
		insert acc2;		
		
		Potential_Revenue__c potentialRevenue = new Potential_Revenue__c();
		potentialRevenue.Name = 'Test Potential Revenue';
		potentialRevenue.Entity__c = acc1.Id; 
		potentialRevenue.RecordTypeId = Schema.SObjectType.Potential_Revenue__c.getRecordTypeInfosByName().get('Individual Life Insurance').getRecordTypeId();
		potentialRevenue.Referred_by_Other__c = 'Referred by Test';
		potentialRevenue.Opened_Date__c = Date.today();
		insert potentialRevenue;
		
	}
	
	static testmethod void testPotentialRevenueTrigger(){
		
		String exceptionExpected;
		
		Test.startTest();
		Id lifeInsuranceId = Schema.SObjectType.Potential_Revenue__c.getRecordTypeInfosByName().get('Individual Life Insurance').getRecordTypeId();
		
		List<Potential_Revenue__c> potentialRevs = [SELECT Id, RecordTypeId
													 FROM Potential_Revenue__c LIMIT 1];
		Id invalidRecordType = Schema.SObjectType.Potential_Revenue__c.getRecordTypeInfosByName().get('Commercial Insurance').getRecordTypeId();											 
		potentialRevs[0].RecordTypeId = invalidRecordType;
		
		try{
			update potentialRevs;
		}catch(Exception ex){
			exceptionExpected = ex.getMessage();
		}
		Test.stopTest();
		
		List<Potential_Revenue__c> potentialRevAfterUpdate = [SELECT Id, RecordTypeId
													            FROM Potential_Revenue__c LIMIT 1];
		
		system.assert(exceptionExpected != null, 'There was no exception when updating with invalid record type.');											            
		system.assert(potentialRevAfterUpdate[0].RecordTypeId.equals(lifeInsuranceId), 'The potential revenue record type changed. Trigger did not work.');											            
	}
}