src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Note this field is only used on the Investment Entity Page Layout</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Type__c</fullName>
        <formula>TEXT(Process_Template__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Template Type</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration In Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Predecessor_Steps__c</fullName>
        <label>Predecessor Steps</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_Details__c</fullName>
        <label>Step Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XLR8ProcessUtils.cls
public with sharing class XLR8ProcessUtils {

	public static Process__c getProcessAndSteps(Id processId, String stepStatus){
		Process__c result = null;
		
		if (processId != null){
			List<Process__c> processes = [SELECT Status__c,  
												 (SELECT Status__c 
												   FROM Process_Steps__r 
												  WHERE Status__c =: stepStatus) 
											FROM Process__c 
										   WHERE Id =: processId];
			
			if (processes.size() == 1){
				result = processes.get(0);
			}
		}
		
		return result;
	}
	
	public static List<Process__c> getProcessesById(Set<Id> processIds){
		List<Process__c> processes = null;
		
		if (processIds != null && processIds.size() > 0){
			processes = [SELECT  Id, Name,
								 Auto_Create_Tasks__c,
								 Entity__c, Entity__r.Name,
								 Case__c, Case__r.CaseNumber,
								 Contact__c, Contact__r.Name,
								 Lead__c, Lead__r.Name,
								 Opportunity__c, Opportunity__r.Name,
								 Template_Type__c, Process_Template__r.Auto_Create_Tasks_Default__c
							FROM Process__c 
						   WHERE Id IN : processIds];
		}
		
		return processes;
	}
	
	public static List<Process_Step__c> getSteps(List<Process_Step__c> selectedSteps){
		List<Process_Step__c> steps = null;
		
		if (selectedSteps != null && selectedSteps.size() > 0){
			steps = [Select Name, Sequence__c,Duration_In_Days__c, Step_Details__c, 
							Predecessor_Steps__c, Assigned_To__c, Status__c, Process__c, 
							Process__r.Name
					 From Process_Step__c 
					 Where Id IN :selectedSteps];
			
			
		}
		
		return steps;
	}
	
	public static string getProcessName(Id processId){
		String processName = '';

		if (processId != null){
			List<Process__c> processes = [Select Id, Name from Process__c where id =: processId];
			if (processes.size() > 0){
				processName = processes.get(0).Name;
			}
		}
		
		return processName;
	}
}