src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Hierarchy_Group_ID__c</fullName>
        <formula>IF( 
ISBLANK(ParentId), 
Id , 
IF( 
ISBLANK(Parent.ParentId), 
Parent.Id, 
IF( 
ISBLANK(Parent.Parent.ParentId), 
Parent.Parent.Id, 
IF( 
ISBLANK(Parent.Parent.Parent.ParentId), 
Parent.Parent.Parent.Id, 
IF( 
ISBLANK(Parent.Parent.Parent.Parent.ParentId), 
Parent.Parent.Parent.Parent.Id, 
IF( 
ISBLANK(Parent.Parent.Parent.Parent.Parent.ParentId), 
Parent.Parent.Parent.Parent.Parent.Id, 
Parent.Parent.Parent.Parent.Parent.Parent.Id 
) 
) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the 15-character record id of the top-level Entity record in a Hierarchy Group.</inlineHelpText>
        <label>Hierarchy Group ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hierarchy_Id_As_Text__c</fullName>
        <description>This field is used internally by a workflow rule to store the text of the Hierarchy Group Id.  It should  not be placed on page layouts.  It is later used by a workflow rule and converted into the Hierarchy Group ID 18 field.</description>
        <inlineHelpText>This field is used internally by a workflow rule to store the text of the Hierarchy Group Id.  It should  not be placed on page layouts.   It is later used by a workflow rule and converted into the Hierarchy Group ID 18 field.</inlineHelpText>
        <label>Hierarchy Id As Text</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScriptForHierarchyIdFieldFixesBatch.cls
/**
 * Batch for updating null values of Hierarchy_Id_As_Text__c with Hierarchy_Group_ID__c values
 *
 *@author Ximena Lasserre
 *@since 2014-12
 */


global class ScriptForHierarchyIdFieldFixesBatch implements Database.Batchable<SObject>{
    
    /*
     * Queries all the existing accounts where Hierarchy_Id_As_Text__c is null and returns them
     * @Param Database.BatchableContext BC
     * @Return Database.queryLocator
     */
    global Database.queryLocator start(Database.BatchableContext BC){
            
        return Database.getQueryLocator([SELECT Id, Hierarchy_Group_ID__c, Hierarchy_Id_As_Text__c
                                         FROM Account 
                                         WHERE Hierarchy_Id_As_Text__c = null
                                         AND Hierarchy_Group_ID__c != null]);
    }
    
    /*
     * For each queried account it takes the value from Hierarchy_Group_ID__c
     * and copies it to Hierarchy_Id_As_Text__c
     * @Param Database.BatchableContext BC
     * @Param List<SObject> scope
     */
    global void execute(Database.BatchableContext BC, List<SObject> scope){
        
        for(SObject s: scope){
            Account a = (Account)s;
            a.Hierarchy_Id_As_Text__c = String.valueOf(a.Hierarchy_Group_ID__c);        
        }
        Database.update(scope, false);
    }
    
    /*
     * There is no need to do anything after the batch was executed
     * @Param Database.BatchableContext BC
     */
    global void finish(Database.BatchableContext BC){
        
    }
}