src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Note this field is only used on the Investment Entity Page Layout</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Enter the target completion date for the entire process.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HandleMassComplete_T.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes HandleMassComplete
 *
 */

@isTest
private class HandleMassComplete_T {

    static testMethod void testHandleMassComplete() 
    {
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Entity'
		);
		insert template;
		System.assertNotEquals(template.Id, null);
		
		Account entity = new Account(
			Name = 'testacc'
		);
		insert entity;

        Date tmpDate = Date.today();
        Process__c tmpProcess = new Process__c();
        tmpProcess.Name = 'TEST PROCESS PKS';
        tmpProcess.Deadline__c = (tmpDate + 5);
        tmpProcess.Process_Template__c = template.Id;
        tmpProcess.Entity__c = entity.Id;
        
        Test.startTest();
        Database.insert(tmpProcess);
        
        tmpProcess = null;
        List<Process__c> processes = Database.query('SELECT name, id, Process_Template__c,Entity__c FROM Process__c WHERE name=\'TEST PROCESS PKS\'');
        for (Process__c tmpObj: processes)
        {
            tmpProcess = tmpObj;
        }
        
        List<Process_Step__c> stepList = new List<Process_Step__c>(); 
        Process_Step__c step = new Process_Step__c();
        step.Name = ' TEST PROCESS STEP 1';
        step.Status__c = 'Open';
        step.Process__c = tmpProcess.Id;
        step.Sequence__c = 1;
        
        //Database.insert(step);
        stepList.add(step);
        
        step = new Process_Step__c();
        step.Name = ' TEST PROCESS STEP 2';
        step.Status__c = 'Open';
        step.Process__c = tmpProcess.Id;
        step.Sequence__c = 2;
        
        stepList.add(step);
        
        Database.insert(stepList);
        Integer idx = 0;
        List<Process_Step__c> steps = Database.query('SELECT Id, Name,Completed_By__c,Status__c,Completed_Date__c FROM Process_Step__c WHERE Process__c = \'' + tmpProcess.Id + '\'');
        Apexpages.currentPage().getParameters().put('retURL', tmpProcess.Id);
        ApexPages.StandardSetController setController = new ApexPages.StandardSetController(steps);
        setController.setSelected(steps);
        HandleMassComplete obj = new HandleMassComplete(setController);
        obj.firstItem();
        test.stopTest();
    }
}