src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Note this field is only used on the Investment Entity Page Layout</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Predecessor_Steps__c</fullName>
        <label>Predecessor Steps</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is intended to be a one-time setting to turn on Predecessor functionality for existing XLR8 users receiving package upgrade XLR8 V3.0.  This setting turns Predecessor functionality on for any newly instantiated processes and will not affect already existing processes.</description>
    <fields>
        <fullName>UseTaskHistory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Task History</label>
        <type>Checkbox</type>
    </fields>
    <label>Settings</label>
</CustomObject>

src/classes/ProcessStepManager_T.cls
@isTest
private class ProcessStepManager_T {

	@isTest
	private static void populatesSequence() {
		
		Settings__c settings = new Settings__c(
			Name = 'default',
			UseTaskHistory__c = true
		);
		insert settings;
		
		Process_Template__c template = new Process_Template__c(
			Name = 'template1',
			Type__c = 'Entity'
		);
		insert template;
		Account account1 = new Account(
			Name = 'testaccount'
		);
		insert account1;
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Process_Template__c = template.Id,
			Entity__c = account1.Id
		);
		insert process1;
		Process_Step__c step = new Process_Step__c(
			Process__c = process1.id,
			Name = 'somecrazyname'
		); 
		insert step;
		step = [SELECT Sequence__c FROM Process_Step__c WHERE Id = :step.Id];
		System.assertEquals(1, step.Sequence__c);
	}
	
	@isTest
	private static void populatePredecessorSequences() {
		Process_Template__c template = new Process_Template__c(
			Name = 'template1',
			Type__c = 'Entity'
		);
		insert template;
		Account account1 = new Account(
			Name = 'testaccount'
		);
		insert account1;
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Process_Template__c = template.Id,
			Entity__c = account1.Id
		);
		insert process1;
		Process_Step__c step = new Process_Step__c(
			Process__c = process1.id,
			Name = 'testprocessstep1',
			Sequence__c = 1
		); 
		insert step;
		Process_Step__c step2 = new Process_Step__c(
			Process__c = process1.id,
			Name = 'testprocessstep2',
			Sequence__c = 2
		); 
		insert step2;
		Process_Step_Junction__c junction = new Process_Step_Junction__c(
			ParentStep__c = step2.Id,
			PredecessorStep__c = step.Id
		);
		insert junction;
		step2 = [SELECT Predecessor_Steps__c FROM Process_Step__c WHERE Id = :step2.Id];
		System.assertEquals('1', step2.Predecessor_Steps__c);
	}	
	
	@isTest
	private static void updateRelatedTasks() {
		Process_Template__c template = new Process_Template__c(
			Name = 'template1',
			Type__c = 'Entity'
		);
		insert template;
		system.assertNotEquals(template.Id, null);
		
		Account account1 = new Account(
			Name = 'testaccount'
		);
		insert account1;
		
		system.assertNotEquals(account1.Id, null);
		
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Process_Template__c = template.Id,
			Entity__c = account1.Id
		);
		insert process1;
		system.assertNotEquals(process1.id, null);
		
		List<Process_Step__c> steps = new List<Process_Step__c>();
		Process_Step__c step = new Process_Step__c(
			Process__c = process1.id,
			Name = 'testprocessstep1',
			Sequence__c = 1,
			Status__c = 'Open'
		); 
		steps.add(step);
		
		Process_Step__c step2 = new Process_Step__c(
			Process__c = process1.id,
			Name = 'testprocessstep2',
			Sequence__c = 2,
			Status__c = 'N/A'
		); 
		steps.add(step2);
		
		Process_Step__c step3 = new Process_Step__c(
			Process__c = process1.id,
			Name = 'testprocessstep3',
			Sequence__c = 2,
			Status__c = 'Completed'
		); 
		steps.add(step3);
		
		insert steps;
		system.assertNotEquals(steps.get(0).Id, null);
		system.assertNotEquals(steps.get(1).Id, null);
		system.assertNotEquals(steps.get(2).Id, null);
		
		List<Task> tasks = new List<Task>();
		Task task = new Task(
			Subject = 'Test Process Step 1',
			Status = 'Not Started',
			WhatId = step.Id
		);
		tasks.add(task);
		
		Task task2 = new Task(
			Subject = 'Test Process Step 1',
			Status = 'Not Started',
			WhatId = step2.Id
		);
		tasks.add(task2);
		
		Task task3 = new Task(
			Subject = 'Test Process Step 1',
			Status = 'Not Started',
			WhatId = step3.Id
		);
		tasks.add(task3);
		
		insert tasks;
		system.assertNotEquals(tasks.get(0).Id, null);
		system.assertNotEquals(tasks.get(1).Id, null);
		system.assertNotEquals(tasks.get(2).Id, null);
		
		// verify that the tasks status is not started
		system.assertEquals([Select Id from Task where Status = 'Not Started'].size(),3);
		
		// update the step status
		step.Status__c = 'N/A'; // Open -> N/A
		step2.Status__c = 'Completed'; // N/A -> Completed
		step3.Status__c = 'Open'; // Completed -> Open
		update steps;
		
		// Verify that the tasks were updated
		Map<Id, Task> taskMap = new Map<Id,Task>([Select Id, Status from Task]);
		
		// Step is assigned to task, step status is N/A, so tasks status should be Cancelled
		system.assertEquals(taskMap.get(task.Id).Status, 'Cancelled');
				
		// Step2 is assigned to task2, step2 status is Completed, so tasks status should be Cancelled
		system.assertEquals(taskMap.get(task2.Id).Status, 'Completed');
		
		// Step3 is assigned to task3, step3 status is Open, so tasks status should be Not Started
		system.assertEquals(taskMap.get(task3.Id).Status, 'Not Started');
		
	}	
	
}