src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Note this field is only used on the Investment Entity Page Layout</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Enter the target completion date for the entire process.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HandleOwnerNotification_T.cls
/**
 * This class contains unit tests for validating the behavior of HandleOwnerNotification
*/
@isTest
private class HandleOwnerNotification_T {
	
	private static void initData(){
		
		// Insert a process Template
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Entity'
		);
		insert template;
		System.assertNotEquals(template.Id, null);
		
		// Insert an Account
		Account entity = new Account(
			Name = 'testacc'
		);
		insert entity;
		System.assertNotEquals(entity.Id, null);

		// Insert a process using the previously created acccont and template
        Process__c tmpProcess = new Process__c();
        tmpProcess.Name = 'TEST PROCESS PKS';
        tmpProcess.Deadline__c = Date.today().addDays(5);
        tmpProcess.Process_Template__c = template.Id;
        tmpProcess.Entity__c = entity.Id;
        insert tmpProcess;
        System.assertNotEquals(tmpProcess.Id, null);
		
		Process_Step__c step = new Process_Step__c();
        step.Name = 'TEST PROCESS STEP 1';
        step.Status__c = 'Open';
        step.Process__c = tmpProcess.Id;
        step.Sequence__c = 1;
        step.Assigned_To__c = Userinfo.getUserId();
        
		insert step;
        System.assertNotEquals(step.Id, null);
	}
    static testmethod void testOwnerNotification()
    {
    	initData();
        test.startTest();
        Process__c tmpProcess = [Select id from Process__c];
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(tmpProcess);
        HandleOwnerNotification controller = new HandleOwnerNotification(stdController);
        
        controller.handleMailNotification();
        
        // Verify that there were no errors
		system.assertNotEquals(controller.errors,null);
		system.assertEquals(controller.errors.size(),0);
		
		// Get the steps
		List<Process_Step__c> steps = [Select Id, Status__c from Process_Step__c];
		system.assertEquals(steps.size(),1);
		
		// Cancel the step
		ProcessActionsController.setCancelProcessStartedForTest();
		steps.get(0).Status__c = 'Cancelled';
		update steps.get(0);
		
		controller = new HandleOwnerNotification(stdController);
		controller.handleMailNotification();
		
		// Verify that there were errors
		system.assertNotEquals(controller.errors,null);
		system.assertEquals(controller.errors.size(),1);
		system.assertEquals(controller.errors.get(0),'This process is Cancelled, owners will not be notified.');
		
		// Complete the steps
		steps.get(0).Status__c = 'Completed';
		update steps.get(0);
		controller = new HandleOwnerNotification(stdController);
		controller.handleMailNotification();
        
        // Verify that there were errors
		system.assertNotEquals(controller.errors,null);
		system.assertEquals(controller.errors.size(),1);
		system.assertEquals(controller.errors.get(0),'This process is Completed, owners will not be notified.');
		
		update steps.get(0);
		// Instantiate the controller with a process that does not exist in the DB
		tmpProcess = new Process__c();
		stdController = new ApexPages.StandardController(tmpProcess);
		controller = new HandleOwnerNotification(stdController);
		
		controller.handleMailNotification();
		system.assertNotEquals(controller.errors,null);
		system.assertEquals(controller.errors.size(),1);
		system.assertEquals(controller.errors.get(0),'Process ID cannot be blank.');
        test.stopTest();
    }  
}