src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Client Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <inlineHelpText>This field is automatically populated with today&apos;s date when the Task Status is set to Completed and there is no Completion Date provided.</inlineHelpText>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FYI_List__c</fullName>
        <label>FYI List</label>
        <picklist>
            <picklistValues>
                <fullName>abuff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sdola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMesc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>jland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>restr</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Import_ID__c</fullName>
        <label>Import ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meaningful_Activity_Flat__c</fullName>
        <label>Meaningful Activity Flat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meaningful_Activity__c</fullName>
        <label>Meaningful Activity</label>
        <picklist>
            <picklistValues>
                <fullName>Last ADV Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Estate Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Financial Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Fund Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Goals Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Insurance Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last IPS Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Issue Questionnaire Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Portfolio Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Privacy Notice Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Rebalancing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Risk Tolerance Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Tax Plan Review</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Send_FYI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send FYI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Task__c</fullName>
        <label>Task Sub-Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Open/Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charitable Giving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trades: Cash Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trades: Rebal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Duration__c</fullName>
        <inlineHelpText>This field is not related to the activity durations used by the Task Timer functionality.  It is a separate field that allows for the manual entry of time spent on a Task.  You must enter the task duration in quarter hour increments.  Ex.  1.25, .25, .50</inlineHelpText>
        <label>Task Duration (Manual)</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ToDo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Process_Template__r.Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is intended to be a one-time setting to turn on Predecessor functionality for existing XLR8 users receiving package upgrade XLR8 V3.0.  This setting turns Predecessor functionality on for any newly instantiated processes and will not affect already existing processes.</description>
    <fields>
        <fullName>UseTaskHistory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Task History</label>
        <type>Checkbox</type>
    </fields>
    <label>Settings</label>
</CustomObject>

src/objects/Task_History__c.object
<CustomObject>
    <description>XLR8 custom object that records the history of changes made to Task records.</description>
    <fields>
        <fullName>Activity_ID__c</fullName>
        <label>Activity ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To_ID__c</fullName>
        <label>Assigned To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Lead_ID__c</fullName>
        <label>Contact/Lead ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meaningful_Activity__c</fullName>
        <label>Meaningful Activity</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To_ID__c</fullName>
        <label>Related To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Duration__c</fullName>
        <label>Task Duration</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Sub_Category__c</fullName>
        <label>Task Sub-Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Task History</label>
    <nameField>
        <displayFormat>TH-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Task History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task_Timer_Activity__c.object
<CustomObject>
    <description>XLR8 custom object that records the date and time spent on a given Task.</description>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Task Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Task Timer Activity</label>
    <nameField>
        <displayFormat>Timer Activity {0}</displayFormat>
        <label>Task Timer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Timer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskManager.cls
/*
 * Handles various activities related to Tasks. Current implementation sets the 
 * "Meaingful Activity Flat" field. 
 ************************************************************************************************************************
 * Revision History
 * Change #     Developer       Date        Description
 ************************************************************************************************************************
 * 1.1         Jason Landry    02/12/15     PlanIO 710 - Exception on Comment when FYI checked, but user not selected
 */
public without sharing class TaskManager {
    
    private Map<Id, User> userMap;
    private User runningUser;
    @TestVisible private static Boolean taskHistoryRecordsCreated = false;
    private static Boolean commentHistoryUpdated = false;
    
    /*
     * Call from before insert and before update triggers
     */
    public void beforeInsertUpdate(Map<Id, Task> oldTaskMap, List<Task> newTasks) {
        buildMaps(newTasks);
        runningUser = [SELECT Name, Alias FROM User WHERE Id = :UserInfo.getUserId()];

        for (Task newTask : newTasks) {
            newTask.Activity_Date__c = newTask.ActivityDate;
            Task oldTask;
            if (oldTaskMap != null) {
                oldTask = oldTaskMap.get(newTask.Id);
            }
            if (oldTask == null || 
                    oldTask.Meaningful_Activity__c != newTask.Meaningful_Activity__c) {
                setMeaningfulActivityFlat(newTask);
            }
            
            if ((oldTask == null || oldTask.Status != newTask.Status) 
                && (newTask.Status == 'Completed' || newTask.Status == 'Cancelled') && newTask.Completion_Date__c == null && newTask.Import_Id__c == null) {
                newTask.Completion_Date__c = Date.today();
            }
            
            if (!commentHistoryUpdated) {
                updateComments(newTask, oldTask);
            }
        }
    }
    
    public void beforeDelete(List<Task> tasks) {
        List<Id> taskIds = new List<Id>();
        Map<Id, Task> taskMap = new Map<Id, Task>();
        for (Task task1 : tasks) {
            taskIds.add(task1.Id);
            taskMap.put(task1.Id, task1);
        }
        List<Task> tasksWithType = [SELECT Id, What.Type FROM Task WHERE Id IN :taskIds];
        for (Task task1 : tasksWithType) {
            if (task1.What != null && task1.What.Type.endsWith('Process__c')) {
                Task taskToReject = taskMap.get(task1.Id);
                taskToReject.addError('Cannot delete a Process Master Task');
            }
        }
    }
    
    public void afterInsert(Map<Id, Task> newTaskMap) {
        system.debug('&&&&&& ' + taskHistoryRecordsCreated);
        if (!taskHistoryRecordsCreated) {
            createTaskHistoryRecords(newTaskMap.values(), false);
        }
    }
    
    public void afterUpdate(Map<Id, Task> oldTaskMap, Map<Id, Task> newTaskMap) {
        if (!taskHistoryRecordsCreated) {
            createTaskHistoryRecords(newTaskMap.values(), false);
        }
        updateTaskTimerActivityStatus(oldTaskMap, newTaskMap);
    }
    
    public void afterDelete(List<Task> tasks) {
        if (!taskHistoryRecordsCreated) {
            createTaskHistoryRecords(tasks, true);
        }
    }
    
    private boolean useTaskHistory(){
        Boolean useTaskHistory = false;
        Settings__c settings = null;
        system.debug('&&&&&& ' + Settings__c.getAll());
        if (Settings__c.getAll() != null && Settings__c.getAll().size() > 0){
            settings = Settings__c.getAll().values().get(0);    
        }
        
        if (settings != null && settings.useTaskHistory__c){
            useTaskHistory = true;
        }
        
        return useTaskHistory;
    }
    
    private void updateTaskTimerActivityStatus(Map<Id, Task> oldTaskMap, Map<Id, Task> newTaskMap){
        Map<Id, Task> tasks = new Map<Id, Task>();
        for (Task task : newTaskMap.values()){
            if (task.Subject != oldTaskMap.get(task.Id).Subject){
                tasks.put(task.Id, task);
            }               
        }
        List<Task_Timer_Activity__c> activities = null;
        if (tasks.size() > 0){
            activities = TaskTimerUtils.getTaskTimerActivities(tasks.keySet());         
        }
        
        if (activities != null && activities.size() > 0){
            for (Task_Timer_Activity__c activity : activities){
                activity.Task_Subject__c = tasks.get(activity.Task_ID__c).Subject;
            }
            
            try{
                update activities;
            }catch (Exception ex){}
        }
        
    }
    
    private void createTaskHistoryRecords(List<Task> tasks, Boolean isDelete) {
        taskHistoryRecordsCreated = true;
        Boolean useTaskHistory =  useTaskHistory();
        List<Task_History__c> histories = new List<Task_History__c>();          
        system.debug('&&&&& ' + useTaskHistory);
        if (useTaskHistory){
            for (Task task1 : tasks) {
                Task_History__c history = makeTaskHistory(task1);
                if (isDelete) {
                    history.Status__c = 'Deleted';
                }
                histories.add(history);
            }
            insert histories;
        }
    }
    
    private Task_History__c makeTaskHistory(Task task1) {
        Task_History__c history = new Task_History__c(
            Activity_ID__c = task1.Id,
            Comments__c = task1.Description,
            Status__c = task1.Status,
            Subject__c = task1.Subject,
            Due_Date__c = task1.ActivityDate,
            Completion_Date__c = task1.Completion_Date__c,
            Assigned_To_ID__c = task1.OwnerId,
            Priority__c = task1.Priority,
            Category__c = task1.Category__c,
            Task_Type__c = task1.Task_Type__c,
            Task_Sub_Category__c = task1.Sub_Category_Task__c,
            Task_Duration__c = task1.Task_Duration__c,
            Meaningful_Activity__c = task1.Meaningful_Activity__c,
            Related_To_ID__c = task1.WhatId,
            Contact_Lead_ID__c = task1.WhoId 
        );
        return history;
    }

    private void buildMaps(List<Task> newTasks) {
        Set<Id> userIds = new Set<Id>();
        for (Task newTask : newTasks) {
            userIds.add(newTask.CreatedById);
        }
        userMap = new Map<Id, User>([SELECT Name, Alias FROM User WHERE Id IN :userIds]);
    }
    
    private void updateComments(Task newTask, Task oldTask) {
        commentHistoryUpdated = true;
        if (newTask.Description == null) {
            return;
        }
        if ((oldTask != null && newTask.Description != oldTask.Description)
            || oldTask == null || newTask.Send_FYI__c) {
            String userAlias = runningUser.Alias;
            String description = Datetime.now().formatLong() + ' ' + userAlias; 
             
            //if (newTask.Send_FYI__c) { 1.1 --
            if (newTask.Send_FYI__c && newTask.FYI_List__c != null){ //1.1++
                description += ' FYI to ';
                Boolean first = true;
                for (String fyiValue : newTask.FYI_List__c.split(';')) {
                    if (!first) {
                        description += ', '; 
                    }
                    description += fyiValue;
                    first = false;
                }
            }
            description += '\r\n' + newTask.Description;
            newTask.Description = description;
        }
    }
    
    private void setMeaningfulActivityFlat(Task t) {
        if (t.Meaningful_Activity__c == null) {
            t.Meaningful_Activity_Flat__c = null;
            return;
        }
        String flatValue = '';
        t.Meaningful_Activity_Flat__c = t.Meaningful_Activity__c;
    }
    
    private String taskClosedStatus() {
        TaskStatus ts = [SELECT MasterLabel FROM TaskStatus WHERE IsClosed = TRUE LIMIT 1];
        return ts.MasterLabel;
    }
}