src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Timer_Billable_Hours__c</fullName>
        <inlineHelpText>This is the roll-up of the amount of timed activities where the billable checkbox was checked.</inlineHelpText>
        <label>Timer Billable Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timer_Non_Billable_Hours__c</fullName>
        <inlineHelpText>This is the roll-up of the amount of timed activities where the billable checkbox was NOT checked.</inlineHelpText>
        <label>Timer Non Billable Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task_Timer_Activity__c.object
<CustomObject>
    <description>XLR8 custom object that records the date and time spent on a given Task.</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that the time spent on this activity is billable.</inlineHelpText>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the duration of the timed activity.  By default it will start at 0.00 but he user has the option of setting a start time for the timer.  For Example, if they already spent 2 hours and want to start timer at 2 hours, then they would enter 2.0.</inlineHelpText>
        <label>Duration</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Task Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Task Timer Activity</label>
    <nameField>
        <displayFormat>Timer Activity {0}</displayFormat>
        <label>Task Timer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Timer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskTimerUtils.cls
/*
 * Utils class for ProjectTimerController
 * 
 * @author Ximena Lasserre
 * @since 01-2015
 */
public with sharing class TaskTimerUtils {
	
	
   /*
    * This method returns a task timer activity record for a given task timer activity Id
    * @param id of the record that must be returned
    * @return task timer activity
    */
    public static Task_Timer_Activity__c getTaskTimerActivity(Id recordId){        
       	Task_Timer_Activity__c timer = null;
       	
		if (recordId != null){
			List<Task_Timer_Activity__c> records = [Select Id,Date__c,Description__c ,Billable__c ,Duration__c, Task_ID__c, Task_Subject__c 
											From Task_Timer_Activity__c
											Where Id =: recordId];
			
			if (records.size() > 0){
				timer = records.get(0);
			}
       	}
       	
       	return timer;
    }
    
    
    /*
    * This method returns a list of task timer activities for a given task id
    * @param id of the record that must be returned
    * @return task timer activity
    */
    public static List<Task_Timer_Activity__c> getTaskTimerActivities(Id taskId, Integer pageOffset){        
       	List<Task_Timer_Activity__c> activities = null;
       	
		if (taskId != null){
			activities = [Select Id, Name, Date__c,Description__c ,Billable__c ,Duration__c, Task_ID__c , Task_Subject__c
											From Task_Timer_Activity__c
											Where Task_ID__c =: taskId																					
											order by Description__c asc
											limit 5	
											offset : pageOffset];
       	}
       	
       	return activities;
    }
    
    /*
    * This method returns a list of task timer activities for a given task id
    * @param id of the record that must be returned
    * @return task timer activity
    */
    public static List<Task_Timer_Activity__c> getTaskTimerActivities(Set<Id> taskIds){        
       	List<Task_Timer_Activity__c> activities = null;
       	
		if (taskIds != null){
			activities = [Select Id, Task_Subject__c, Task_ID__c from Task_Timer_Activity__c where Task_ID__c IN : taskIds];
       	}
       	
       	return activities;
    }
    
    /*
    * This method returns the number of task timer activities for a given task
    * @param id of the record that must be returned
    * @return task timer activity
    */
    public static Integer getTaskTimerActivitiesCount(Id taskId){        
       	Integer recordsCount = 0;
       	
		if (taskId != null){
			recordsCount = [select count() from Task_Timer_Activity__c where Task_ID__c =: taskId]; 
       	}
       	
       	return recordsCount;
    }
    
    /*
    * This method returns a task for a given task Id
    * @param id of the task that must be returned
    * @return task
    */
    public static Task getTask(Id recordId){        
       	Task task = null;
       	
		if (recordId != null){
			List<Task> records = [Select Id, Subject
											From Task
											Where Id =: recordId];
			
			if (records.size() > 0){
				task = records.get(0);
			}
       	}
       	
       	return task;
    }
    
    
    
    
    public static List<Task> getTasks(Set<Id> taskIds){
    	List<Task> tasks = null;
    	
    	if (taskIds != null && taskIds.size() > 0){
    		tasks = [Select Id, Timer_Billable_Hours__c, Timer_Non_Billable_Hours__c from Task where Id IN : taskIds];
    	}
    	
    	return tasks;
    }
}