src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age_EOY__c</fullName>
        <formula>((DATE((YEAR(TODAY())),12,31))-(Birthdate))/365.25</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age EOY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RMD_Factors__c.object
<CustomObject>
    <description>XLR8 custom object that contains the RMD Uniform, Single and Joint IRS Life Expectancy Values, which are used to calculate RMD.</description>
    <fields>
        <fullName>Age_EOY_2__c</fullName>
        <label>Age EOY 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Age_EOY__c</fullName>
        <label>Age EOY</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calculation_Type__c</fullName>
        <label>Calculation Type</label>
        <picklist>
            <picklistValues>
                <fullName>JOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNIFORM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMD_Factor__c</fullName>
        <label>RMD Factor</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>RMD Factors</label>
    <nameField>
        <label>RMD Table ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RMD_Requirement__c.object
<CustomObject>
    <description>XLR8 custom object for tracking RMD Requirements.</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>XLR8_Assets_Liabilities__c</referenceTo>
        <relationshipLabel>RMD Requirements</relationshipLabel>
        <relationshipName>RMD</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RMD_Calculated__c</fullName>
        <label>RMD Calculated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RMD_Calculation_Method__c</fullName>
        <label>RMD Calculation Method</label>
        <picklist>
            <picklistValues>
                <fullName>JOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNIFORM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMD_Factor__c</fullName>
        <inlineHelpText>This is the RMD factor used in the RMD Amount calculation, taken from the IRS Life Expectancy Table.</inlineHelpText>
        <label>RMD Factor</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Last_Updated_Date__c</fullName>
        <description>Date of the last update.</description>
        <label>RMD Last Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RMD_Member_Age_EOY__c</fullName>
        <formula>FLOOR( (DATE(VALUE( RMD_Year__c ), 12, 31) - Financial_Account__r.RMD_Member__r.Birthdate ) / 365.25)</formula>
        <label>RMD Member Age EOY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Member__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Financial_Account__r.RMD_Member__c ,  Financial_Account__r.RMD_Member__r.FirstName + &quot;  &quot; + Financial_Account__r.RMD_Member__r.LastName)</formula>
        <label>RMD Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMD_Override__c</fullName>
        <inlineHelpText>If the RMD has to be manually calculated in the case of Inherited IRAs, etc, then the user will manually calculate the RMD and populate this field with the amount.  If the override is done, that is the amount that will appear in the final RMD Amount field</inlineHelpText>
        <label>RMD Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse_Age_EOY__c</fullName>
        <formula>IF(OR( ISPICKVAL( RMD_Calculation_Method__c , &apos;UNIFORM&apos;),ISPICKVAL( RMD_Calculation_Method__c , &apos;SINGLE&apos;) ),NULL, FLOOR((DATE( VALUE( RMD_Year__c ), 12, 31) - Financial_Account__r.RMD_Spouse__r.Birthdate ) / 365.25))</formula>
        <label>RMD Spouse Age EOY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Financial_Account__r.RMD_Spouse__c , Financial_Account__r.RMD_Spouse__r.FirstName + &quot; &quot; + Financial_Account__r.RMD_Spouse__r.LastName)</formula>
        <label>RMD Spouse</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMD_Year__c</fullName>
        <label>RMD Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Previous_EOY__c</fullName>
        <label>Value Previous EOY</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RMD Requirement</label>
    <nameField>
        <label>RMD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XLR8_Assets_Liabilities__c.object
<CustomObject>
    <description>XLR8 custom object that holds Client Household Use Assets, Financial Assets, Retirement Assets and Liabilities data.</description>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets &amp; Liabilities</relationshipLabel>
        <relationshipName>R00N40000001YLFUEA4</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RMD_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMD Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMD Member</relationshipLabel>
        <relationshipName>R00N40000001Zq5kEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMD Spouse</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets &amp; Liabilities (RMD Spouse)</relationshipLabel>
        <relationshipName>Assets_Liabilities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assets &amp; Liabilities</label>
    <nameField>
        <label>Asset/Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets &amp; Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestRMDBatchCalculator.cls
/*
 * Test class for RMDBatchCalculator class
 * @author Ximena Lasserre
 * @since Mar 2015
 */
 @isTest
public with sharing class TestRMDBatchCalculator {

	@testSetup static void setup(){
		
		//create the Account
		Account oneEntity = new Account(Name = 'One Entity');
        insert oneEntity;
        
        //create the contacts
        Contact c1 = new Contact();
        Contact c2 = new Contact();
        Contact c3 = new Contact();
        c1.Email = 'John@Doe.com';
        c1.LastName = 'Doe';
        c1.Birthdate = date.newInstance(1956, 4, 23);
        c2.Email = 'Jane@Doe.com';
        c2.LastName = 'Doe';
        c2.Birthdate = date.newInstance(1950, 9, 26); 
        c3.Email = 'Jim@Dune.com';
        c3.LastName = 'Dune';
        c3.Birthdate = date.newInstance(1940, 8, 28);
        insert c1; 
        insert c2; 
        insert c3;
        
        //create the RMD Factors
        RMD_Factors__c factor1 = new RMD_Factors__c();
        factor1.Age_EOY__c = 65; 
        factor1.Age_EOY_2__c = 59; 
        factor1.Calculation_Type__c = 'JOINT';
        factor1.RMD_Factor__c = 30.4;
        RMD_Factors__c factor2 = new RMD_Factors__c();
        factor2.Age_EOY__c = 63;
        factor2.Age_EOY_2__c = 57;
        factor2.Calculation_Type__c = 'JOINT';
        factor2.RMD_Factor__c = 31.3;
        RMD_Factors__c factor3 = new RMD_Factors__c();
        factor3.Age_EOY__c = 72;
        factor3.Calculation_Type__c = 'SINGLE';
        factor3.RMD_Factor__c = 15.5;
        RMD_Factors__c factor4 = new RMD_Factors__c();
        factor4.Age_EOY__c = 75;
        factor4.Calculation_Type__c = 'UNIFORM';
        factor4.RMD_Factor__c = 23.8;
        
        insert factor1;
        insert factor2;
        insert factor3;
        insert factor4;
        
		//create 2 assets and Liabilities 
		XLR8_Assets_Liabilities__c asset1 = new XLR8_Assets_Liabilities__c();
        asset1.Name = '2344';
        asset1.Entity__c = oneEntity.Id;
        asset1.RMD_Spouse__c = c1.Id;
        asset1.RMD_Member__c = c2.Id;
        insert asset1;
        
        RMD_Requirement__c req1 = new RMD_Requirement__c();
        req1.Financial_Account__c = asset1.Id;
        req1.Name = '2344-2015';
        req1.RMD_Override__c = 600.05;
        req1.RMD_Year__c = '2015'; //c1 59 c2 65
        req1.RMD_Calculation_Method__c = 'JOINT';
        req1.Value_Previous_EOY__c = 2000;
        insert req1;
        
        RMD_Requirement__c req2 = new RMD_Requirement__c();
        req2.Financial_Account__c = asset1.Id;
        req2.Name = '2344-2014';
        req2.RMD_Override__c = 200.05;
        req2.RMD_Year__c = '2014'; //c1 58 c2 64
        req2.RMD_Calculation_Method__c = 'UNIFORM';
        req2.Value_Previous_EOY__c = 2000;
        insert req2;
        
        XLR8_Assets_Liabilities__c asset2 = new XLR8_Assets_Liabilities__c();
        asset2.Name = '2345';
        asset2.Entity__c = oneEntity.Id;
        asset2.RMD_Member__c = c3.Id;
        insert asset2;
        
        RMD_Requirement__c req3 = new RMD_Requirement__c();
        req3.Financial_Account__c = asset2.Id;
        req3.Name = '2345-2013';
        req3.RMD_Override__c = 200.05;
        req3.RMD_Year__c = '2013'; //c1 56 c3 72
        req3.RMD_Calculation_Method__c = 'SINGLE';
        req3.Value_Previous_EOY__c = 2000;
        insert req3;
        
        RMD_Requirement__c req4 = new RMD_Requirement__c();
        req4.Financial_Account__c = asset2.Id;
        req4.Name = '2345-2015';
        req4.RMD_Override__c = 200.05;
        req4.RMD_Year__c = '2015'; //c1 59 c3 75
        req4.RMD_Calculation_Method__c = 'UNIFORM';
        req4.Value_Previous_EOY__c = 2000;
        insert req4;
	}
	
	@isTest static void TestRMDBatchCalculatorController(){
		
		Test.startTest();
		
		//instantiate the page
		PageReference pageRef = Page.RMDBatchCalculator;
		Test.setCurrentPage(pageRef);
		
		//instantiate the controller and calculate without setting the year
		RMDBatchCalculatorController batchCalcController = new RMDBatchCalculatorController();
		batchCalcController.calculateRMDAmount();
		
		//verify that there was an error
		system.assert(batchCalcController.errors.size() > 0, 'There were errors when not passing a year to the controller.');
		
		//set the year
		batchCalcController.year = '2015';
		batchCalcController.calculateRMDAmount();
		
		List<CronTrigger> ctBefore = [SELECT Id, TimesTriggered, NextFireTime 
                		    		    FROM CronTrigger
                		    		   WHERE CronJobDetail.Name LIKE 'RMD Calculator%'];
       
        //verify the batch has been scheduled        		    
        system.assert(ctBefore.size() == 1, 'There is no scheduled cron trigger.');  
        system.assert(ctBefore[0].TimesTriggered == 0, 'The batch has run or there is no batch scheduled.');  
        						      
        Test.stopTest(); 
        
	}
	
	@isTest static void TestRMDBatchCalculator(){
		
		Test.startTest();
		
		Id batchId = Database.executeBatch(new RMDAmountBatchCalculator('2015'));
        
		Test.stopTest();
		
		//verify the batch has already run
        List<RMD_Requirement__c> rmdReqs = [SELECT RMD_Member_Age_EOY__c, RMD_Spouse_Age_EOY__c, RMD_Year__c, 
       											   RMD_Factor__c, RMD_Last_Updated_Date__c, RMD_Calculated__c, RMD_Calculation_Method__c
       									      FROM RMD_Requirement__c
       									     WHERE RMD_Year__c = '2015'];
       									      
        for(RMD_Requirement__c req : rmdReqs){
        	system.assert(req.RMD_Factor__c != null, 'RMD Factor was not updated.');
        	system.assert(req.RMD_Last_Updated_Date__c != null, 'RMD Last Updated Date was not updated.');  
        	system.assert(req.RMD_Calculated__c != null, 'RMD Calculated was not updated.');  
        }	
        
        system.assert(rmdReqs.size() == 2, 'There were not 2 updated RMD Requirements');     
        
	}
	
}