src/objects/Data_Mover_Scheduled_Job__c.object
<CustomObject>
    <fields>
        <fullName>Creator_Email__c</fullName>
        <label>Creator Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_Expression__c</fullName>
        <label>Cron Expression</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Data Mover Scheduled Job</label>
    <nameField>
        <label>Scheduled Job Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Mover Scheduled Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mapping_Object__c.object
<CustomObject>
    <fields>
        <fullName>Data_Mover_Scheduled_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Mover Scheduled Job</label>
        <referenceTo>Data_Mover_Scheduled_Job__c</referenceTo>
        <relationshipLabel>Mapping Objects</relationshipLabel>
        <relationshipName>Mapping_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mapping Object</label>
    <nameField>
        <label>MappingObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataMoverDataMappingScheduledBatch.cls
/**
 * Scheduled class to run the batch DataMoverDataMappingBatch
 * @author Ximena Lasserre
 * @since 2014-12
 */
public class DataMoverDataMappingScheduledBatch implements Schedulable{

	/*
	 * Executes the DataMoverDataMappingBatch class for 
	 * each mapping object that there is
	 * @param SchedulableContext sc
	 */ 
	 public void execute(SchedulableContext sc){ 
		List<Data_Mover_Scheduled_Job__c> scheduledJob;
		if(!Test.isRunningTest()){
			//get the job's id
			String jobId = String.ValueOf(sc.getTriggerId());
			
			//query the Data_Mover_Scheduled_Job__c for that job  
			scheduledJob = [SELECT Id, Name, Creator_Email__c, Cron_Expression__c, End_Date__c,
								   Job_Id__c, Start_Date__c,
								   (SELECT Id
								      FROM Mapping_Objects__r)
						      FROM Data_Mover_Scheduled_Job__c
							 WHERE Job_Id__c = :jobId LIMIT 1];
		}else{
			scheduledJob = [SELECT Id, Name, Creator_Email__c, Cron_Expression__c, End_Date__c,
								 Job_Id__c, Start_Date__c,
								 (SELECT Id
								    FROM Mapping_Objects__r)
				   		      FROM Data_Mover_Scheduled_Job__c LIMIT 1];
			
		}
			
			//if the current date is within the start date and end date continue 
		if(scheduledJob.size() > 0){
			if(Datetime.now().date() >= scheduledJob[0].Start_Date__c && Datetime.now().date() <= scheduledJob[0].End_Date__c){
				List<Id> mappingObjectIds = new List<Id>();
				for(Data_Mover_Scheduled_Job__c jobs : scheduledJob){
					for(Mapping_Object__c mapObj : jobs.Mapping_Objects__r){
						mappingObjectIds.add(mapObj.Id);
					}
				}
				
				if(mappingObjectIds.size() > 0){
					DataMoverDataMappingBatch sac = new DataMoverDataMappingBatch(mappingObjectIds, scheduledJob[0].Name, null);
					Database.executebatch(sac, 200);
				}
			}	
		}
	}
}