src/objects/Field_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Object_Mapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mapping Object</label>
        <referenceTo>Mapping_Object__c</referenceTo>
        <relationshipLabel>Field Mappings</relationshipLabel>
        <relationshipName>FieldsMapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Field_API_Name__c</fullName>
        <label>Source Field API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Field Mapping</label>
    <nameField>
        <label>Field Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mapping_Object__c.object
<CustomObject>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_External_ID_API_Name__c</fullName>
        <label>Source External ID API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_External_ID_is_Name_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true the source external id is the name field of the object.</description>
        <label>Source External ID is Name Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Object_API_Name__c</fullName>
        <label>Source Object API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_External_ID_API_Name__c</fullName>
        <label>Target External ID API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_External_ID_is_Name_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If it is checked the external id field is the name field of the object.</description>
        <label>Target External ID is Name Field</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Object_API_Name__c</fullName>
        <label>Target Object API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Mapping Object</label>
    <nameField>
        <label>MappingObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataMoverDeleteSecuritiesBatch.cls
/* 
 *Batchable class to delete DM securities
 *@author Ximena Lasserre
 *@since September 2015
 */ 
global class DataMoverDeleteSecuritiesBatch implements Database.Batchable<sObject> {

	private String query;
	private String jobName;
	private Id jobLogId;
	private Mapping_Object__c securitiesMapObj;
	
	public DataMoverDeleteSecuritiesBatch(Mapping_Object__c securitiesMapObj, String jobName, Id jobLogId){
		this.query = 'SELECT Id FROM ' + securitiesMapObj.get('Target_Object_API_Name__c') + ' WHERE Package_of_Origin__c = \'' + securitiesMapObj.Package_Name__c + '\'';
		this.jobName = jobName;
		this.jobLogId = jobLogId;
		this.securitiesMapObj = securitiesMapObj;
	}
	
	global Database.QueryLocator start(Database.BatchableContext context) {
	    return Database.getQueryLocator(query);
	}
	  
	global void execute(Database.BatchableContext context, List<SObject> records) {
		delete records;
	}
	  
	global void finish(Database.BatchableContext context){
	  	//execute the batch to insert securities
	  	executeSecuritiesBatch(securitiesMapObj, jobName, jobLogId);
	}
	
	/*
     *Executes the batch class DataMoverSecuritiesDataMappingBatch
     *@param Mapping_Object__c mapObj
     *@param String jobName
     *@param Id jobLogId
     */
    private void executeSecuritiesBatch(Mapping_Object__c mapObj, String jobName, Id jobLogId){
    	List<Field_Mapping__c> fieldMappingForMapObj = mapObj.FieldsMapping__r;
											   
		Integer times = 0;
		String query = '';
		//iterate over fieldMappingForMapObj to create the query 
		if (fieldMappingForMapObj != null && fieldMappingForMapObj.size() > 0){
			query += 'SELECT ';
			for(Field_Mapping__c field : fieldMappingForMapObj){
				if(times < fieldMappingForMapObj.size() - 1){ 
					query += field.Source_Field_API_Name__c + ', ';
					times += 1;
				}
				else{ 
					query += field.Source_Field_API_Name__c;
				}				
			}			
			query += ' FROM ' + mapObj.Source_Object_API_Name__c;
		
			system.debug('### ' + query + '-' + 
				                  mapObj.Source_External_ID_API_Name__c + '-' + 
				                  mapObj.Target_External_ID_API_Name__c + '-' + 
				                  mapObj.Source_Object_API_Name__c + '-' + 
				                  mapObj.Target_Object_API_Name__c  + '-'+ 
				                  mapObj.Id + '-'+
				                  mapObj.Source_External_ID_is_Name_Field__c +'-'+
				                  mapObj.Target_External_ID_is_Name_Field__c +'-'+ 
				                  jobName + '-' + jobLogId + '-' + mapObj.Package_Name__c);

		}

		if (query != '' && query.length() > 0){
			DataMoverSecuritiesDataMappingBatch batch = new DataMoverSecuritiesDataMappingBatch(query, mapObj.Source_External_ID_API_Name__c,
									mapObj.Target_External_ID_API_Name__c, mapObj.Source_Object_API_Name__c, mapObj.Target_Object_API_Name__c,
									mapObj.Id, mapObj.Source_External_ID_is_Name_Field__c, mapObj.Target_External_ID_is_Name_Field__c,
									jobName, jobLogId, mapObj.Package_Name__c);
									
			//execute the batch	
			Database.executebatch(batch, 200);	
		}else{
			JobLogWrapper jobWrapper = new JobLogWrapper();
			ErrorLogWrapper error = new ErrorLogWrapper();
			error.errorDescription = 'Securities were not loaded because the mapping between Account Positions and Securities is not defined';
			jobWrapper.errorLogs.add(error);    
			DataMoverDataMappingBatchUtils.insertJobAndErrorLog(jobWrapper, jobName, jobLogId, true);         
		}
    }
}