src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Predecessor_Steps__c</fullName>
        <label>Predecessor Steps</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessStepManager.cls
public without sharing class ProcessStepManager {

    public void populateSequences(List<Process_Step__c> steps) {
        Set<Id> processIds = new Set<Id>();
        for (Process_Step__c step : steps) {
            processIds.add(step.Process__c);
        }
        AggregateResult[] results = [SELECT Process__c ProcessId, MAX(Sequence__c) MaxSeq FROM Process_Step__c 
            WHERE Process__c IN :processIds GROUP BY Process__c ];
        Map<Id, Double> maxSequenceByProcess = new Map<Id, Double>();
        for (AggregateResult result : results) {
            maxSequenceByProcess.put((Id) result.get('ProcessId'), (Double) result.get('MaxSeq'));
        }
        for (Process_Step__c step : steps) {
            if (step.Sequence__c == null) {
                Double maxSequence = maxSequenceByProcess.get(step.Process__c);
                if (maxSequence == null) {
                    maxSequence = 0;
                }
                step.Sequence__c = maxSequence + 1;
            }
        }
    }
    
    public void populatePredecessorSequences(List<Id> newStepIds) {
        List<Process_Step__c> newSteps = [SELECT Process__c, Sequence__c,
            (SELECT ParentStep__c, PredecessorStep__c, PredecessorStep__r.Sequence__c 
            FROM Process_Step_Junctions_Parent__r ORDER BY PredecessorStep__r.Sequence__c)
            FROM Process_Step__c WHERE Id IN :newStepIds];
        Map<Id, Process_Step__c> mapNewSteps = new Map<Id, Process_Step__c>(
            newSteps);
        Set<Id> processIds = new Set<Id>();
        for (Process_Step__c step : newSteps) {
            processIds.add(step.Process__c);
        }
        List<Process_Step__c> steps = [SELECT Process__c, Sequence__c,
            (SELECT ParentStep__c, PredecessorStep__c, PredecessorStep__r.Sequence__c 
            FROM Process_Step_Junctions_Parent__r ORDER BY PredecessorStep__r.Sequence__c)
            FROM Process_Step__c WHERE Process__c IN :processIds];
        Map<Id, Map<Id, Process_Step__c>> processMap = 
                new Map<Id, Map<Id, Process_Step__c>>(); 
        for (Process_Step__c step : newSteps) {
            if (step.Process_Step_Junctions_Parent__r == null) {
                step.Predecessor_Steps__c = null;
                continue;
            }
            List<String> sequences = new List<String>();
            for (Process_Step_Junction__c junction : step.Process_Step_Junctions_Parent__r) {
                sequences.add(String.valueOf(junction.PredecessorStep__r.Sequence__c));
            }           
            step.Predecessor_Steps__c = String.join(sequences, ', ');
        }
        if (isProcessStepUpdateable()){
            update newSteps;
        }
    }

    public void deleteJunctionObjectsForSteps(List<Process_Step__c> steps) { 
        List<Process_Step_Junction__c> junctions = [SELECT Id 
            FROM Process_Step_Junction__c 
            WHERE PredecessorStep__c IN :steps]; 
        Boolean isDeleteable = Schema.sObjectType.Process_Step_Junction__c.isDeletable();
        if (isDeleteable){
            delete junctions;
        }
    }
    
    public void updateRelatedTasks(Map<Id,Process_Step__c> steps, Map<Id,Process_Step__c> oldSteps) {
        Set<ID> stepIDs = new Set<ID>();
        
        // Verify if the status has changed and it is not null
        for (Process_Step__c processStep: steps.values()) {
            if (processStep.Status__c != null && processStep.Status__c.trim().length() > 0 && 
               (oldSteps == null || (oldSteps != null && oldSteps.get(processStep.Id).Status__c != processStep.Status__c))) {
                stepIDs.add(processStep.Id);            
            }
        }
        
        
        if (!stepIds.isEmpty()) {
            List<Task> tasks = XLR8TaskUtils.getProcessStepTasks(stepIDs);
            if (tasks != null && tasks.size() > 0){
                
                // Set the status of tasks
                for (Task task : tasks) {
                    String stepStatus = steps.get(task.WhatID).Status__c;
                    if (stepStatus.equalsIgnoreCase('N/A')){
                        task.Status = 'Cancelled';
                    }else if (stepStatus.equalsIgnoreCase('Completed')){
                        task.Status = 'Completed';
                    }else if (stepStatus.equalsIgnoreCase('Open')){
                        task.Status = 'Not Started';
                    }else if (stepStatus.equalsIgnoreCase('Cancelled')){
                        task.Status = 'Cancelled';
                    }                   
                }
                
                //Update the tasks allowing to commit just the successfull changes
                if (isTaskUpdateable()){
                    Database.update(tasks, false);
                }
            }
        }    
    }   

    public void autoCreateTasks(List<Process_Step__c> steps) {
        Set<ID> processIds = new Set<ID>();
        for (Process_Step__c processStep: steps) {
            processIDs.add(processStep.Process__c);              
        }
        if (!processIds.isEmpty()) {
            AutoCreateTasks.processSteps(processIDs);
        }
    }   
    
    public void handleStatusChange(List<Process_Step__c> steps, Map<Id, Process_Step__c> oldStepMap) {
        for (Process_Step__c step : steps) {
            Process_Step__c oldStep = oldStepMap.get(step.Id);
            if (oldStep.Status__c != step.Status__c && step.Status__c != null) {
                if ('Open'.equalsIgnoreCase(step.Status__c)) {
                    step.Completed_By__c = null;
                    step.Completed_Date__c = null;
                }
                else if ('N/A'.equalsIgnoreCase(step.Status__c)
                    || step.Status__c.equalsIgnoreCase('Completed')
                    || step.Status__c.equalsIgnoreCase('Cancelled')) {
                    if (step.Completed_By__c == null) {
                        step.Completed_By__c = Userinfo.getUserId();
                    }
                    if (step.Completed_Date__c == null) {
                        step.Completed_Date__c = Date.today();
                    }
                }
            }
        }
    }   
    
    public void validateUniqueName(List<Process_Step__c> steps) {
        if (steps.size() > 1) {
            return;
        }
        for (Process_Step__c step: steps) {
            if (step.Process__c != null) {
                List<Process_Step__c> stepList = [SELECT Id, name, Process__c from  Process_Step__c 
                where Process__c =: step.Process__c
                AND name =: step.name AND id <>: step.id]; 
                if (!stepList.isEmpty()) {
                    step.Name.addError('Process step name is already in use');
                }
            }
            //Requeriments on Planio ticket #332
            /*List<Process_Step__c> stepList = [SELECT Id, name, Process__c, sequence__c 
                from Process_Step__c where Process__c =: step.Process__c
                AND sequence__c =: step.sequence__c AND id <>: step.id]; 
            if (!stepList.isEmpty()) {
                step.sequence__c.addError('This sequence number is already in use.'
                    + ' Please select another sequence number. ');
            }  */          
        }
    }
    
    private static Boolean isProcessStepUpdateable(){
        return (Schema.sObjectType.Process_Step__c.isUpdateable() && Process_Step__c.Predecessor_Steps__c.getDescribe().isUpdateable());
    }
    
    private static Boolean isTaskUpdateable(){
        return (Schema.Sobjecttype.Task.isUpdateable() &&  Task.Status.getDescribe().isCreateable());
    }
}