src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InitPredecessorsBatchable.cls
global class InitPredecessorsBatchable implements Database.Batchable<SObject> {

	global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator([SELECT Id FROM Process__c WHERE Status__c != 'Completed']);
	}
	
	global void execute(Database.BatchableContext context, List<Process__c> processes) {
		InitPredecessors mgr = new InitPredecessors();
		mgr.initPredecessors(processes);
	}
	
	global void finish(Database.BatchableContext context) {
	}
	
	public static void run() {
		InitPredecessorsBatchable b = new InitPredecessorsBatchable();
		Database.executeBatch(b);
	}
}