src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Completed_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HandleMassComplete.cls
public with sharing class HandleMassComplete 
{ 
    List<Process_Step__c> steps;

    public PageReference firstItem() {
        List<Process_Step__c> newSteps= new List<Process_Step__c>();
        String retUrl= Apexpages.currentPage().getParameters().get('retURL');
        Pagereference ref  = new Pagereference('/apex/showUncheckedItemsMsg?retUrl='+retUrl);
        if (!steps.isEmpty())
        {
            for(Process_Step__c step:steps )
            {
               newSteps.add(new Process_Step__c(Status__c = 'Completed', Id = step.Id
               ,Completed_By__c = Userinfo.getUserId()
               , Completed_Date__c = Date.today()));
            }
            
            //Update the process steps, checking if current user has perms to update
            if (isProcessStepUpdateable()){
            	Database.update(newSteps);
            }else{
            	ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have privileges to update porcess steps.');
				ApexPages.addMessage(myMsg); 
        	}            
            
            ref = new Pagereference(retURL);
        }
        return ref;
    }

    public HandleMassComplete(ApexPages.StandardSetController controller) 
    {
        steps = (List<Process_Step__c>) controller.getSelected();
    }
    
    private static Boolean isProcessStepUpdateable(){
    	return (Schema.sObjectType.Process_Step__c.isUpdateable() && Process_Step__c.Status__c.getDescribe().isUpdateable() && 
    			Process_Step__c.Completed_By__c.getDescribe().isUpdateable() && Process_Step__c.Completed_Date__c.getDescribe().isUpdateable());
    
	}
}