src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditProcessController_T.cls
@isTest
private class EditProcessController_T {
	
	@isTest
	private static void test() {
		Account entity = new Account(
			Name = 'testacc'
		);
		insert entity;
		
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Entity'
		);
		insert template;
		System.assertNotEquals(template.Id, null);

		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Auto_Create_Tasks__c = true,
			Process_Template__c = template.Id,
			Entity__c = entity.Id
		);
		
		EditProcessController cont = new EditProcessController(
			new ApexPages.StandardController(process1));
		cont.selectTemplate(); 
		cont.save();
		cont.getProcessName();
	}
	
		@isTest
	private static void testContact() {
		Contact entity = new Contact(
			FirstName = 'Contact',
			LastName = 'Test'
		);
		insert entity;
		System.assertNotEquals(entity.Id, null);
		
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Contact'
		);
		insert template;
		System.assertNotEquals(template.Id, null);
		
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Auto_Create_Tasks__c = true,
			Process_Template__c = template.Id,
			Contact__c = entity.Id
		);
		
		EditProcessController cont = new EditProcessController(
			new ApexPages.StandardController(process1));
		cont.selectTemplate(); 
		cont.save();
		System.assertEquals(cont.getTemplateType(), 'Contact');
		System.assertEquals([Select Id from Process__c].size(),1);
		System.assertEquals(cont.getProcessName(), 'testprocess');
	}
	
	@isTest
	private static void testLead() {
		Lead entity = new Lead(
			FirstName = 'Lead',
			LastName = 'Test',
			Company = 'Test Co',
			Status = 'Open'
		);
		insert entity;
		System.assertNotEquals(entity.Id, null);
		
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Lead'
		);
		insert template;
		System.assertNotEquals(template.Id, null);
		
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Auto_Create_Tasks__c = true,
			Process_Template__c = template.Id,
			Lead__c = entity.Id
		);
		
		EditProcessController cont = new EditProcessController(
			new ApexPages.StandardController(process1));
		cont.selectTemplate(); 
		cont.save();

		System.assertEquals(cont.getTemplateType(), 'Lead');
		System.assertEquals([Select Id from Process__c].size(),1);
		System.assertEquals(cont.getProcessName(), 'testprocess');
	}
	
	@isTest
	private static void testCase() {
		Case entity = new Case(
			Status = 'Open',
			Origin = 'Web'
		);
		insert entity;
		System.assertNotEquals(entity.Id, null);
		
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Case'
		);
		insert template;
		System.assertNotEquals(template.Id, null);
		
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Auto_Create_Tasks__c = true,
			Process_Template__c = template.Id,
			Case__c = entity.Id
		);
		
		EditProcessController cont = new EditProcessController(
			new ApexPages.StandardController(process1));
		cont.selectTemplate(); 
		cont.save();

		System.assertEquals(cont.getTemplateType(), 'Case');
		System.assertEquals([Select Id from Process__c].size(),1);
		System.assertEquals(cont.getProcessName(), 'testprocess');
	}
	
	@isTest
	private static void testOpportunity() {
		Opportunity entity = new Opportunity(
			Name = 'Oppty test',
			CloseDate = System.today(),
			StageName = 'Open'
		);
		insert entity;
		System.assertNotEquals(entity.Id, null);
		
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplate',
			Auto_Create_Tasks_Default__c = true,
			Type__c = 'Opportunity'
		);
		insert template;
		System.assertNotEquals(template.Id, null);
		
		Process__c process1 = new Process__c(
			Name = 'testprocess',
			Auto_Create_Tasks__c = true,
			Process_Template__c = template.Id,
			Opportunity__c = entity.Id
		);
		
		EditProcessController cont = new EditProcessController(
			new ApexPages.StandardController(process1));
		cont.selectTemplate(); 
		cont.save();

		System.assertEquals(cont.getTemplateType(), 'Opportunity');
		System.assertEquals([Select Id from Process__c].size(),1);
		System.assertEquals(cont.getProcessName(), 'testprocess');
	}
}