src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template_Type__c</fullName>
        <formula>TEXT(Process_Template__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Template Type</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XLR8ProcessWrapper.cls
public with sharing class XLR8ProcessWrapper {
	
	public Process__c processRecord { get; set; }
    public boolean unassignedSteps { get; set; }
    public String parentRecordName { get; set; }
    public Id parentRecordId { get; set; }
    public String templateType { get; set; }
    
    public XLR8ProcessWrapper(Process__c pProcess){
        processRecord = pProcess;
        initData();
    }
    
    public void initData(){
    	// Init default values
    	templateType = '';
    	parentRecordName = '';
    	parentRecordId = null;
    	unassignedSteps = false;
    	
    	// Initialize template Type
    	if (processRecord != null ){
    		templateType = processRecord.Template_Type__c;
    	}
    	
    	// Initialize the information of the parent record (Name and Id)
    	if (templateType != null && templateType != ''){
    		if (templateType == 'Entity'){
    			parentRecordName = processRecord.Entity__r.Name;
    			parentRecordId = processRecord.Entity__c;
    		}else if (templateType == 'Contact'){
    			parentRecordName = processRecord.Contact__r.Name;
    			parentRecordId = processRecord.Contact__c;
    		}else if (templateType == 'Case'){
    			parentRecordName = processRecord.Case__r.CaseNumber;
    			parentRecordId = processRecord.Case__c;
    		}else if (templateType == 'Lead'){
    			parentRecordName = processRecord.Lead__r.Name;
    			parentRecordId = processRecord.Lead__c;
    		}else if (templateType == 'Opportunity'){
    			parentRecordName = processRecord.Opportunity__r.Name;
    			parentRecordId = processRecord.Opportunity__c;
    		}else{
    			parentRecordName = '';
    		}
    	}
    	
    	// Check if the process has unassigned steps when the auto create tasks is on
    	if (processRecord != null && processRecord.Process_Template__c != null && 
            processRecord.Process_Template__r.Auto_Create_Tasks_Default__c && !processRecord.Auto_Create_Tasks__c){
            unassignedSteps = true;
        } 
    }
}