src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessTemplateBatchable_T.cls
@isTest
private class ProcessTemplateBatchable_T {
	
	@isTest
	private static void test() {
		Process_Template__c template = new Process_Template__c(
			Name = 'testtemplatename123',
			Type__c = 'Entity'
		);
		insert template;
		
		Test.startTest();
		
		ProcessTemplateBatchable b = new ProcessTemplateBatchable();
		Database.executeBatch(b);
		Test.stopTest();
		
		template = [SELECT Type__c FROM Process_Template__c WHERE Id = :template.Id];
		System.assertEquals('Entity', template.Type__c);
	}

}