src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditProcessController.cls
public with sharing class EditProcessController {

	public String getTemplateType() {
		return [SELECT Type__c FROM Process_Template__c 
    			WHERE Id = :theProcess.Process_Template__c].Type__c;
	}

	public String getProcessName() {
		return theProcess.Name != null ? theProcess.Name : 'New Process';
	}

    private ApexPages.Standardcontroller controller;
    private Process__c theProcess;
    
    public EditProcessController(ApexPages.StandardController controller) {
    	this.controller = controller;
    	this.theProcess = (Process__c) controller.getRecord();
    }
    
    public void selectTemplate() {
		if (theProcess.Process_Template__c != null 
				&& !hasReadAccessToObject(getTemplateType())) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
			'You do not have access to the ' + getTemplateType() + ' object. Please select a'
			+ ' different template.'));
			theProcess.Process_Template__c = null;
		}
		else {
			theProcess.Auto_Create_Tasks__c = [SELECT Auto_Create_Tasks_Default__c 
				FROM Process_Template__c WHERE Id = :theProcess.Process_Template__c]
				.Auto_Create_Tasks_Default__c;
		}
    }
    
    private Boolean hasReadAccessToObject(String objectName) {
		if (objectName == 'Entity') objectName = 'Account';
		Map<String, Schema.SObjectType> describeMap = Schema.getGlobalDescribe();
		Schema.SObjectType token = describeMap.get(objectName);
		if (token == null) {
			return false;
		}
		return token.getDescribe().isAccessible();
    }
    
    public PageReference save() {
    	PageReference pr = null;
    	try { 
	    	clearInvisibleFields();
	    	saveInternal();
	    	pr = new ApexPages.StandardController(theProcess).view();
    	}
    	catch(Exception ex) {
    		ApexPages.addMessages(ex);
    	} 
    	return pr;
    }
    
    private void saveInternal() {
		ProcessManager manager = new ProcessManager();
		manager.save(theProcess);
    }
    
    private void clearInvisibleFields() {
		String templateType = getTemplateType();
		if (templateType != 'Contact') {
			theProcess.Contact__c = null;
		}
		if (templateType != 'Entity') {
			theProcess.Entity__c = null;
		}
		if (templatetype != 'Case') {
			theProcess.Case__c = null;
		}
		if (templateType != 'Opportunity') {
			theProcess.Opportunity__c = null;
		}
		if (templateType != 'Lead') {
			theProcess.Lead__c = null;
		}
    }
}