src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ValidateTemplateStepHelper.cls
//Helper Class for Validate Template Step Trigger
//Sankalp Shastri    04192011    Created Class

public with sharing class ValidateTemplateStepHelper
    {
    	//Validates the Template Step Name
        public static boolean validateName(boolean isUpdate, Process_Template_Step__c dbTemplateStep, Process_Template_Step__c newTemplateStep)
    		{
		         boolean result = false;
		         if (isUpdate && (newTemplateStep.Process_Template__c != null ))
		         {
		            if (newTemplateStep.Id != dbTemplateStep.Id)
		            {
		                if (newTemplateStep.name == dbTemplateStep.name && newTemplateStep.Process_Template__c == dbTemplateStep.Process_Template__c)
		                {
		                    result = true;
		                }
		            }
		         }
		         else if (newTemplateStep.Process_Template__c != null )
		         {
		            if (newTemplateStep.name == dbTemplateStep.name && newTemplateStep.Process_Template__c == dbTemplateStep.Process_Template__c)
		            {
		                result = true;
		            }
		         }
		         else
		         {
		            if (newTemplateStep.name == dbTemplateStep.name)
		            {
		                result = true;
		            }
		         }
		         return result;
    		}
    	
    	 //Validates the sequence		
    	 public static boolean validateSequence(boolean isUpdate, Process_Template_Step__c dbTemplateStep, Process_Template_Step__c newTemplateStep)
    		{
		         boolean result = false;
		         if (isUpdate && (newTemplateStep.Process_Template__c != null ))
		         {
		            if (newTemplateStep.Id != dbTemplateStep.Id)
		            {
		                if (newTemplateStep.Sequence__c == dbTemplateStep.Sequence__c && newTemplateStep.Process_Template__c == dbTemplateStep.Process_Template__c)
		                {
		                    result = true;
		                }
		            }
		         }
		         else if (newTemplateStep.Process_Template__c != null )
		         {
		            if (newTemplateStep.Sequence__c == dbTemplateStep.Sequence__c && newTemplateStep.Process_Template__c == dbTemplateStep.Process_Template__c)
		            {
		                result = true;
		            }
		         }
		         else
		         {
		            if (newTemplateStep.Sequence__c == dbTemplateStep.Sequence__c)
		            {
		                result = true;
		            }
		         }
		         return result;
    		}	
    }