src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InitPredecessorsBatchable_T.cls
/**
 * This class contains unit tests for validating the behavior of InitPredecessorsBatchable

 */
@isTest
private class InitPredecessorsBatchable_T {

  private static void initData(){
    //Create one case
    Case tcase = TestUtility.createCase('Open', 'Phone');
    insert tcase;
    
    System.assertNotEquals(tcase.Id, null); 
  
    //Create one template
    Process_Template__c template = TestUtility.createProcessTemplate('Sample Case Template', 'Case', 'Marketing','', false);
    insert template;
    System.assertNotEquals(template.Id, null);
    
    //Insert 100 process
    List<Process__c> processes = new List<Process__c>();
    for (Integer i = 0; i < 100; i++){
      processes.add(TestUtility.createProcess('Process' + i, template.Id, tcase.Id));
    }
    insert processes;
    
    //Verify processes were inserted
    processes = [Select Id from Process__c];
    System.assertEquals(processes.size(), 100);
  
    //Insert open steps for some processes
    List<Process_Step__c> steps = new List<Process_Step__c>();
    for (Integer i = 0; i < 80; i++){
      Id processId = processes.get(i).Id;
      steps.add(TestUtility.createProcessStep('Step ' + i + 'a', processId, 'Open', 1));
      steps.add(TestUtility.createProcessStep('Step ' + i + 'b', processId, 'Open', 2));
    }
    
    //Insert completed steps fro some processes
    for (Integer i = 80; i < 100; i++){
      Id processId = processes.get(i).Id;
      steps.add(TestUtility.createProcessStep('Step ' + i, processId, 'Completed', 1));
    }
    
    insert steps;
    
    //Verify steps were inserted
    steps = [Select Id from Process_Step__c];
    System.assertEquals(steps.size(), 180);
    
    //Verify that there are 80 open processes
    processes = [Select Id from Process__c where Status__c != 'Completed'];
    System.assertEquals(processes.size(), 80);
    
    
    //Verify that there are 20 completed processes
    processes = [Select Id from Process__c where Status__c = 'Completed'];
    System.assertEquals(processes.size(), 20);
  }
  
    static testMethod void myUnitTest() {
        //Create data for the test
        initData();
        
        //Start the test
        Test.startTest();
        
        //Verify that there aren't any Process_Step_Junction__c
        System.assertEquals([Select Id from Process_Step_Junction__c].size(), 0);
        
        //Execute the batch
        InitPredecessorsBatchable.run();
        
        //Stop the test
        Test.stopTest();
        
        //Verify that after running the test, Process_Step_Junction__c records were inserted
        System.assertEquals([Select Id from Process_Step_Junction__c].size(), 80);
        
    }
}