src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Enter the target completion date for the entire process.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exclude_From_Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude From Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration In Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_Details__c</fullName>
        <label>Step Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Created__c</fullName>
        <defaultValue>&quot;N&quot;</defaultValue>
        <label>Task Created</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AutoCreateTasks.cls
//Class for Auto Creating Tasks when Auto Create Check box if ON

// Changed By    Date        Comments
// Sankalp       04192011    Created the class 
public without sharing class AutoCreateTasks {
    
    public static Boolean Disable = false;
    
        //Logic for auto creating tasks
        public static void processSteps(Set<ID> processIDs) {

            if (Disable) {
                return;
            }
            try
                {   
                //Fetch all the steps where Process is marked for auto creation of tasks
                List<Process_Step__c> lstProcessSteps = new List<Process_Step__c>
                    (
                    [SELECT ID,Name,Process__c,Status__c, Assigned_To__c, Step_Details__c, 
                    Sequence__c,Task_Created__c, Process__r.Name, Process__r.Deadline__c,
                    Duration_In_Days__c,
                    (SELECT ParentStep__c, PredecessorStep__c, PredecessorStep__r.Status__c 
                    FROM Process_Step_Junctions_Parent__r)
                    FROM Process_Step__c 
                    WHERE Process__c IN : processIDs 
                          AND Process__r.Auto_Create_Tasks__c = true
                          AND Process__r.Exclude_From_Auto_Create_Tasks__c = false
                    ORDER BY Sequence__c LIMIT : Limits.getLimitQueryRows()
                    ]);
                
                //Process only if there are process steps returned
                if(lstProcessSteps.size() > 0)
                    {
                        //Fetch all the tasks for the available Process Step IDs
                        List<Task> lstTasks = new List<Task>
                            (
                            [Select ID, Status, WhatID 
                            FROM Task 
                            WHERE WhatID IN : lstProcessSteps LIMIT : Limits.getLimitQueryRows()
                            ]);
                        
                        //Create a MAP so that bulk update can be handled on Process Steps
                        Map<ID,List<Process_Step__c>> mapPS = new Map<ID,List<Process_Step__c>>();
                        
                        //Create a MAP for keeping the tasks
                        Map<ID, Task> mapTasks = new Map<ID,Task>();
                        
                        //Loop through the Process Steps and fill the map
                        for(Process_Step__c PS : lstProcessSteps)
                            {
                                if(mapPS.containsKey(PS.Process__c))
                                    {
                                        //Fetch the list and add the process step in the list
                                        mapPS.get(PS.Process__c).add(PS);
                                    }
                                else
                                    {
                                        //Create an entry in the map with the key and the list with the Process Step added to it
                                        List<Process_Step__c> lstTemp = new List<Process_Step__c>();
                                        lstTemp.add(PS);
                                        mapPS.put(PS.Process__c,lstTemp);   
                                    }   
                            }
                        
                        //Loop through and put the tasks in the map
                        for(Task tsk : lstTasks)
                            {
                                mapTasks.put(tsk.WhatID,tsk);   
                            }   
                        
                        //Create a list of tasks to be inserted
                        List<Task> lstNewTasks = new List<Task>();
                        List<Process_Step__c> lstProcessStepsToUpdate = new List<Process_Step__c>();
                        
                        //Loop through and process
                        for(ID processID : processIDs)
                            {
                                //Fetch the Process Steps for the Process
                                List<Process_Step__c> lstTempProcessSteps = mapPS.get(processID);
                            
                                if(lstTempProcessSteps != null)
                                {
                                    
                                //Loop through the list and check if there is task available for the process step
                                for(Process_Step__c PS : lstTempProcessSteps)
                                    {
                                        Boolean hasIncompletePredecessor = containsIncompletePredecessor(PS.Process_Step_Junctions_Parent__r); 
                                        if(PS.Status__c.equals(ProcessManager.PROCESS_STEP_STATUS_OPEN) 
                                                && !hasIncompletePredecessor)
                                            {
                                                if(!mapTasks.containsKey(PS.id))
                                                {
                                                    Task objTask = new Task();
                                                    objTask.OwnerId = PS.Assigned_To__c != null?PS.Assigned_To__c:userinfo.getUserId();
                                                    Decimal duration = PS.Duration_In_Days__c;
                                                    Date dueDate = Date.today();
                                                    System.debug(dueDate);
                                                    if (duration != null) {
                                                        dueDate = DateUtils.addBusinessDays(dueDate, Integer.valueOf(duration)).dateGMT();
                                                    }
                                                    System.debug(dueDate);
                                                    objTask.ActivityDate = dueDate;
                                                    objTask.WhatID = PS.id;
                                                    objTask.Subject = 'Process Step: ' + PS.Process__r.Name + ' - ' + PS.name;
                                                    objTask.Description = PS.Step_Details__c;
                                                    objTask.Priority = 'Normal';
                                                    objTask.Process_ID__c = PS.Process__c;
                                                    objTask.Process_Step_ID__c = PS.id;
                                                        
                                                    //add the task to the list
                                                    PS.Task_Created__c = 'Y';
                                                    lstNewTasks.add(objTask);
                                                        
                                                    //Mark the process to have the task created for
                                                    lstProcessStepsToUpdate.add(PS);

                                                 }                                                
                                            }
                                    }
                                }   
                            }
                    
                        Database.DMLOptions dmlo = new Database.DMLOptions();
                        dmlo.EmailHeader.triggerUserEmail = true; 
                        dmlo.optAllOrNone = true;   
                    
                            //Insert the tasks, checking if current user has perms to update
                            if (isTaskCreateable()){

                                database.insert(lstNewTasks,dmlo);
                            }
                            
                            //Update the process steps, checking if current user has perms to update
                            if (isProcessStepUpdeatable()){
                                update lstProcessStepsToUpdate; 
                            }
                        }
                }
            catch(exception ex)
                {
                    throw ex;   
                }           
            }

    public static Boolean containsIncompletePredecessor(List<Process_Step_Junction__c> junctions) {
        System.debug(junctions);
        if (junctions == null) {
            System.debug('junctions was null');
            return false;
        }
        for (Process_Step_Junction__c junction : junctions) {
            System.debug(junction);
            if (junction.PredecessorStep__r.Status__c == 'Open') {
                return true;
            }
        }
        return false;
    }
    
    public static Boolean isTaskCreateable(){
        return (Schema.Sobjecttype.Task.isCreateable() &&  Task.OwnerId.getDescribe().isCreateable() && Task.Subject.getDescribe().isCreateable() &&
                Task.Description.getDescribe().isCreateable() && Task.Priority.getDescribe().isCreateable() && Task.Process_ID__c.getDescribe().isCreateable() &&
                Task.Process_Step_ID__c.getDescribe().isCreateable());
    
    }
    public static Boolean isProcessStepUpdeatable(){
        return (Schema.Sobjecttype.Process_Step__c.isUpdateable() &&  Process_Step__c.Task_Created__c.getDescribe().isUpdateable());
    }
}