src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditProcessTemplateStepController.cls
public with sharing class EditProcessTemplateStepController {

	public String TheType { get; set; }

	private ApexPages.StandardController standardController;
	private String newUrl;
	
	public EditProcessTemplateStepController(ApexPages.StandardController standardController) {
		this.standardController = standardController;
		String templateId = null;
		Process_Template_Step__c step = (Process_Template_Step__c) standardController.getRecord();
		if (step.Process_Template__c != null) {
			templateId = step.Process_Template__c;
		}
		else {
			templateId = ApexPages.currentPage().getParameters().get('templateId');
			step.Process_Template__c = templateId;
		}
		Process_Template__c template = [SELECT Type__c FROM Process_Template__c 
			WHERE Id = :templateId];
		TheType = template.Type__c;
    	setNewUrl();
	}
	
	public PageReference saveAndNew() {
		PageReference pr = null;
		try {
			standardController.save();
			Process_Template_Step__c step = (Process_Template_Step__c) standardController.getRecord();
			if (!Apexpages.hasMessages()) {
		        pr = new PageReference(newUrl += '&templateId=' + step.Process_Template__c);
		        pr.setRedirect(true);
			}
		}
		catch (Exception ex) {
			ApexPages.addMessages(ex);
		}
        return pr;
	}
	
	private void setNewUrl() {
		Schema.DescribeSObjectResult describeResult = standardController.getRecord()
				.getSObjectType().getDescribe();
        newUrl = '/' + describeResult.getKeyPrefix() + '/e?';
    	Map<String, String> params = ApexPages.currentPage().getParameters();
    	String queryString = '';
    	for (String key : params.keyset()) {
    		if (key != 'id' && key != 'templateId') {
    			if (queryString.length() > 0) {
    				queryString += '&';
    			}
    			queryString += key + '=' + params.get(key);
    		}
    	}
    	newUrl += queryString;
	}
}