src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is intended to be a one-time setting to turn on Predecessor functionality for existing XLR8 users receiving package upgrade XLR8 V3.0.  This setting turns Predecessor functionality on for any newly instantiated processes and will not affect already existing processes.</description>
    <fields>
        <fullName>UseTaskHistory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Task History</label>
        <type>Checkbox</type>
    </fields>
    <label>Settings</label>
</CustomObject>

src/objects/Task_History__c.object
<CustomObject>
    <description>XLR8 custom object that records the history of changes made to Task records.</description>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meaningful_Activity__c</fullName>
        <label>Meaningful Activity</label>
        <type>TextArea</type>
    </fields>
    <label>Task History</label>
    <nameField>
        <displayFormat>TH-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Task History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task_Timer_Activity__c.object
<CustomObject>
    <description>XLR8 custom object that records the date and time spent on a given Task.</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Task_ID__c</fullName>
        <label>Task ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Task Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Task Timer Activity</label>
    <nameField>
        <displayFormat>Timer Activity {0}</displayFormat>
        <label>Task Timer Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Timer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskManager_T.cls
@isTest
private class TaskManager_T {
    @isTest
    private static void meaningfulActivityIsCopied() {
        
        String meaningfulActivity = 'Last Estate Plan Review';
        
        Account account1 = new Account(
            Name = 'test'
        );
        insert account1;
        
        Task task1 = new Task(
            WhatId = account1.Id,
            Subject = 'test',
            ActivityDate = Date.today(),
            Meaningful_Activity__c = meaningfulActivity
        );
        
        insert task1;
        
        task1 = [SELECT Meaningful_Activity_Flat__c FROM Task WHERE Id = :task1.Id];
        System.assertEquals(meaningfulActivity, task1.Meaningful_Activity_Flat__c);
    }

    @isTest
    private static void activityDateIsCopied() {
        
        Date theDate = Date.today().addDays(-3);
        
        Account account1 = new Account(
            Name = 'test'
        );
        insert account1;
        
        Task task1 = new Task(
            WhatId = account1.Id,
            Subject = 'test',
            ActivityDate = theDate
        );
        
        insert task1;
        
        task1 = [SELECT Activity_Date__c FROM Task WHERE Id = :task1.Id];
        System.assertEquals(theDate, task1.Activity_Date__c);
        
    }

    @isTest
    private static void completionDateIsSetToToday() {
        
        Date theDate = Date.today().addDays(-3);
        
        Account account1 = new Account(
            Name = 'test'
        );
        insert account1;
        
        Task task1 = new Task(
            WhatId = account1.Id,
            Subject = 'test', 
            ActivityDate = theDate,
            Status = 'Completed'
        );
        
        insert task1;
        
        task1 = [SELECT Completion_Date__c FROM Task WHERE Id = :task1.Id];
        System.assertEquals(Date.today(), task1.Completion_Date__c);
        
    }

    @isTest
    private static void deletingMasterTaskIsRejected() {
        Process_Template__c template = new Process_Template__c(
            Name = 'test1',
            Type__c = 'Entity'
        );
        insert template;
        
        Account account1 = new Account(
            Name = 'test'
        );
        insert account1;

        Process__c process1 = new Process__c(
            Process_Template__c = template.Id,
            Name = 'test12',
            Entity__c = account1.Id
        );
        insert process1;
        
        Process_Step__c processStep = new Process_Step__c(
            Process__c = process1.Id,
            Name = 'test',
            Sequence__c = 1
        );
        insert processStep;
        
        List<Task> tasks = [SELECT Id FROM Task WHERE WhatId = :process1.Id];
        System.assertEquals(1, tasks.size());
        
        Database.DeleteResult result = Database.delete(tasks[0], false);
        System.assert(!result.isSuccess());
        System.assert(result.getErrors()[0].getMessage().contains('Cannot delete a Process Master Task'));
    }
    
    @isTest
    private static void descriptionIsModified() {
        Task task1 = new Task(
            Subject = 'test',
            ActivityDate = Date.today(),
            Description = 'abc'
        );
        insert task1;
        task1 = [Select Description FROM Task WHERE Id = :task1.Id];
        System.debug(task1.Description);
        System.assert(task1.Description.contains('abc'));
    }
    
    @isTest
    private static void createsTaskHistory() {
    	
    	// Create custom setting to use task history
    	Settings__c settings = new Settings__c();
    	settings.Name = 'Default Settings';
    	settings.UseTaskHistory__c = true;
    	insert settings;
    	
    	//Verify settings were inserted
    	system.assertNotEquals(settings.Id, null);
    	
        Task task1 = new Task(
            Subject = 'test',
            ActivityDate = Date.today(),
            Description = 'abc'
        );
        insert task1;

        List<Task_History__c> histories = [SELECT Id FROM Task_History__c];
        System.assertEquals(1, histories.size());
        
        // Turn off the settings to not to use task histories
        settings.useTaskHistory__c = false;
        update settings;
        
        Task task2 = new Task(
            Subject = 'test2',
            ActivityDate = Date.today(),
            Description = 'abc'
        );
        insert task2;
        
        // There should only be one entry in the table
        histories = [SELECT Id FROM Task_History__c];
        System.assertEquals(1, histories.size());
        
         // Turn on the settings to use task histories
        settings.useTaskHistory__c = true;
        update settings;
        
        TaskManager.taskHistoryRecordsCreated = false;
        Task task3 = new Task(
            Subject = 'teste',
            ActivityDate = Date.today(),
            Description = 'abc'
        );
        insert task3;
        
        // There should be two records in the table
        histories = [SELECT Id FROM Task_History__c];
        System.assertEquals(2, histories.size());
    }
    
     @isTest
    private static void testSubjectUpdate() {
        Task task1 = new Task(
            Subject = 'Subject',
            ActivityDate = Date.today(),
            Description = 'abc'
        );
        insert task1;
        system.assertNotEquals(task1.Id, null);
        
        Task_Timer_Activity__c taskTimer = new Task_Timer_Activity__c(
        	Task_ID__c = task1.Id,
        	Task_Subject__c = task1.Subject,
        	Date__c = system.today(),
        	Description__c = 'test'
        );
        
        insert taskTimer;
        system.assertNotEquals(taskTimer.Id, null);
        
        
        Test.startTest();
        taskTimer = [Select Id, Task_Subject__c from Task_Timer_Activity__c where Id =: taskTimer.Id];
        system.assertEquals(taskTimer.Task_Subject__c, 'Subject');
        
        task1.Subject = 'Subject Updated';
        update task1;
        
        
        taskTimer = [Select Id, Task_Subject__c, Name from Task_Timer_Activity__c where Id =: taskTimer.Id];
        system.assertEquals(taskTimer.Task_Subject__c, 'Subject Updated');
        Test.stopTest();
        
    }
}