src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Enter the target completion date for the entire process.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude_From_Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude From Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Account_Team_Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assigned to Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration In Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Step_Details__c</fullName>
        <label>Step Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Case_Role__c</fullName>
        <label>Assign to Case Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Case Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Contact_Role__c</fullName>
        <label>Assign to Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Contact Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Lead_Role__c</fullName>
        <label>Assign to Lead Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Lead Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Opportunity_Role__c</fullName>
        <label>Assign to Opportunity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Opportunity Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Process_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Process Owner is the person who instantiates the process for a record.</inlineHelpText>
        <label>Assign to Process Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_to_Record_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Record Owner is the person who owns the record where the process is being instantiated.</inlineHelpText>
        <label>Assign to Record Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user will be assigned this step every time the template is instantiated on a record.</inlineHelpText>
        <label>Assign to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration in Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Template Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Template_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Template_Step_Junctions_Pred</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step Junction</label>
    <nameField>
        <label>Process Template Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessManager.cls
public without sharing class ProcessManager {

    public static String PROCESS_STATUS_NOT_STARTED = 'Not Started';
    public static String PROCESS_STATUS_COMPLETED = 'Completed';
    public static String PROCESS_STATUS_IN_PROGRESS = 'In Progress';
    public static String PROCESS_STATUS_CANCELLED = 'Cancelled';
    public static String PROCESS_STEP_STATUS_OPEN = 'Open';
    public static String PROCESS_STEP_STATUS_N_A = 'N/A';
    public static String PROCESS_STEP_STATUS_COMPLETED = 'Completed';
    public static String PROCESS_STEP_STATUS_CANCELLED = 'Cancelled';
    
    private List<Process__c> processes;
    private Map<Id,Process__c> processesMap;
    private ProcessUtils processUtils = new ProcessUtils();
    
    public void beforeInsert(List<Process__c> processes, Map<Id,Process__c> processesMap) {
        this.processes = processes;
        this.processesMap = processesMap;
        setDefaultValues();
        validateNew();
        validateDeadline();
    }
    
    public void beforeUpdate(List<Process__c> processes, Map<Id,Process__c> processesMap){
        this.processes = processes;
        this.processesMap = processesMap;
        validateDeadline();
    }
    
    public void afterInsert(Map<Id, Process__c> processes) {
        ProcessTaskManager mgr = new ProcessTaskManager();
        mgr.createMasterTasks(processes);
    }
    
    public void afterUpdate(Map<Id, Process__c> oldProcesses, Map<Id, Process__c> newProcesses) {
        updateMasterTaskStatus(newProcesses);
        validateAssignedToUser(oldProcesses, newProcesses);
        autoCreateTasks(oldProcesses, newProcesses);        
    }
    
    private void updateMasterTaskStatus(Map<Id, Process__c> newProcesses) {
        List<Task> tasks = [SELECT Id, ActivityDate, WhatID, status, OwnerId FROM task 
            WHERE WhatID != NULL AND WhatID IN :newProcesses.keySet()];
        for(Task task1: tasks) {
            for (Process__c process1: newProcesses.values()) {
                if (task1.WhatId == process1.Id) {
                    task1.ActivityDate = process1.Deadline__c;
                    if (process1.Status__c == 'Cancelled'){
                        task1.Status = 'Cancelled';
                    }else if (process1.Status__c == 'Completed'){
                        task1.Status = 'Completed';
                    }else if (process1.Status__c == 'In Progress'){
                        task1.Status = 'In Progress';
                    }else if (process1.Status__c == 'Not Started'){
                        task1.Status = 'Not Started';
                    }               
                }
            }
        }
        if (isTaskUpdateable()){
            Database.update(tasks);   
        }    
    }
    
    private void validateAssignedToUser(Map<Id, Process__c> oldProcesses, 
            Map<Id, Process__c> newProcesses) {
        Set<ID> processIDs = new Set<ID>();
        for (Process__c newProcess : newProcesses.values()) {
            Process__c oldProcess = oldProcesses.get(newProcess.Id);
            if (newProcess.Auto_Create_Tasks__c != oldProcess.Auto_Create_Tasks__c) {
                processIds.add(newProcess.Id);
            }
        }
        boolean result = ValidateAssignedToUserHelper.validate(processIDs,true);
    }
        
    private void autoCreateTasks(Map<Id, Process__c> oldProcesses, 
            Map<Id, Process__c> newProcesses) {
        Set<ID> processIDs = new Set<ID>();
        for (Process__c newProcess : newProcesses.values()) {
            processIds.add(newProcess.Id);
            /*
            Process__c oldProcess = oldProcesses.get(newProcess.Id);
            
            if (newProcess.Auto_Create_Tasks__c != oldProcess.Auto_Create_Tasks__c) {
                processIds.add(newProcess.Id);
            }
            */
        }
        AutoCreateTasks.processSteps(processIDs);       
    }
    
    public void save(Process__c theProcess) {
        if (theProcess.Id == null) {
            theProcess.Exclude_From_Auto_Create_Tasks__c = true;
            if (isProcessCreateable()){
                insert theProcess;
            }else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have privileges to insert Processes.');
                ApexPages.addMessage(myMsg);
            } 
            insertProcessSteps(theProcess.Process_Template__c, 
                new List<Process__c> { theProcess });
            theProcess.Exclude_From_Auto_Create_Tasks__c = false;
            if (isProcessUpdateable()){
                update theProcess;
            }else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have privileges to update Processes.');
                ApexPages.addMessage(myMsg);
            }
        }
        else {
            if (isProcessUpdateable()){
                update theProcess;
            }else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have privileges to update Processes.');
                ApexPages.addMessage(myMsg);
            }
        }
    }
    
    public void stopProcess(Id processId) {
        AutoCreateTasks.Disable = true;
        Process__c tmpProcess = XLR8ProcessUtils.getProcessAndSteps(processId, PROCESS_STEP_STATUS_OPEN);
        
        if (tmpProcess != null && 
            tmpProcess.Status__c != PROCESS_STATUS_COMPLETED && tmpProcess.Status__c != PROCESS_STATUS_CANCELLED &&
            tmpProcess.Process_Steps__r != null && tmpProcess.Process_Steps__r.size() > 0) {
            
            List<Process_Step__c> steps = tmpProcess.Process_Steps__r;
            for (Process_Step__c step : steps) {
                step.Status__c = PROCESS_STEP_STATUS_CANCELLED;
            }
        
            if (isProcessStepUpdateable()){
                update steps;
            }else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have privileges to update Process Steps.');
                ApexPages.addMessage(myMsg);
            }
        }
    }
    
    private void validateNew() {
        Set<Id> templateIds = new Set<Id>();
        for (Process__c theProcess : processes) {
            templateIds.add(theProcess.Process_Template__c);
        }
        Map<Id, Process_Template__c> templateMap = new Map<Id, Process_Template__c>([
            SELECT Type__c FROM Process_Template__c WHERE Id IN :templateIds]);
        for (Process__c theProcess : processes) {
            Process_Template__c template = templateMap.get(theProcess.Process_Template__c);
            if (template == null) {
                continue;
            }
            
            if ((template.Type__c == 'Entity' && (theProcess.Entity__c == null 
                    || theProcess.Lead__c != null || theProcess.Opportunity__c != null
                    || theProcess.Contact__c != null || theProcess.Case__c != null))
                    || (template.Type__c == 'Lead' && (theProcess.Entity__c != null 
                    || theProcess.Lead__c == null || theProcess.Opportunity__c != null
                    || theProcess.Contact__c != null || theProcess.Case__c != null)) 
                    || (template.Type__c == 'Opportunity' && (theProcess.Entity__c != null 
                    || theProcess.Lead__c != null || theProcess.Opportunity__c == null
                    || theProcess.Contact__c != null || theProcess.Case__c != null)) 
                    || (template.Type__c == 'Contact' && (theProcess.Entity__c != null 
                    || theProcess.Lead__c != null || theProcess.Opportunity__c != null
                    || theProcess.Contact__c == null || theProcess.Case__c != null)) 
                    || (template.Type__c == 'Case' && (theProcess.Entity__c != null 
                    || theProcess.Lead__c != null || theProcess.Opportunity__c != null
                    || theProcess.Contact__c != null || theProcess.Case__c == null))
            ) {
                theProcess.addError('Please populate the ' + template.Type__c + ' lookup.');
            }
        }
    }
    
    private void setDefaultValues() {
        Set<Id> processTemplateIds = new Set<Id>();
        for (Process__c theProcess : processes) {
            if (theProcess.Process_Template__c != null) {
                processTemplateIds.add(theProcess.Process_Template__c);
            }
        }
        Map<Id, Process_Template__c> processTemplateMap = new Map<Id, Process_Template__c>([
            SELECT Auto_Create_Tasks_Default__c, Type__c FROM Process_Template__c 
            WHERE Id IN :processTemplateIds
        ]);
        for (Process__c theProcess : processes) {
            Process_Template__c processTemplate = 
                processTemplateMap.get(theProcess.Process_Template__c);
            if (processTemplate == null) {
                theProcess.addError('Process must be associated with a Template.');
                continue;
            }
            if (processTemplate.Type__c == null) {
                theProcess.addError('Process template must have a value selected for Type.');
            }
            theProcess.Auto_Create_Tasks__c = processTemplate.Auto_Create_Tasks_Default__c;
        }
    }
    
    public void insertProcessSteps(Id processTemplateId, List<Process__c> processes) {
        List<Process_Step__c> processSteps = new List<Process_Step__c>();
        List<Process_Template_Step__c> templateSteps = [select id, name , Details__c, Sequence__c, 
            Assign_To_Role__c, Assign_to_User__c,  Assign_To_Process_Owner__c, Assign_To_Record_Owner__c, 
            Duration_In_Days__c,
            Assign_To_Case_Role__c, Assign_To_Contact_Role__c, Assign_To_Lead_Role__c,
            Assign_To_Opportunity_Role__c, Process_Template__r.Type__c,
            (SELECT ParentStep__c, PredecessorStep__c FROM Template_Step_Junctions_Parent__r)
            from Process_Template_Step__c s 
            where Process_Template__c = : processTemplateId];
        
        if (templateSteps != null && templateSteps.size() > 0){
            processSteps.addAll(makeProcessSteps(processes, templateSteps));
        }
        
        
        if (isProcessStepCreateable() && processSteps.size() > 0){
            insert processSteps;    
        }

        List<Map<Id, Id>> stepMapList = new List<Map<Id, Id>>();
        Integer processStepIndex = 0;
        for (Integer i = 0; i < processes.size(); i++) {
            Map<Id, Id> stepMap = new Map<Id, Id>();
            stepMapList.add(stepMap);
            for (Integer j = 0; j < templateSteps.size(); j++) {
                stepMap.put(templateSteps.get(j).Id, processSteps.get(processStepIndex).Id);
                processStepIndex++;
            }
        }
        List<Process_Step_Junction__c> junctions = new List<Process_Step_Junction__c>();
        for (Process_Template_Step__c templateStep : templateSteps) {
            if (templateStep.Template_Step_Junctions_Parent__r == null) {
                continue;
            }
            for (Process_Template_Step_Junction__c junction : 
                    templateStep.Template_Step_Junctions_Parent__r) {
                for (Map<Id, Id> stepMap : stepMapList) {
                    Process_Step_Junction__c stepJunction = new Process_Step_Junction__c();
                    stepJunction.ParentStep__c = stepMap.get(junction.ParentStep__c);
                    stepJunction.PredecessorStep__c = stepMap.get(junction.PredecessorStep__c);
                    junctions.add(stepJunction);
                }
            }
        }
        if (isProcessStepJunctionCreateable()){
            insert junctions;
        }
    }
    
    public void setPredecessorsFromGenericSteps(List<GenericStep> genericSteps) {
        Boolean isDeletable = Schema.sObjectType.Process_Step_Junction__c.isDeletable();
        List<Id> parentStepIds = new List<Id>();
        List<Process_Step_Junction__c> junctions = 
            new List<Process_Step_Junction__c>();
        for (GenericStep step : genericSteps) {
            parentStepIds.add(step.Id);
            if (String.isEmpty(step.PredecessorIds)) {
                continue;
            }
            String[] predecessorIds = step.PredecessorIds.split(';');
            for (String predecessorId : predecessorIds) {
                Process_Step_Junction__c junction = new Process_Step_Junction__c(
                    ParentStep__c = step.Id,
                    PredecessorStep__c = predecessorId
                );
                junctions.add(junction);
            }
        }
        List<Process_Step_Junction__c> junctionsToDelete = [SELECT Id 
            FROM Process_Step_Junction__c
            WHERE ParentStep__c IN :parentStepIds];
        AutoCreateTasks.Disable = true;
        if (isDeletable){
            delete junctionsToDelete;
        }
        AutoCreateTasks.Disable = false;
        if (!junctions.isEmpty()) {
            if (isProcessStepJunctionCreateable()){
                insert junctions;
            }
        }
    }
    

    private List<Process_Step__c> makeProcessSteps(List<Process__c> processes, 
            List<Process_Template_Step__c> templateSteps) {
                System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>> ' + processes);
        List<Process_Step__c> processSteps = new List<Process_Step__c>();
        Map<String,Id> assignedToIds = processUtils.getAssignedToUser(templateSteps, processes);
        String templateType = templateSteps.get(0).Process_Template__r.Type__c;
        Map<Id,sObject> parentsMap = processUtils.getParentOwnerIds(processes, templateType);
        for (Process__c process1 : processes){
            Id parentId = processUtils.getProcessParentOwner(process1, templateType);                   
            Id parentOwnerId = (Id)parentsMap.get(parentId).get('OwnerId');
            for (Process_Template_Step__c templateStep : templateSteps) {
                Process_Step__c processStep = new Process_Step__c();
                processStep.Name = templateStep.Name;
                processStep.Duration_In_Days__c = templateStep.Duration_In_Days__c;
                processStep.Step_Details__c = templateStep.Details__c;
                processStep.Process__c = process1.Id;
                processStep.Sequence__c = templateStep.Sequence__c;
                processStep.Status__c = 'Open';
                if (templateStep.Assign_To_Role__c != null) {
                    processStep.Account_Team_Assigned__c = true;
                }
                if (templateStep.Assign_to_User__c != null) {
                    processStep.Assigned_To__c = templateStep.Assign_to_User__c;
                }else if (templateStep.Assign_To_Process_Owner__c == true){
                    processStep.Assigned_To__c = UserInfo.getUserId();
                }else if (templateStep.Assign_to_Record_Owner__c == true){
                    processStep.Assigned_To__c = parentOwnerId;
                }else{
                    String key = String.valueOf(process1.Id) + String.valueOf(templateStep.Id);
                    String userId = assignedToIds.get(key);
                    if (userId != null && userId.length() > 0 ) {                       
                        processStep.Assigned_To__c = userId;
                    }
                }
                
                processSteps.add(processStep);
            }
        }
        return processSteps;
    }
    
    private static Boolean isProcessStepCreateable(){

        return (Schema.sObjectType.Process_Step__c.isCreateable() &&  Process_Step__c.Name.getDescribe().isCreateable() && 
                Process_Step__c.Duration_In_Days__c.getDescribe().isCreateable() && Process_Step__c.Step_Details__c.getDescribe().isCreateable() &&  
                Process_Step__c.Process__c.getDescribe().isCreateable() && Process_Step__c.Sequence__c.getDescribe().isCreateable() &&  
                Process_Step__c.Status__c.getDescribe().isCreateable() && Process_Step__c.Account_Team_Assigned__c.getDescribe().isCreateable() &&  
                Process_Step__c.Assigned_To__c.getDescribe().isCreateable() );
    }
    
    private void validateDeadline(){
        if (processes != null){
            for (Process__c p : processes){
                 if ((p.Deadline__c != null) && (system.today().daysBetween(p.Deadline__c) < 0) && 
                     (processesMap == null || (processesMap != null && processesMap.get(p.Id).Deadline__c != p.Deadline__c))){
                    p.addError('Due date cannot be in the past');
                 }
            }
        }
    }
    private static Boolean isProcessStepJunctionCreateable(){

        return (Schema.sObjectType.Process_Step_Junction__c.isCreateable() &&  Process_Step_Junction__c.ParentStep__c.getDescribe().isCreateable() && 
                Process_Step_Junction__c.PredecessorStep__c.getDescribe().isCreateable());
    }
    
    public static Boolean isTaskUpdateable(){
        return (Schema.Sobjecttype.Task.isUpdateable() &&  Task.Status.getDescribe().isCreateable());
    }
    
    private static Boolean isProcessCreateable(){
        return (Schema.sObjectType.Process__c.isCreateable() && Process__c.Exclude_From_Auto_Create_Tasks__c.getDescribe().isCreateable()); 
    }
    
    private static Boolean isProcessUpdateable(){
        return (Schema.sObjectType.Process__c.isUpdateable() && Process__c.Exclude_From_Auto_Create_Tasks__c.getDescribe().isUpdateable()); 
    }
    
    private static Boolean isProcessStepUpdateable(){
        return (Schema.sObjectType.Process_Step__c.isUpdateable() ); 
    }
}