src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Client Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Case_Role__c</fullName>
        <label>Assign to Case Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Case Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Contact_Role__c</fullName>
        <label>Assign to Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Contact Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Lead_Role__c</fullName>
        <label>Assign to Lead Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Lead Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Opportunity_Role__c</fullName>
        <label>Assign to Opportunity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Opportunity Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Process_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Process Owner is the person who instantiates the process for a record.</inlineHelpText>
        <label>Assign to Process Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_to_Record_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Record Owner is the person who owns the record where the process is being instantiated.</inlineHelpText>
        <label>Assign to Record Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user will be assigned this step every time the template is instantiated on a record.</inlineHelpText>
        <label>Assign to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration in Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Template Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Template_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Template_Step_Junctions_Pred</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step Junction</label>
    <nameField>
        <label>Process Template Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessTemplateManager.cls
public with sharing 	class ProcessTemplateManager {

	public void beforeInsert(List<Process_Template__c> templates) {
		validateNew(templates);
	}
	
	public void beforeUpdate(List<Process_Template__c> templates, Map<Id, 
			Process_Template__c> oldMap) {
		validateChange(templates, oldMap);
	}
	
	private void validateNew(List<Process_Template__c> templates) {
		for (Process_Template__c template : templates) {
			if (template.Type__c == null) {
				template.addError('Please select the Type.');
			}
		}
	}
	
	private void validateChange(List<Process_Template__c> templates, 
			Map<Id, Process_Template__c> oldTemplateMap) {
		for (Process_Template__c template : templates) {
			Process_Template__c oldTemplate = oldTemplateMap.get(template.Id);
			if (template.Type__c != oldTemplate.Type__c && oldTemplate.Type__c != null) {
				template.addError('The Type cannot be changed.');
				return;
			}
		}
		List<Process_Template_Step__c> steps = [SELECT Assign_To_User__c, Assign_To_Role__c, 
			Assign_To_Lead_Role__c, Assign_To_Contact_Role__c, Assign_To_Opportunity_Role__c, 
			Assign_To_Case_Role__c, Process_Template__c, Assign_To_Process_Owner__c, Assign_To_Record_Owner__c
			FROM Process_Template_Step__c 
			WHERE Process_Template__c IN :templates];
		ProcessTemplateStepManager stepManager = new ProcessTemplateStepManager();
		Map<Id, Process_Template__c> templateMap = new Map<Id, Process_Template__c>(templates);
		for (Process_Template_Step__c step : steps) {
			Process_Template__c template = templateMap.get(step.Process_Template__c);
			if (!stepManager.stepIsAssignedToUserOrRole(template.Type__c, 
			template.Auto_Create_Tasks_Default__c, step)) {
				template.addError('If Auto Create Tasks is turned on, all steps must be assigned to'
				+ ' a user or role.');
			}
		}
	}
	
	
	public Id deepClone(String processTemplateId) {
		Process_Template__c template = [select Id, OwnerId, IsDeleted, Name, CreatedDate, 
			CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, Category__c, 
			Description__c, Auto_Create_Tasks_Default__c, Type__c,
			(select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, 
			LastModifiedById, SystemModstamp, LastActivityDate, Assign_To_Role__c, 
			Assign_to_User__c, Details__c, Process_Template__c, Assign_To_Case_Role__c, 
			Assign_To_Contact_Role__c, Assign_To_Lead_Role__c, Assign_To_Opportunity_Role__c, 
			Assign_To_Process_Owner__c, Assign_to_Record_Owner__c,
			Sequence__c, Duration_In_Days__c
			from Process_Template_Steps__r)
			from Process_Template__c WHERE Id = :processTemplateId];
		Process_Template__c clonedTemplate = template.clone(false, true, false, false);
		String name = 'Copy of ' + clonedTemplate.Name;
		Integer nameCounter = 2;
		while (templateNameExists(name)) {
			name = 'Copy of ' + clonedTemplate.Name + ' ' + nameCounter;
			nameCounter++;
		}
		clonedTemplate.Name = name;
		clonedTemplate.OwnerId  = UserInfo.getUserId();
		if (isProcessTemplateCreateable()){
			insert clonedTemplate;
		}
		
		List<Process_Template_Step__c> clonedTemplateSteps = new List<Process_Template_Step__c>(); 
		for (Process_Template_Step__c step : template.Process_Template_Steps__r) {
			Process_Template_Step__c clonedStep = step.clone(false, true, false, false);
			clonedStep.Process_Template__c = clonedTemplate.Id;
			clonedStep.OwnerId = UserInfo.getUserId();
			clonedTemplateSteps.add(clonedStep);
		}
		if (isProcessTemplateStepCreateable()){
			insert clonedTemplateSteps;
		}
		setTemplateStepPredecessors(template.Process_Template_Steps__r, clonedTemplateSteps);
		return clonedTemplate.Id;
	}
	
	public void setPredecessorsFromGenericSteps(List<GenericStep> genericSteps) {
		Boolean isDeleteable = Schema.sObjectType.Process_Template_Step_Junction__c.isDeletable();
		List<Id> parentStepIds = new List<Id>();
		List<Process_Template_Step_Junction__c> junctions = 
			new List<Process_Template_Step_Junction__c>();
		for (GenericStep step : genericSteps) {
			System.debug(step);
			parentStepIds.add(step.Id);
			if (String.isEmpty(step.PredecessorIds)) {
				continue;
			}
			String[] predecessorIds = step.PredecessorIds.split(';');
			for (String predecessorId : predecessorIds) {
				Process_Template_Step_Junction__c junction = new Process_Template_Step_Junction__c(
					ParentStep__c = step.Id,
					PredecessorStep__c = predecessorId
				);
				junctions.add(junction);
			}
		}
		List<Process_Template_Step_Junction__c> junctionsToDelete = [SELECT Id 
			FROM Process_Template_Step_Junction__c
			WHERE ParentStep__c IN :parentStepIds];
		if (isDeleteable){
			delete junctionsToDelete;
		}
		
		if (!junctions.isEmpty()) {
			if (isProcessTemplateStepJunctionCreateable()){
				insert junctions;
			}
			
		}
	}
	
	private void setTemplateStepPredecessors(List<Process_Template_Step__c> oldSteps, 
			List<Process_Template_Step__c> newSteps) {
		Boolean isCreateable = Schema.sObjectType.Process_Template_Step_Junction__c.isCreateable();
		Map<Id, Id> newStepIdByOldStepId = new Map<Id, Id>();
		for (Integer i = 0; i < newSteps.size(); i++) {
			Process_Template_Step__c newStep = newSteps[i];
			Process_Template_Step__c oldStep = oldSteps[i];
			newStepIdByOldStepId.put(oldStep.Id, newStep.Id);
		}
		List<Process_Template_Step_Junction__c> junctions = [SELECT ParentStep__c, 
			PredecessorStep__c FROM Process_Template_Step_Junction__c 
			WHERE ParentStep__c IN :oldSteps];
		List<Process_Template_Step_Junction__c> newJunctions = 
			new List<Process_Template_Step_Junction__c>();
		for (Process_Template_Step_Junction__c junction : junctions) {
			newJunctions.add(new Process_Template_Step_Junction__c(
				ParentStep__c = newStepIdByOldStepId.get(junction.ParentStep__c),
				PredecessorStep__c = newStepIdByOldStepId.get(junction.PredecessorStep__c)
			));
		}
		if (isProcessTemplateStepJunctionCreateable()){
			insert newJunctions;
		}
	}
	
	private Boolean templateNameExists(String name) {
		return ![SELECT Id FROM Process_Template__c WHERE Name = :name].isEmpty();
	}
	
	public static Boolean isProcessTemplateCreateable(){
		return (Schema.sObjectType.Process_Template__c.isCreateable() && Process_Template__c.Category__c.getDescribe().isCreateable() &&
				Process_Template__c.Description__c.getDescribe().isCreateable() && Process_Template__c.Auto_Create_Tasks_Default__c.getDescribe().isCreateable() &&
				Process_Template__c.Type__c.getDescribe().isCreateable() );
	}
	
	public static Boolean isProcessTemplateStepCreateable(){
		return (Schema.sObjectType.Process_Template_Step__c.isCreateable() && Process_Template_Step__c.Process_Template__c.getDescribe().isCreateable());
	}
	
	public static Boolean isProcessTemplateStepJunctionCreateable(){
		return (Schema.sObjectType.Process_Template_Step_Junction__c.isCreateable() && Process_Template_Step_Junction__c.ParentStep__c.getDescribe().isCreateable() &&
		Process_Template_Step_Junction__c.PredecessorStep__c.getDescribe().isCreateable());
	}
}