src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ValidateAssignedToUserHelper.cls
//Helper class for Validate Assinged To User Trigger
//Changed By        Date        Comments
//Sankalp           04202011    Created the class
public  with sharing class ValidateAssignedToUserHelper
    {
    	//Validate assigned to users
    	public static boolean validate(Set<ID> processIDs, boolean updateProcesses)
    		{
    			// Create List for Process Steps
    			List <Process_Step__c> listProcessStep;
    
    			
    			 // Get the Process Steps    
			    listProcessStep = new List <Process_Step__c>(
			        [SELECT Assigned_To__c, Process__c
			            FROM Process_Step__c
			            WHERE Process__c
			            IN: processIDs AND Process__r.Auto_Create_Tasks__c = true AND Status__c != 'Completed' limit : Limits.getLimitQueryRows()
			        ]
			    );
			    
			    if(listProcessStep.size() > 0)
			    	{
				    // Create Map
				    Map <ID, list<Process_Step__c>> mapProcessStep = new Map <ID, list<Process_Step__c>>();
				    
				    // Loop through and add to Map
				    for(Process_Step__c processStep: listProcessStep)
				        {
				            if(mapProcessStep.containsKey(processStep.Process__c))
				                {
				                    // Add process object in list
				                    List<Process_Step__c> listTemp = mapProcessStep.get(processStep.Process__c);
				                    listTemp.add(processStep);
				                }
				                
				            else
				                {
				                     // Add key with empty list to Map
				                     List<Process_Step__c> listTemp = new List<Process_Step__c>();
				                     listTemp.add(processStep);
				                     mapProcessStep.put(processStep.Process__c,listTemp);
				                }
				         }
				     
				     //Set of proccess IDs to update
				     SET<ID> setProcesses = new SET<ID>();
				     
				     //Check for assigned users
				     for(ID p : processIDs)
				            {              
				            if(mapProcessStep.containsKey(p))
				                {                
					                //Get list from Map                     
					                List<Process_Step__c> listTempProcessStep = mapProcessStep.get(p);
					                for(Process_Step__c processStepValidate : listTempProcessStep)
					                    {
					                        if(processStepValidate.Assigned_To__c == null)
					                            {	
					                                setProcesses.add(p);
					                                break;
					                            } 
					                    }                
				                }
				            }
				   
				   	if(setProcesses.size() > 0)
				   		{				    
					    //Fetch all the processes to be updated
					    List<Process__c> lstUpdateProcesses = new List<Process__c>([Select Auto_Create_Tasks__c from Process__c where ID in : setProcesses LIMIT : Limits.getLimitQueryRows()]);
					                  
					    for(Process__c objPro : lstUpdateProcesses)
					    	{
					    		objPro.Auto_Create_Tasks__c = false;
					    	}              
					            
					    if(updateProcesses)
					    	{              
					    		if (isProcessUpdateable()){
									update lstUpdateProcesses;
								}
					    	}
					    
					    	return false;
					    	
				   		}
				   	else
						{
							return true;						   	
						}		
			    }
			 else
			 	{
			 		return true;
			 	}   
    		}
    		
    		private static Boolean isProcessUpdateable(){
		    	return (Schema.sObjectType.Process__c.isUpdateable() && Process__c.Auto_Create_Tasks__c.getDescribe().isUpdateable());
		    }
    }