src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InitPredecessors.cls
public with sharing class InitPredecessors {

	public void initPredecessors(List<Process__c> processes) {
		List<Process__c> processesAndSteps = [SELECT Id, 
			(SELECT Sequence__c FROM Process_Steps__r ORDER BY Sequence__c) 
			FROM Process__c WHERE Id IN :processes];
		
		List<Process_Step_Junction__c> junctions = new List<Process_Step_Junction__c>();
		for (Process__c process1 : processesAndSteps) {
			for (Integer i = 0; i < process1.Process_Steps__r.size(); i++) {
				Process_Step__c step = process1.Process_Steps__r.get(i);
				if (i > 0) {
					junctions.add(new Process_Step_Junction__c(
						ParentStep__c = process1.Process_Steps__r.get(i).Id,
						PredecessorStep__c = process1.Process_Steps__r.get(i - 1).Id
					));
				}
			} 
		}
		if (isProcessStepJnctionCreateable()){
			insert junctions;
		}
		
	}
	
	private Boolean isProcessStepJnctionCreateable(){
		return  Schema.sObjectType.Process_Step_Junction__c.isCreateable();
	}
}