src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessTemplateBatchable.cls
global class ProcessTemplateBatchable implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator([SELECT Id FROM Process_Template__c WHERE Type__c = null]);
	}
	
	global void execute(Database.BatchableContext context, List<Process_Template__c> templates) {
		for (Process_Template__c template : templates) {
			template.Type__c = 'Entity';
		}
		if (isProcessTemplateUpdateable()){
			update templates;
		}
	}
	
	global void finish(Database.BatchableContext context) {
		
	}
	
	private Boolean isProcessTemplateUpdateable(){
    	return (Schema.sObjectType.Process_Template__c.isUpdateable() && Process_Template__c.Type__c.getDescribe().isUpdateable());
    }
}