src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Create Tasks Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Case_Role__c</fullName>
        <label>Assign to Case Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Case Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Contact_Role__c</fullName>
        <label>Assign to Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Contact Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Lead_Role__c</fullName>
        <label>Assign to Lead Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Lead Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Opportunity_Role__c</fullName>
        <label>Assign to Opportunity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Opportunity Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Process_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Process Owner is the person who instantiates the process for a record.</inlineHelpText>
        <label>Assign to Process Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_to_Record_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The Record Owner is the person who owns the record where the process is being instantiated.</inlineHelpText>
        <label>Assign to Record Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assign_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user will be assigned this step every time the template is instantiated on a record.</inlineHelpText>
        <label>Assign to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor_Steps__c</fullName>
        <label>Predecessor Steps</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Template Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Template_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Template_Step_Junctions_Pred</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step Junction</label>
    <nameField>
        <label>Process Template Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessTemplateStepManager.cls
public with sharing class ProcessTemplateStepManager {

	private static final String ERROR_MESSAGE = 'Step must be assigned to a user, role, process owner or record owner.';
	
	public void beforeInsert(List<Process_Template_Step__c> steps) {
		validateAssignedToUserOrRole(steps);
	}
	
	public void beforeUpdate(List<Process_Template_Step__c> steps) {
		validateAssignedToUserOrRole(steps);
	}
	
	public void afterDelete(List<Process_Template_Step__c> steps) {
		deleteJunctionObjectsForSteps(steps);
	}
	
	public void validateAssignedToUserOrRole(List<Process_Template_Step__c> steps) {
		Set<Id> templateIds = new Set<Id>();
		for (Process_Template_Step__c step : steps) {
			templateIds.add(step.Process_Template__c);
		}
		Map<Id, Process_Template__c> templates = new Map<Id, Process_Template__c>([SELECT Type__c,
			Auto_Create_Tasks_Default__c
			FROM Process_Template__c WHERE Id IN :templateIds]);
		for (Process_Template_Step__c step : steps) {
			Boolean isStepAssigned = isStepAssigned(step);
			Boolean isRoleAssigned = false;
			
			if (isStepAssigned){
				Process_Template__c template = templates.get(step.Process_Template__c);
				isRoleAssigned = isRoleAssigned(step, template.Type__c);
			}
			
			if (!isStepAssigned || ! isRoleAssigned){
				step.addError(ERROR_MESSAGE);
			}
		}
	}
	
	public Boolean isStepAssigned(Process_Template_Step__c step){
		Integer assigneesCount = 0;
		if (step != null){
			if (step.Assign_to_User__c != null){
				assigneesCount++;
			}
			if (step.Assign_To_Role__c != null ||
				step.Assign_To_Case_Role__c != null ||
				step.Assign_To_Lead_Role__c != null ||
				step.Assign_To_Contact_Role__c != null ||
				step.Assign_To_Opportunity_Role__c != null){
				assigneesCount++;
			}
			
			if (step.Assign_To_Process_Owner__c){
				assigneesCount++;
			}
			if (step.Assign_to_Record_Owner__c){
				assigneesCount++;
			}
			
		}
		
		return assigneesCount == 1;
	}
	
	public Boolean isRoleAssigned(Process_Template_Step__c step, String templateType){
		Boolean result = true;
		
		if (step == null ){
			result = false;
		}
		
		if (result){
			if (step.Assign_To_Role__c != null ||
				step.Assign_To_Case_Role__c != null ||
				step.Assign_To_Lead_Role__c != null ||
				step.Assign_To_Contact_Role__c != null ||
				step.Assign_To_Opportunity_Role__c != null){
					
				if ((templateType == 'Entity' && step.Assign_To_Role__c == null) ||
					 (templateType == 'Case' && step.Assign_To_Case_Role__c == null) ||
					 (templateType == 'Lead' && step.Assign_To_Lead_Role__c == null) ||
					 (templateType == 'Contact' && step.Assign_To_Contact_Role__c == null) ||
					 (templateType == 'Opportunity' && step.Assign_To_Opportunity_Role__c == null)) {
					 
					 result = false;
				}	
			}	
		}
		
		return result;
	}
	public Boolean stepIsAssignedToUserOrRole(String templateType, Boolean autoCreateTasks, 
			Process_Template_Step__c step) { 			
		Boolean result = true;	
		Boolean isRoleAssigned = false;	
		Boolean isStepAssigned = false;
		
		if (autoCreateTasks){
			isStepAssigned = isStepAssigned(step);
			if (isStepAssigned){
				isRoleAssigned = isRoleAssigned(step, templateType);
			}
			
			if (!isStepAssigned || ! isRoleAssigned){
				result = false;
			}
		}
		return result;
	}

	public void populateSequences(List<Process_Template_Step__c> steps) {
		Set<Id> processTemplateIds = new Set<Id>();
		for (Process_Template_Step__c step : steps) {
			processTemplateIds.add(step.Process_Template__c);
		}
		AggregateResult[] results = [SELECT Process_Template__c TemplateId, MAX(Sequence__c) MaxSeq 
			FROM Process_Template_Step__c 
			WHERE Process_Template__c IN :processTemplateIds GROUP BY Process_Template__c ];
		Map<Id, Double> maxSequenceByTemplate = new Map<Id, Double>();
		for (AggregateResult result : results) {
			maxSequenceByTemplate.put((Id) result.get('TemplateId'), 
				(Double) result.get('MaxSeq'));
		}
		for (Process_Template_Step__c step : steps) {
			if (step.Sequence__c == null) {
				Double maxSequence = maxSequenceByTemplate.get(step.Process_Template__c);
				if (maxSequence == null) {
					maxSequence = 0;
				}
				step.Sequence__c = maxSequence + 1;
			}
		}
	}
	
	public void populatePredecessorSequences(List<Id> newStepIds) {
		List<Process_Template_Step__c> newSteps = [SELECT Process_Template__c, Sequence__c,
			(SELECT ParentStep__c, PredecessorStep__c, PredecessorStep__r.Sequence__c 
			FROM Template_Step_Junctions_Parent__r ORDER BY PredecessorStep__r.Sequence__c)
			FROM Process_Template_Step__c WHERE Id IN :newStepIds];
		Map<Id, Process_Template_Step__c> mapNewSteps = new Map<Id, Process_Template_Step__c>(
			newSteps);
		Set<Id> templateIds = new Set<Id>();
		for (Process_Template_Step__c step : newSteps) {
			templateIds.add(step.Process_Template__c);
		}
		List<Process_Template_Step__c> steps = [SELECT Process_Template__c, Sequence__c,
			(SELECT ParentStep__c, PredecessorStep__c, PredecessorStep__r.Sequence__c 
			FROM Template_Step_Junctions_Parent__r ORDER BY PredecessorStep__r.Sequence__c)
			FROM Process_Template_Step__c WHERE Process_Template__c IN :templateIds];
		Map<Id, Map<Id, Process_Template_Step__c>> templateMap = 
				new Map<Id, Map<Id, Process_Template_Step__c>>(); 
		for (Process_Template_Step__c step : newSteps) {
			if (step.Template_Step_Junctions_Parent__r == null) {
				step.Predecessor_Steps__c = null;
				continue;
			}
			List<String> sequences = new List<String>();
			for (Process_Template_Step_Junction__c junction : step.Template_Step_Junctions_Parent__r) {
				sequences.add(String.valueOf(junction.PredecessorStep__r.Sequence__c));
			}			
			step.Predecessor_Steps__c = String.join(sequences, ', ');
		}
		if (isProcessTemplateStepUpdateable()){
			update newSteps;
		}
	}
	
	public void deleteJunctionObjectsForSteps(List<Process_Template_Step__c> steps) {
		System.debug(steps);
		List<Process_Template_Step_Junction__c> junctions = [SELECT Id 
			FROM Process_Template_Step_Junction__c 
			WHERE PredecessorStep__c IN :steps];
		Boolean isDeleteable = Schema.sObjectType.Process_Template_Step_Junction__c.isDeletable();
		if (isDeleteable){
			delete junctions;
		}
	}
	
	private Boolean isProcessTemplateStepUpdateable(){
    	return (Schema.sObjectType.Process_Template_Step__c.isUpdateable() && Process_Template_Step__c.Predecessor_Steps__c.getDescribe().isUpdateable());
    }
}