src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Case_Role__c</fullName>
        <label>Assign to Case Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Case Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number of days the task is expected to require for completion. Enter as a whole number, otherwise it will be rounded. Task due date will be calculated based on this value.  A duration of 0 (zero) will result in a task due date equal to the current date.</inlineHelpText>
        <label>Duration in Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditProcessTemplateStepController_T.cls
/**
 * This class contains unit tests for validating the behavior of EditProcessTemplateStepController
 */
@isTest
private class EditProcessTemplateStepController_T {

    private static void initData(){
    //Create one template
    Process_Template__c template = TestUtility.createProcessTemplate('Sample Case Template', 'Case', 'Marketing','', false);
    insert template;
    System.assertNotEquals(template.Id, null);
    
    //Insert one step
    Process_Template_Step__c templateStep = TestUtility.createProcessTemplateStep('Create payload', 'Create payload', 0, template.Id, null, 'Case Role');
    insert templateStep;
    System.assertNotEquals(templateStep.Id, null);
    
    
  }
  
    static testMethod void testSave() {
        //Initialize data
        initData();
        
        //Query the template inserted
        Process_Template_Step__c templateStep = [Select Id, Name, Details__c, Duration_In_Days__c, Assign_To_Case_Role__c, Process_Template__c from Process_Template_Step__c limit 1];
        
        //Set the page for the test
        PageReference pageRef = Page.EditProcessTemplateStep;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('templateId', templateStep.Process_Template__c);
      ApexPages.currentPage().getParameters().put('CF00NG000000AkRdl', 'Sample+Case+Template');
      ApexPages.currentPage().getParameters().put('CF00NG000000AkRdl_lkid', templateStep.Process_Template__c);
      
      //Instantiate the page controller
        ApexPages.StandardController standardController = new ApexPages.StandardController(templateStep);            
      EditProcessTemplateStepController controller = new EditProcessTemplateStepController(standardController);
      
      //Update the attributes
      templateStep.Name = 'Updated name';
      templateStep.Duration_In_Days__c = 1;
      
      standardController.save();
      templateStep = [Select Id, Name, Details__c, Duration_In_Days__c, Assign_To_Case_Role__c, Process_Template__c from Process_Template_Step__c limit 1];
      System.assertEquals(templateStep.Name, 'Updated name');
      System.assertEquals(templateStep.Duration_In_Days__c, 1);
        
    }
    
    static testMethod void testCancel() {
        //Initialize data
        initData();
        
        //Query the template inserted
        Process_Template_Step__c templateStep = [Select Id, Name, Details__c, Duration_In_Days__c, Assign_To_Case_Role__c, Process_Template__c from Process_Template_Step__c limit 1];
        
        //Set the page for the test
        PageReference pageRef = Page.EditProcessTemplateStep;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('templateId', templateStep.Process_Template__c);
      ApexPages.currentPage().getParameters().put('CF00NG000000AkRdl', 'Sample+Case+Template');
      ApexPages.currentPage().getParameters().put('CF00NG000000AkRdl_lkid', templateStep.Process_Template__c);
      
      //Instantiate the page controller
        ApexPages.StandardController standardController = new ApexPages.StandardController(templateStep);            
      EditProcessTemplateStepController controller = new EditProcessTemplateStepController(standardController);
      
      //Update the attributes
      templateStep.Name = 'Updated name';
      templateStep.Duration_In_Days__c = 1;
      
      standardController.cancel();
      templateStep = [Select Id, Name, Details__c, Duration_In_Days__c, Assign_To_Case_Role__c, Process_Template__c from Process_Template_Step__c limit 1];
      System.assertEquals(templateStep.Name, 'Create payload');
      System.assertEquals(templateStep.Duration_In_Days__c, 0);
        
    }
    
    static testMethod void testSaveAndNew() {
        //Initialize data
        initData();
        
        //Query the template inserted
        Process_Template_Step__c templateStep = [Select Id, Name, Details__c, Duration_In_Days__c, Assign_To_Case_Role__c, Process_Template__c from Process_Template_Step__c limit 1];
        
        //Set the page for the test
        PageReference pageRef = Page.EditProcessTemplateStep;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('templateId', templateStep.Process_Template__c);
      ApexPages.currentPage().getParameters().put('CF00NG000000AkRdl', 'Sample+Case+Template');
      ApexPages.currentPage().getParameters().put('CF00NG000000AkRdl_lkid', templateStep.Process_Template__c);
      
      //Instantiate the page controller
        ApexPages.StandardController standardController = new ApexPages.StandardController(templateStep);            
      EditProcessTemplateStepController controller = new EditProcessTemplateStepController(standardController);
      
      //Update the attributes
      templateStep.Name = 'Updated name';
      templateStep.Duration_In_Days__c = 1;
      
      PageReference pr = controller.saveAndNew();
      templateStep = [Select Id, Name, Details__c, Duration_In_Days__c, Assign_To_Case_Role__c, Process_Template__c from Process_Template_Step__c limit 1];
      System.assertEquals(templateStep.Name, 'Updated name');
      System.assertEquals(templateStep.Duration_In_Days__c, 1);
        
        System.assertNotEquals(pr, null);
        System.assertNotEquals(pr.getUrl(),null);
        System.assert(pr.getUrl().contains('templateId'));
    }
}