src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Step__c</referenceTo>
        <relationshipLabel>Process Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Step_Junctions_Predecessors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Step Junction</label>
    <nameField>
        <label>Process Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessStepSequenceController.cls
public with sharing class ProcessStepSequenceController {

	public List<GenericStep> Steps { get; set; }
	private ApexPages.StandardController controller;
	private Process__c theProcess;

	public ProcessStepSequenceController(ApexPages.StandardController cont) {
		this.controller = cont;
		this.theProcess = (Process__c) cont.getRecord(); 
		Steps = new List<GenericStep>();
		
		List<Process_Step__c> processSteps = [Select Name, Sequence__c,
			(SELECT ParentStep__c, PredecessorStep__c FROM Process_Step_Junctions_Parent__r)
			FROM Process_Step__c WHERE Process__c = :theProcess.Id ORDER BY Sequence__c ];
		
		for (Process_Step__c step : processSteps) {
			GenericStep Step1 = new GenericStep(step.Id, step.Name, String.valueOf(step.Sequence__c), 
				null);
			if (step.Process_Step_Junctions_Parent__r != null) {
				String[] predecessorIds = new List<String>();
				for (Process_Step_Junction__c junction : step.Process_Step_Junctions_Parent__r) {
					predecessorIds.add(junction.PredecessorStep__c);
				}
				Step1.PredecessorIds = String.join(predecessorIds, ';');
				System.debug(Step1.PredecessorIds);
			}
			Steps.add(Step1);
		}
	}
	
	public PageReference save() {
		List<Process_Step__c> processSteps = new List<Process_Step__c>();
		for (GenericStep step1 : Steps) {	
			Process_Step__c processStep = new Process_Step__c(
				Id = step1.Id,
				Sequence__c = Integer.valueOf(step1.Sequence)
			);
			processSteps.add(processStep);
		}
		try { 
			if (isProcessStepUpdateable()){
				update processSteps;
			}else{
				
		    	ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'You do not have perms to update process steps.');
				ApexPages.addMessage(myMsg); 
			}
			ProcessManager mgr = new ProcessManager();
			mgr.setPredecessorsFromGenericSteps(Steps); 
			return controller.view();
		}
		catch (DMLException e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
		}
		return null;
	}
	
	private static Boolean isProcessStepUpdateable(){
    	return (Schema.sObjectType.Process_Step__c.isUpdateable() && Process_Step__c.Sequence__c.getDescribe().isUpdateable());
    }
}