src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(OR(Total_Steps__c == 0, AND(Total_Steps__c &gt; 0, Cancelled_Steps__c == 0,  Completed_Steps__c == 0, NA_Steps__c == 0 )), &apos;Not Started&apos;,
IF(Cancelled_Steps__c &gt; 0, &apos;Cancelled&apos;, 
IF( Total_Steps__c == (Completed_Steps__c + NA_Steps__c  ), &apos;Completed&apos;, &apos;In Progress&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessActionsController_T.cls
/**
 * This class contains unit tests for validating the behavior of the ProcessActionsController
 */  

@isTest
private class ProcessActionsController_T {
  
  private static void initData(){
    //Create one case
    Case tcase = TestUtility.createCase('Open', 'Phone');
    insert tcase;
    
    System.assertNotEquals(tcase.Id, null); 
  
    //Create one template
    Process_Template__c template = TestUtility.createProcessTemplate('Sample Case Template', 'Case', 'Marketing','', false);
    insert template;
    System.assertNotEquals(template.Id, null);
    
    //Insert a process
    Process__c p = TestUtility.createProcess('Process', template.Id, tcase.Id);
    
    insert p;
    System.assertNotEquals(p.Id, null);
    
  }
  
    static testMethod void testNoAction() {
        //Initialize data for the test
        initData();
        
        //Query the process
        Process__c p = [Select Id from Process__c limit 1];
        
        //Set the page for the test
        PageReference pageRef = Page.ProcessActions;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('id', p.Id);
      ApexPages.currentPage().getParameters().put('action','');
      
      ProcessActionsController controller = new ProcessActionsController();
      
      PageReference pr = controller.doAction();
      
      String url = System.Url.getSalesforceBaseUrl() + '/' + p.Id;
      String returnUrl = System.Url.getSalesforceBaseUrl() + pr.getUrl(); 
      System.assertEquals(url,returnUrl);   
    }
    
    static testMethod void testCloseProcessWithoutSteps() {
        //Initialize data for the test
        initData();
        
        //Query the process
        Process__c p = [Select Id from Process__c limit 1];
        
        //Set the page for the test
        PageReference pageRef = Page.ProcessActions;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('id', p.Id);
      ApexPages.currentPage().getParameters().put('action','stop');
      
      ProcessActionsController controller = new ProcessActionsController();
      
      PageReference pr = controller.doAction();
      
    }
    
    static testMethod void testCloseProcessWithSteps() {
        //Initialize data for the test
        initData();
        
        //Query the process
        Process__c p = [Select Id from Process__c limit 1];
        
        //Insert steps
        List<Process_Step__c> steps = new List<Process_Step__c>();
    steps.add(TestUtility.createProcessStep('Step 1', p.Id, 'Open', 1));
    steps.add(TestUtility.createProcessStep('Step 2', p.Id, 'Open', 2));
    
    insert steps;
    
    //Verify steps were inserted
    System.assertNotEquals(steps.get(0).Id, null);
    System.assertNotEquals(steps.get(1).Id, null);
    
        //Set the page for the test
        PageReference pageRef = Page.ProcessActions;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('id', p.Id);
      ApexPages.currentPage().getParameters().put('action','stop');
      
      ProcessActionsController controller = new ProcessActionsController();
      PageReference pr = controller.doAction();
      
      //Verify steps were updated
      steps = [Select Id, Status__c from Process_Step__c];
      System.assertEquals(steps.size(), 2);
      System.assertEquals(steps.get(0).Status__c, 'Cancelled');
      System.assertEquals(steps.get(1).Status__c, 'Cancelled');
      
      
    }
    
    static testMethod void testCloseCompletedProcess() {
        //Initialize data for the test
        initData();
        
        //Query the process
        Process__c p = [Select Id from Process__c limit 1];
        
        //Insert steps
        List<Process_Step__c> steps = new List<Process_Step__c>();
    steps.add(TestUtility.createProcessStep('Step 1', p.Id, 'Completed', 1));
    steps.add(TestUtility.createProcessStep('Step 2', p.Id, 'Completed', 2));
    
    insert steps;
    
    //Verify steps were inserted
    System.assertNotEquals(steps.get(0).Id, null);
    System.assertNotEquals(steps.get(1).Id, null);
    
        //Set the page for the test
        PageReference pageRef = Page.ProcessActions;
        Test.setCurrentPage(pageRef);
      
      //Set parameters
      ApexPages.currentPage().getParameters().put('id', p.Id);
      ApexPages.currentPage().getParameters().put('action','stop');
      
      ProcessActionsController controller = new ProcessActionsController();
      
      PageReference pr = controller.doAction();
      
      
    }
}