src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Enter the target completion date for the entire process.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestHandleProcessCreation.cls
@isTest
private class TestHandleProcessCreation 
{
    static testMethod void handleProcessCreation() 
    {
        Process_Template__c processTemplate = new Process_Template__c();
        processTemplate.Name = 'TEST PKS TEMPLATE-1';
        processTemplate.Description__c = 'TEST PKS TEMPLATE-1';
        processTemplate.Type__c = 'Entity';
        
        Test.startTest();
        Database.insert(processTemplate);
        System.assertNotEquals(processTemplate.Id, null);
        
        List<Process_Template__c> templates = Database.query('SELECT Id, Name FROM Process_Template__c WHERE name =\'TEST PKS TEMPLATE-1\'');  //
        for (Process_Template__c tmpObj: templates)
        {
            processTemplate = tmpObj;
        }
        
        Process_Template_Step__c templateStep = new Process_Template_Step__c();
        templateStep.Name = 'TEST PKS TEMPLATE STEP-1';
        templateStep.Sequence__c = 1;
        templateStep.Process_Template__c = processTemplate.Id;
        templateStep.Assign_To_Role__c = 'Primary Advisor';
        Database.insert(templateStep);
        System.assertNotEquals(templateStep.Id, null);
        
        Account tmpAccount = new Account();
        tmpAccount.Name = 'PKS TEST ACCOUNT';
        Database.insert(tmpAccount);
        List<Account> accounts = Database.query('SELECT Id, Name FROM account where name=\'PKS TEST ACCOUNT\'');
        for (Account tmpObj: accounts)
        {
            tmpAccount = tmpObj;
        }
        
        List<Process__c> processes = new List<Process__c>{};
        for (Integer i=0; i<4; i++)
        {
            Process__c tmpProcess = new Process__c();
            tmpProcess.Name = 'TEST Process: ' + (i);
            if (i == 2)
            {
                tmpProcess.Name = 'TEST Process: ' + (4 - i);
            }
            
            tmpProcess.Process_Template__c = processTemplate.Id;
            tmpProcess.Entity__c = tmpAccount.Id;
            tmpProcess.Deadline__c = Date.today();
            processes.add(tmpProcess);
        }
        
        Database.insert(processes);
        
        Test.stopTest();
        
    }
}