src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Predecessor_Steps__c</fullName>
        <label>Predecessor Steps</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step_Junction__c.object
<CustomObject>
    <description>XLR8 custom object used by the Process Engine to handle Process Template Predecessor Steps functionality.</description>
    <fields>
        <fullName>ParentStep__c</fullName>
        <label>Parent Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Parent)</relationshipLabel>
        <relationshipName>Template_Step_Junctions_Parent</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PredecessorStep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Predecessor Step</label>
        <referenceTo>Process_Template_Step__c</referenceTo>
        <relationshipLabel>Process Template Step Junctions (Predecessors)</relationshipLabel>
        <relationshipName>Process_Template_Step_Junctions_Pred</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step Junction</label>
    <nameField>
        <label>Process Template Step Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Step Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessTemplateStepManager_T.cls
@isTest
private class ProcessTemplateStepManager_T {

	@isTest
	private static void populatesSequence() {
		
		Process_Template__c template = new Process_Template__c(
			Name = 'template1',
			Type__c = 'Entity'
		);
		insert template;
		Process_Template_Step__c step = new Process_Template_Step__c(
			Process_Template__c = template.id,
			Name = 'somecrazyname',
			Assign_To_Role__c = 'Primary Advisor'
		); 
		insert step;
		step = [SELECT Sequence__c FROM Process_Template_Step__c WHERE Id = :step.Id];
		System.assertEquals(1, step.Sequence__c);
	}

	@isTest
	private static void populatePredecessorSequences() {
		Process_Template__c template = new Process_Template__c(
			Name = 'template1',
			Type__c = 'Entity'
		);
		insert template;
		Process_Template_Step__c step = new Process_Template_Step__c(
			Process_Template__c = template.id,
			Name = 'stepnametest2',
			Assign_To_Role__c = 'Primary Advisor',
			Sequence__c = 1
		); 
		insert step;
		Process_Template_Step__c step2 = new Process_Template_Step__c(
			Process_Template__c = template.id,
			Name = 'stepnametest3',
			Assign_To_Role__c = 'Primary Advisor',
			Sequence__c = 2
		); 
		insert step2;
		Process_Template_Step_Junction__c junction = new Process_Template_Step_Junction__c(
			ParentStep__c = step2.Id,
			PredecessorStep__c = step.Id
		);
		insert junction;
		step2 = [SELECT Predecessor_Steps__c FROM Process_Template_Step__c 
			WHERE Id = :step2.Id];
		System.assertEquals('1', step2.Predecessor_Steps__c);
	}	

}