src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Auto_Create_Tasks__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box when you want to auto create tasks for the steps</description>
        <inlineHelpText>Check this box when you want to auto create tasks for the steps</inlineHelpText>
        <label>Auto Create Tasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Process_Template__r.Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Enter the target completion date for the entire process.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine steps. This is the child object to the Process Engine object and holds all of the steps for a given process.</description>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <referenceTo>Process__c</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Step</label>
    <nameField>
        <label>Process Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Client Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_to_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This user will be assigned this step every time the template is instantiated on a record.</inlineHelpText>
        <label>Assign to User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SuperTask_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestValidateAssignedToUsers.cls
//Test Class for VerifyAssignedToUsers Trigger
@isTest
private class TestValidateAssignedToUsers
    {
        //Prepare and insert data
        static testmethod void insertProcesses()
            {
				Account entity = new Account(
					Name = 'testacc'
				);
				insert entity;
				system.assertNotEquals(entity.Id, null);
				
                //Step 1:
                //Create Process Template
                Process_Template__c objProcessTemplate = new Process_Template__c();
                objProcessTemplate.Name = 'Created by Test Method';
                objProcessTemplate.Category__c = 'Sales';
                objProcessTemplate.Type__c = 'Entity';
                upsert objProcessTemplate;                
                
                //Step 2:
                //Create Process Template Steps with Assigned To User Field Filled
                Process_Template_Step__c step1 = new Process_Template_Step__c();
                step1.Name = 'Step 1';
                step1.Assign_to_User__c = UserInfo.getUserID();
                step1.Process_Template__c = objProcessTemplate.id;
                step1.sequence__c = 1;                
                
                Process_Template_Step__c step2 = new Process_Template_Step__c();
                step2.Name = 'Step 2';
                step2.Assign_to_User__c = UserInfo.getUserID();
                step2.Process_Template__c = objProcessTemplate.id;
                step2.sequence__c = 2;
                
                List<Process_Template_Step__c> lstSteps = new List<Process_Template_Step__c>();
                lstSteps.add(step1);
                lstSteps.add(step2);  
                
                upsert lstSteps;               
                
                //Step 3:
                //Insert Process using the Process Template ID created in Step 1
                Process__c objProcess = new Process__c();
                objProcess.Entity__c = entity.Id;
                objProcess.Auto_Create_Tasks__c = true;
                objProcess.Process_Template__c = objProcessTemplate.id;
                objProcess.Deadline__c = Date.Today();
                
                insert objProcess;
                system.assertNotEquals(objProcess.Id, null);
                
                objProcess.Name = 'Process from Test Method';
                update objProcess;
                
                 Test.StartTest();
                
                //Step 4:
                //Insert Process Step
                Process_Step__c objProcessStep = new Process_Step__c();
                objProcessStep.Name = 'Step from Test Method';
                objProcessStep.Process__c = objProcess.id;
                objProcessStep.Sequence__c = 1;
                insert objProcessStep;
                
                Process_Step__c objProcessStep2 = new Process_Step__c();
                objProcessStep2.Name = 'Step 2 from Test Method';
                objProcessStep2.Process__c = objProcess.id;
                objProcessStep2.Sequence__c = 2;
                insert objProcessStep2;
                system.assertNotEquals(objProcessStep2.Id, null);
                               
                //Update Process Step                
                List<Process_Step__c> lstProcessSteps = new List<Process_Step__c>([Select ID, Name from Process_Step__c WHERE Process__c =: objProcess.ID]);
                update lstProcessSteps;                
                
                Test.StopTest();
            }
    }