src/objects/Process__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine master record.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>SuperTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Processes</relationshipLabel>
        <relationshipName>Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template master record.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Process Template</label>
    <nameField>
        <label>Process Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Template_Step__c.object
<CustomObject>
    <description>XLR8 custom object for the Process Engine template steps. This is the child object to the Process Engine template object and holds all of the steps for a given process template.</description>
    <fields>
        <fullName>Assign_To_Case_Role__c</fullName>
        <label>Assign to Case Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Case Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Contact_Role__c</fullName>
        <label>Assign to Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Contact Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Lead_Role__c</fullName>
        <label>Assign to Lead Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Lead Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Opportunity_Role__c</fullName>
        <label>Assign to Opportunity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Sample Opportunity Role</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_To_Role__c</fullName>
        <label>Assign to Entity Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Svcs Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Process Template</label>
        <referenceTo>Process_Template__c</referenceTo>
        <relationshipLabel>Process Template Steps</relationshipLabel>
        <relationshipName>Process_Template_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Process Template Step</label>
    <nameField>
        <label>Process Template Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Template Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessUtils.cls
public with sharing class ProcessUtils {

	 private String getRoleName(String objectType, Process_Template_Step__c templateStep){
    	String roleFieldName = null;
    	
    	if (objectType == 'Account') {
          	roleFieldName = templateStep.Assign_To_Role__c;
        }else if (objectType == 'Lead') {
 			roleFieldName = templateStep.Assign_To_Lead_Role__c;
 		}else if (objectType == 'Contact') {
 			roleFieldName = templateStep.Assign_To_Contact_Role__c;
 		}else if (objectType == 'Opportunity') {
 			roleFieldName = templateStep.Assign_To_Opportunity_Role__c;
 		}else if (objectType == 'Case') {
 			roleFieldName = templateStep.Assign_To_Case_Role__c;
 		}		
 			
 		if (roleFieldName != null && roleFieldName.length() > 0){
	        roleFieldName = roleFieldName.trim() + '__c';
	        roleFieldName = roleFieldName.replaceAll('\\p{Blank}', '_');
 		}
    	
    	
    	return roleFieldName;
    }
    
     public Map<String, Id> getAssignedToUser(List<Process_Template_Step__c> templateSteps, List<Process__c> processes) {
        Set<String> roleFieldNames = new Set<String>();
        String roleFieldName = null;
        String objectType = null;
        Map<String,Id> result = new Map<String,Id>();
        Map<Id,Id>parentIdsMap = new Map<Id,Id>();
        Map<Id,String>stepToRoleField = new Map<Id,String>();
        if (templateSteps != null && templateSteps.size() > 0 && processes != null && processes.size() > 0){
	        objectType = templateSteps.get(0).Process_Template__r.Type__c;
	        
	        if (objectType != 'Entity' && objectType != 'Lead' && objectType != 'Contact' && objectType != 'Case' && objectType != 'Opportunity' ){
	        	throw new ApplicationException('Unsupported object type: ' + objectType);
	        }
	        for (Process__c process1 : processes){
	        	Id parentId = null;
	        	if (objectType == 'Entity'){
	        		parentId = process1.Entity__c;
	        	}else if (objectType == 'Lead') {
	        		parentId = process1.Lead__c;
	        	}else if (objectType == 'Contact') {
	        		parentId = process1.Contact__c;
	        	}else if (objectType == 'Opportunity') {
	        		parentId = process1.Opportunity__c;
	        	}else if (objectType == 'Case') {
	        		parentId = process1.Case__c;
	        	}
	        	parentIdsMap.put(process1.Id, parentId);
	        }
			
			if (objectType == 'Entity'){
	        	objectType = 'Account';
			}
	        
	        
	        for (Process_Template_Step__c step : templateSteps){           
	        	rolefieldName = getRoleName(objectType, step);
	        	if (roleFieldName != null && roleFieldName.length() > 0){
		            roleFieldNames.add(roleFieldName);
		            stepToRoleField.put(step.id,roleFieldName);
	        	}        	
	        }
	        
	        if (roleFieldNames.size() > 0){
	        	roleFieldName = String.join(new List<String>(roleFieldNames), ' , ');
	        	try {
		        	List<String>parentIds = parentIdsMap.values();
		        	String query = 'SELECT ' + roleFieldName + ' FROM ' + objectType + ' WHERE Id IN :parentIds';
		        	Map<Id,SObject> sobjectsMap = new Map<Id,SObject>(Database.query(query));
		            if (!sobjectsMap.isEmpty()) {
		            	for (Id processId : parentIdsMap.keySet()){
		            		Id parentId = parentIdsMap.get(processId);
		            		for (Process_Template_Step__c step : templateSteps){   
								rolefieldName = stepToRoleField.get(step.Id);
								if (sobjectsMap.containsKey(parentId) && roleFieldName  != null && roleFieldName.length() > 0){
									Id userId = (Id)sobjectsMap.get(parentId).get(roleFieldName);
									String key = String.valueOf(processId) + String.valueOf(step.Id);
									result.put(key, userId);
								}
			            	}
		            	}
		            }            
		        }catch (Exception ex) { 
		                throw ex;
		                // assignedToUser = '';
		        }
	        }
        }
	    return result;
    }
    
    public Map<Id,Sobject> getParentOwnerIds(List<Process__c> processes, String templateType){
    	Map<Id,sObject> records = new Map<Id, sObject>();
    	Set<ID> recordIds = new Set<ID>();
    	for (Process__c pProcess : processes){    		
    		Id parentId = getProcessParentOwner(pProcess, templateType);
        	recordIds.add(parentId);
        }
		
		if (templateType == 'Entity'){
        	templateType = 'Account';
		}
		
		if (recordIds.size() > 0){
			String queryString = 'Select Id, OwnerId from ' + templateType + ' Where Id IN :recordIds';
			List<sObject> tmpRecords = Database.query(queryString);
			
			for (sObject o : tmpRecords){
				records.put(o.Id, o);
			}
		}  
		return records;
    }
    
    public Id getProcessParentOwner(Process__c pProcess, String templateType){
    	Id parentId = null;
    	
    	if (pProcess != null && templateType != null){
    		if (templateType == 'Entity'){
        		parentId = pProcess.Entity__c;
        	}else if (templateType == 'Lead') {
        		parentId = pProcess.Lead__c;
        	}else if (templateType == 'Contact') {
        		parentId = pProcess.Contact__c;
        	}else if (templateType == 'Opportunity') {
        		parentId = pProcess.Opportunity__c;
        	}else if (templateType == 'Case') {
        		parentId = pProcess.Case__c;
        	}
    	}
    	
    	return parentId;
    }
    
}