src/objects/RMD_Requirement__c.object
<CustomObject>
    <description>XLR8 custom object for tracking RMD Requirements.</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>XLR8_Assets_Liabilities__c</referenceTo>
        <relationshipLabel>RMD Requirements</relationshipLabel>
        <relationshipName>RMD</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RMD_Calculation_Method__c</fullName>
        <label>RMD Calculation Method</label>
        <picklist>
            <picklistValues>
                <fullName>JOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNIFORM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMD_Member__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Financial_Account__r.RMD_Member__c ,  Financial_Account__r.RMD_Member__r.FirstName + &quot;  &quot; + Financial_Account__r.RMD_Member__r.LastName)</formula>
        <label>RMD Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMD_Override__c</fullName>
        <inlineHelpText>If the RMD has to be manually calculated in the case of Inherited IRAs, etc, then the user will manually calculate the RMD and populate this field with the amount.  If the override is done, that is the amount that will appear in the final RMD Amount field</inlineHelpText>
        <label>RMD Override</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Financial_Account__r.RMD_Spouse__c , Financial_Account__r.RMD_Spouse__r.FirstName + &quot; &quot; + Financial_Account__r.RMD_Spouse__r.LastName)</formula>
        <label>RMD Spouse</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMD_Year__c</fullName>
        <label>RMD Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Previous_EOY__c</fullName>
        <label>Value Previous EOY</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RMD Requirement</label>
    <nameField>
        <label>RMD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XLR8_Assets_Liabilities__c.object
<CustomObject>
    <description>XLR8 custom object that holds Client Household Use Assets, Financial Assets, Retirement Assets and Liabilities data.</description>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets &amp; Liabilities</relationshipLabel>
        <relationshipName>R00N40000001YLFUEA4</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RMD_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMD Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMD Member</relationshipLabel>
        <relationshipName>R00N40000001Zq5kEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMD Spouse</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets &amp; Liabilities (RMD Spouse)</relationshipLabel>
        <relationshipName>Assets_Liabilities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_RMD_Requirement_Records__c</fullName>
        <description>Calculates the amount of RMD Requirements</description>
        <label>Total RMD Requirement Records</label>
        <summaryFilterItems>
            <field>RMD_Requirement__c.RMD_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>RMD_Requirement__c.Financial_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Assets &amp; Liabilities</label>
    <nameField>
        <label>Asset/Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets &amp; Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssetsAndLiabilitiesTrigger.cls
@isTest
public class TestAssetsAndLiabilitiesTrigger {
    
    @testSetup static void setup(){
        
        Account oneEntity = new Account(Name = 'One Entity');
        insert oneEntity;
        
        //create the contacts
        Contact c1 = new Contact();
        Contact c2 = new Contact();
        Contact c3 = new Contact();
        c1.Email = 'John@Doe.com';
        c1.LastName = 'Doe';
        c2.Email = 'Jane@Doe.com';
        c2.LastName = 'Doe';
        c3.Email = 'Jim@Dune.com';
        c3.LastName = 'Dune';
        insert c1; 
        insert c2; 
        insert c3;
        
        //create an asset and liabilities with one RMD requirement
        XLR8_Assets_Liabilities__c assetWithRMDReq = new XLR8_Assets_Liabilities__c();
        assetWithRMDReq.Name = '2345';
        assetWithRMDReq.Entity__c = oneEntity.Id;
        assetWithRMDReq.RMD_Spouse__c = c1.Id;
        assetWithRMDReq.RMD_Member__c = c2.Id;
        insert assetWithRMDReq;
        
        RMD_Requirement__c req1 = new RMD_Requirement__c();
        req1.Financial_Account__c = assetWithRMDReq.Id;
        req1.Name = '2345-' + String.valueOf(date.today().year());
        req1.RMD_Override__c = 600.05;
        req1.RMD_Year__c = String.valueOf(date.today().year());
        req1.RMD_Calculation_Method__c = 'SINGLE';
        req1.Value_Previous_EOY__c = 2000;
        insert req1;
        
        //create one without RMD requirements
        XLR8_Assets_Liabilities__c assetWithoutRMDReq = new XLR8_Assets_Liabilities__c();
        assetWithoutRMDReq.Entity__c = oneEntity.Id;
        assetWithoutRMDReq.RMD_Spouse__c = c1.Id;
        assetWithoutRMDReq.RMD_Member__c = c2.Id;
        insert assetWithoutRMDReq;
    }
    
    @isTest static void testAssetsAndLiabilitiesTrigger(){
        
        Test.startTest();
        
        XLR8_Assets_Liabilities__c assetWithRMDReq = [SELECT Id, RMD_Spouse__c, RMD_Member__c
                                                      FROM XLR8_Assets_Liabilities__c
                                                      WHERE Total_RMD_Requirement_Records__c > 0 LIMIT 1];
        
        XLR8_Assets_Liabilities__c assetWithoutRMDReq = [SELECT Id, RMD_Spouse__c, RMD_Member__c
                                                      FROM XLR8_Assets_Liabilities__c
                                                      WHERE Total_RMD_Requirement_Records__c = 0 LIMIT 1];
        
        Contact c1 = [SELECT Id 
                      FROM Contact
                      WHERE Email = 'John@Doe.com' LIMIT 1];   
        Contact c2 = [SELECT Id 
                      FROM Contact
                      WHERE Email = 'Jane@Doe.com' LIMIT 1];
        Contact c3 = [SELECT Id 
                      FROM Contact
                      WHERE Email = 'Jim@Dune.com' LIMIT 1];                             
        system.debug('c1 ' + c1.Id + ' c2 ' + c2.Id + ' c3 ' + c3.Id);
                                                                
        //change the member and spouse on the one without rmd reqs
        assetWithRMDReq.RMD_Spouse__c = c3.Id;
        assetWithRMDReq.RMD_Member__c = c3.Id;
        try{
            update assetWithRMDReq;
        }catch(DmlException ex){
            system.debug('Could not update exception ' + assetWithRMDReq.RMD_Member__c + ' - ' + assetWithRMDReq.RMD_Spouse__c);
        }
        
        //change the member and spouse on the one with rmd reqs
        assetWithoutRMDReq.RMD_Spouse__c = c3.Id;
        assetWithoutRMDReq.RMD_Member__c = c3.Id;
        update assetWithoutRMDReq;
        
        Test.stopTest();
        
        
        XLR8_Assets_Liabilities__c finalAssetWithRMDReq = [SELECT Id, RMD_Spouse__c, RMD_Member__c
                                                           FROM XLR8_Assets_Liabilities__c
                                                           WHERE Total_RMD_Requirement_Records__c > 0 LIMIT 1];
        system.debug('before c2.Id -' + c2.Id + ' now-' + finalAssetWithRMDReq.RMD_Member__c);                                              
        system.assert(finalAssetWithRMDReq.RMD_Member__c != c3.Id, 'The member was changed, when it should have not.');
        system.assert(finalAssetWithRMDReq.RMD_Spouse__c != c3.Id, 'The spouse was changed, when it should have not.');
        
        system.assert(assetWithoutRMDReq.RMD_Spouse__c == c3.Id, 'The spouse was not changed, when it should have.');
        system.assert(assetWithoutRMDReq.RMD_Member__c == c3.Id, 'The member was not changed, when it should have.');
    }
}