src/objects/RMD_Requirement__c.object
<CustomObject>
    <description>XLR8 custom object for tracking RMD Requirements.</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>XLR8_Assets_Liabilities__c</referenceTo>
        <relationshipLabel>RMD Requirements</relationshipLabel>
        <relationshipName>RMD</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RMD_Member__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Financial_Account__r.RMD_Member__c ,  Financial_Account__r.RMD_Member__r.FirstName + &quot;  &quot; + Financial_Account__r.RMD_Member__r.LastName)</formula>
        <label>RMD Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; + Financial_Account__r.RMD_Spouse__c , Financial_Account__r.RMD_Spouse__r.FirstName + &quot; &quot; + Financial_Account__r.RMD_Spouse__r.LastName)</formula>
        <label>RMD Spouse</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMD_Year__c</fullName>
        <label>RMD Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RMD Requirement</label>
    <nameField>
        <label>RMD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XLR8_Assets_Liabilities__c.object
<CustomObject>
    <description>XLR8 custom object that holds Client Household Use Assets, Financial Assets, Retirement Assets and Liabilities data.</description>
    <fields>
        <fullName>RMD_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMD Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMD Member</relationshipLabel>
        <relationshipName>R00N40000001Zq5kEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RMD Spouse</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assets &amp; Liabilities (RMD Spouse)</relationshipLabel>
        <relationshipName>Assets_Liabilities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_RMD_Requirement_Records__c</fullName>
        <description>Calculates the amount of RMD Requirements</description>
        <label>Total RMD Requirement Records</label>
        <summaryFilterItems>
            <field>RMD_Requirement__c.RMD_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>RMD_Requirement__c.Financial_Account__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Assets &amp; Liabilities</label>
    <nameField>
        <label>Asset/Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets &amp; Liabilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssetsAndLiabilitiesTriggerUtils.cls
/*
 * Utils class for AssetsAndLiabilitiesTrigger
 * @author Ximena Lasserre
 * @since Mar 2015
 */
public class AssetsAndLiabilitiesTriggerUtils {
	
	/*
     * Checks if every asset that is passed as an argument
     * has at least one total rmd requirement record, if not
     * it adds an error to the object
     * @param Map<Id, XLR8_Assets_Liabilities__c> mapNew - map of the new XLR8_Assets_Liabilities__c 
     * @param Map<Id, XLR8_Assets_Liabilities__c> mapOld - map of the original XLR8_Assets_Liabilities__c  
     */
    public void verifyIfRMDRequirements(Map<Id, XLR8_Assets_Liabilities__c> mapNew, Map<Id, XLR8_Assets_Liabilities__c> mapOld){
        
       
        		List<Id> allAssetsIds = new List<Id>();
		        for(XLR8_Assets_Liabilities__c asset : mapNew.values()){
		            if(asset.Total_RMD_Requirement_Records__c != null && asset.Total_RMD_Requirement_Records__c > 0 &&
		            (mapOld.get(asset.Id).RMD_Spouse__c != null || mapOld.get(asset.Id).RMD_Member__c != null) &&
		            (asset.RMD_Spouse__c != mapOld.get(asset.Id).RMD_Spouse__c || asset.RMD_Member__c != mapOld.get(asset.Id).RMD_Member__c)){
		            	allAssetsIds.add(asset.Id);
		            }
		        }
		        //query the rmdRequirements whose financial account id is the same as in allAssetsIds
		        List<RMD_Requirement__c> rmdRequirements = new List<RMD_Requirement__c>(); 
		        if(allAssetsIds.size() > 0){
		        	rmdRequirements = [SELECT Id, Financial_Account__c, RMD_Year__c
		            				   FROM RMD_Requirement__c
		                               WHERE Financial_Account__c IN :allAssetsIds];
		        }
		        
		        
		        String currentYear = String.valueOf(date.today().year());
		        
		        if(rmdRequirements.size() > 0){
			        for(RMD_Requirement__c rmd : rmdRequirements){
			            if(rmd.RMD_Year__c == currentYear){
			                mapNew.get(rmd.Financial_Account__c).addError(' The RMD Member and RMD Spouse cannot be modified if an ' +
			                        'RMD Requirement record exists for this Retirement Asset for the current RMD year.');
			            }
			        }   
		        }     
                                              
    }
}