src/objects/RMD_Factors__c.object
<CustomObject>
    <description>XLR8 custom object that contains the RMD Uniform, Single and Joint IRS Life Expectancy Values, which are used to calculate RMD.</description>
    <fields>
        <fullName>Age_EOY_2__c</fullName>
        <label>Age EOY 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Age_EOY__c</fullName>
        <label>Age EOY</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Calculation_Type__c</fullName>
        <label>Calculation Type</label>
        <picklist>
            <picklistValues>
                <fullName>JOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNIFORM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMD_Factor__c</fullName>
        <label>RMD Factor</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>RMD Factors</label>
    <nameField>
        <label>RMD Table ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RMD_Requirement__c.object
<CustomObject>
    <description>XLR8 custom object for tracking RMD Requirements.</description>
    <fields>
        <fullName>RMD_Calculated__c</fullName>
        <label>RMD Calculated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RMD_Calculation_Method__c</fullName>
        <label>RMD Calculation Method</label>
        <picklist>
            <picklistValues>
                <fullName>JOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNIFORM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMD_Factor__c</fullName>
        <inlineHelpText>This is the RMD factor used in the RMD Amount calculation, taken from the IRS Life Expectancy Table.</inlineHelpText>
        <label>RMD Factor</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Last_Updated_Date__c</fullName>
        <description>Date of the last update.</description>
        <label>RMD Last Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RMD_Member_Age_EOY__c</fullName>
        <formula>FLOOR( (DATE(VALUE( RMD_Year__c ), 12, 31) - Financial_Account__r.RMD_Member__r.Birthdate ) / 365.25)</formula>
        <label>RMD Member Age EOY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse_Age_EOY__c</fullName>
        <formula>IF(OR( ISPICKVAL( RMD_Calculation_Method__c , &apos;UNIFORM&apos;),ISPICKVAL( RMD_Calculation_Method__c , &apos;SINGLE&apos;) ),NULL, FLOOR((DATE( VALUE( RMD_Year__c ), 12, 31) - Financial_Account__r.RMD_Spouse__r.Birthdate ) / 365.25))</formula>
        <label>RMD Spouse Age EOY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value_Previous_EOY__c</fullName>
        <label>Value Previous EOY</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RMD Requirement</label>
    <nameField>
        <label>RMD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RmdCalcuatedAmountUtils.cls
/*
 * Utils class for RMD Calculations
 * @author Ang?lica Buffa, Ximena Lasserre
 * @since Mar 2015
 */
public without sharing class RmdCalcuatedAmountUtils {
    // Private constants
    private static final String UNIFORM_CALCULATION_METHOD = 'UNIFORM';
    private static final STring SINGLE_CALCULATION_METHOD = 'SINGLE';
    prIvate static final String JOINT_CALCULATION_METHOD = 'JOINT';  
      
    /* This methods calculates RMD for a subset of RMD Requirements
     * @param factors list of factors that can match the requirements
     * @param requirements list of requirements that need to be calculated
     * @param ExecutedTime datetime stamp that indicates when the rmd amount was calculated
     * @return collection of datbase save result. 
     */
    public Database.saveResult[] calculateRmdAmount(List<RMD_Factors__c> factors, List<RMD_Requirement__c> requirements, DateTime executedTime){
        Database.saveResult[] dbSaveResult;
        List<RMD_Requirement__c> requirementsToUpdate = new List<RMD_Requirement__c>();
        
        if (factors != null && requirements != null){
            // For each requirement we have to identify the factor that matches the Member Age, Spouse Age, and
            // Calculation Method
            for (RMD_Requirement__c requirement : requirements){
                Integer index = 0;
                Boolean factorFound = false;        
                while (!factorFound && index < factors.size() ){
                    RMD_Factors__c factor = factors.get(index);
                    // Check if the calculation method matches and
                    // ensure the factors is greater than cero to avoid Math.DivideByCero exception
                    if (requirement.RMD_Calculation_Method__c != null && 
                        requirement.RMD_Calculation_Method__c != '' &&
                        requirement.RMD_Calculation_Method__c == factor.Calculation_Type__c &&
                        factor.RMD_Factor__c != null && factor.RMD_Factor__c > 0){
                        // Member and spouse age must match if calculation type is joint. 
                        // member age must match if calculation type is single or uniform
                        if ((factor.Calculation_Type__c.toUpperCase() == JOINT_CALCULATION_METHOD  &&
                            requirement.RMD_Member_Age_EOY__c == factor.Age_EOY__c &&
                            requirement.RMD_Spouse_Age_EOY__c == factor.Age_EOY_2__c) ||
                            ((factor.Calculation_Type__c.toUpperCase() == SINGLE_CALCULATION_METHOD  ||
                            factor.Calculation_Type__c.toUpperCase() == UNIFORM_CALCULATION_METHOD ) &&
                            requirement.RMD_Member_Age_EOY__c == factor.Age_EOY__c)){
                            factorFound = true;   
                        }  
                    }
                    // Calculate RMD amount if there is a matching factor for current member
                    if (factorFound){
                        requirement.RMd_Factor__c = factor.RMD_Factor__c;
                        requirement.RMD_Calculated__c = requirement.Value_Previous_EOY__c / factor.RMD_Factor__c;
                        requirement.RMD_Last_Updated_Date__c = executedTime;
                        requirementsToUpdate.add(requirement);              
                    }
                    index++;
                }
            }
            
            if (requirementsToUpdate.size() > 0){ 
                try{
                    //update requirements
                    dbSaveResult = Database.update(requirementsToUpdate, false);
                    system.debug('save result 0 ' + dbSaveResult[0]);
                }catch(Exception ex){}
            }           
        }
        return dbSaveResult;
    }
}