src/objects/RMD_Factors__c.object
<CustomObject>
    <description>XLR8 custom object that contains the RMD Uniform, Single and Joint IRS Life Expectancy Values, which are used to calculate RMD.</description>
    <fields>
        <fullName>RMD_Factor__c</fullName>
        <label>RMD Factor</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>RMD Factors</label>
    <nameField>
        <label>RMD Table ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RMD_Requirement__c.object
<CustomObject>
    <description>XLR8 custom object for tracking RMD Requirements.</description>
    <fields>
        <fullName>RMD_Calculated__c</fullName>
        <label>RMD Calculated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RMD_Calculation_Method__c</fullName>
        <label>RMD Calculation Method</label>
        <picklist>
            <picklistValues>
                <fullName>JOINT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNIFORM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RMD_Factor__c</fullName>
        <inlineHelpText>This is the RMD factor used in the RMD Amount calculation, taken from the IRS Life Expectancy Table.</inlineHelpText>
        <label>RMD Factor</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Member_Age_EOY__c</fullName>
        <formula>FLOOR( (DATE(VALUE( RMD_Year__c ), 12, 31) - Financial_Account__r.RMD_Member__r.Birthdate ) / 365.25)</formula>
        <label>RMD Member Age EOY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Spouse_Age_EOY__c</fullName>
        <formula>IF(OR( ISPICKVAL( RMD_Calculation_Method__c , &apos;UNIFORM&apos;),ISPICKVAL( RMD_Calculation_Method__c , &apos;SINGLE&apos;) ),NULL, FLOOR((DATE( VALUE( RMD_Year__c ), 12, 31) - Financial_Account__r.RMD_Spouse__r.Birthdate ) / 365.25))</formula>
        <label>RMD Spouse Age EOY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RMD_Year__c</fullName>
        <label>RMD Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Previous_EOY__c</fullName>
        <label>Value Previous EOY</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>RMD Requirement</label>
    <nameField>
        <label>RMD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMD Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RMDAmountBatchCalculator.cls
/* This class Implements Batchable and is used to calculate the RMD Amount for a subset of 
 * RMD requirements that match a given year 
 * @author Angelica Buffa
 * @since March 2015
 */
public with sharing class RMDAmountBatchCalculator implements
		Database.Batchable<sObject>, Database.Stateful{
	
	// Private instance variables	
	private String  year { get; set; }
	private Database.saveResult[] databaseResults {get;set;}
	private Integer numberOfSuccess {get;set;}
	private Integer numberOfErrors {get;set;}
	private Integer totRequirements {get;set;}	
	
	//datetime the batch was executed
	public Datetime executedDate {get;set;}
	
	// Constructor
	public RMDAmountBatchCalculator(String year){
		this.year = year;
		numberOfSuccess = 0;
		numberOfErrors = 0;
		totRequirements = 0;
	}
	
  	public Database.QueryLocator start(Database.BatchableContext BC){
  		
        DateTime executedDateGMT = datetime.now();
        Date d = executedDateGMT.date();
        Time t = executedDateGMT.time();
        executedDate = Datetime.newInstance(d,t);
    
      	return Database.getQueryLocator([SELECT RMD_Calculated__c, 
      											Value_Previous_EOY__c, 
      											RMD_Year__c, 
      											RMD_Factor__c, 
												RMD_Calculation_Method__c,
									   			RMD_Spouse_Age_EOY__c,
									   			RMD_Member_Age_EOY__c
										FROM RMD_Requirement__c 
										WHERE RMD_Year__c = :year]);
   	}

   	public void execute(Database.BatchableContext BC, List<RMD_Requirement__c> rmdRequirements){
   		if(rmdRequirements != null){ 
	     	List<RMD_Factors__c> rmdFactors = RMDCalculatorUtils.getRMDFactors(rmdRequirements);
			databaseResults = RMDCalculatorUtils.calculateRMDAmount(rmdFactors, rmdRequirements, executedDate);
			//add the total amount of requirements to the previous quantity
			totRequirements += rmdRequirements.size();
			//add the successes to numberOfSuccess
	   		if(databaseResults != null && databaseResults.size() > 0){
	   			for(Database.saveResult result : databaseResults){
		   			if(result.isSuccess()){
		   				numberOfSuccess++;
		   			}
		   		}
   			}	
   		}
    }

   	public void finish(Database.BatchableContext BC){
   		
   		if(totRequirements > numberOfSuccess){
   			numberOfErrors = totRequirements - numberOfSuccess;
   		}
   		RMDCalculatorUtils.sendNotification(UserInfo.getUserId(), numberOfErrors, numberOfSuccess, year, executedDate);	
   	}
}