src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is intended to be a one-time setting to turn on Predecessor functionality for existing XLR8 users receiving package upgrade XLR8 V3.0.  This setting turns Predecessor functionality on for any newly instantiated processes and will not affect already existing processes.</description>
    <fields>
        <fullName>UseTaskHistory__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enable Task History</label>
        <type>Checkbox</type>
    </fields>
    <label>Settings</label>
</CustomObject>

src/classes/SettingsManagerTest.cls
/*
 *Test class for SettingsManager class
 *@author Ximena Lasserre
 *@since October 2015
 */
@isTest
public with sharing class SettingsManagerTest {

	@testSetup static void setup(){
		Settings__c settings = new Settings__c();
		settings.Name = 'Default Settings';
		settings.UseTaskHistory__c = true;
		insert settings;
	}
	
	static testmethod void SettingsManagerTest(){
		Test.startTest();
		
		Settings__c settingsObj = SettingsManager.getSettings();
		
		Test.stopTest();
		
		system.assert(settingsObj != null, 'There were no settings returned.');
	}
}